import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import test from "node:test";

const componentUrl = new URL("../components/design-lab/DesignLab.js", import.meta.url);
const componentSource = existsSync(componentUrl) ? readFileSync(componentUrl, "utf8") : "";
const catalogSource = readFileSync(new URL("../lib/designLab.mjs", import.meta.url), "utf8");
const indexSource = readFileSync(new URL("../pages/index.js", import.meta.url), "utf8");
const sessionSource = readFileSync(new URL("../lib/sessionPersistence.mjs", import.meta.url), "utf8");
const workspaceSource = readFileSync(new URL("../lib/workspaces.mjs", import.meta.url), "utf8");

test("design lab component renders catalog tabs and practice actions", () => {
  assert.match(componentSource, /DESIGN_LAB_CATALOG/);
  assert.match(componentSource, /Design Lab/);
  assert.match(componentSource, /Patterns/);
  assert.match(componentSource, /HLD/);
  assert.match(componentSource, /LLD/);
  assert.match(componentSource, /OOD \/ UML/);
  assert.match(componentSource, /Agentic AI/);
  assert.match(componentSource, /Curriculum/);
  assert.match(componentSource, /Practice/);
  assert.match(componentSource, /WorkflowDiagram/);
  assert.match(componentSource, /UmlClassBoard/);
  assert.match(componentSource, /AgenticAiBoard/);
  assert.match(componentSource, /ReferencePlaybookBoard/);
  assert.match(componentSource, /DesignSearchPanel/);
  assert.match(componentSource, /Search Any System/);
  assert.match(componentSource, /Search any design system/);
  assert.match(componentSource, /Generate Answer/);
  assert.match(componentSource, /buildDesignSystemSearchPrompt/);
  assert.match(componentSource, /designSystemSearch/);
  assert.match(componentSource, /Pictorial Workflow/);
  assert.match(componentSource, /Step \{index \+ 1\}/);
  assert.match(componentSource, /Java Example/);
  assert.match(componentSource, /Spring Boot Example/);
  assert.match(componentSource, /Interview Traps/);
  assert.match(componentSource, /Practice UML/);
  assert.match(componentSource, /Practice Agent Design/);
  assert.match(componentSource, /buildUmlClassDesignPrompt/);
  assert.match(componentSource, /buildAgenticAiDesignPrompt/);
  assert.match(componentSource, /buildReferencePlaybookPrompt/);
  assert.match(componentSource, /Practice Track/);
  assert.match(componentSource, /Diagrammatic Drills/);
  assert.match(componentSource, /Build-from-Scratch Tracks/);
  assert.match(componentSource, /Handbook Sprint Checklist/);
  assert.match(componentSource, /Practice Curriculum/);
  assert.match(componentSource, /Full-context practice maps/);
  assert.match(componentSource, /Practice Topic Maps/);
  assert.match(componentSource, /Full context by practice area/);
  assert.match(componentSource, /Build Topic Plan/);
  assert.match(componentSource, /listReferenceTopicCatalog/);
  assert.match(componentSource, /buildReferenceTopicImportPrompt/);
  assert.match(componentSource, /Practice Drills/);
  assert.match(componentSource, /Practice Outcomes/);
  assert.match(componentSource, /Start Here/);
  assert.match(componentSource, /Beginner Explainer/);
  assert.match(componentSource, /Visual Flow/);
  assert.match(componentSource, /Difficulty Path/);
  assert.match(componentSource, /Try This Practice/);
  assert.match(componentSource, /Common Confusions/);
  assert.doesNotMatch(componentSource, /href=\{group\.url\}|group\.url|group\.source|Source/);
  assert.match(componentSource, /Primer Topic Map/);
  assert.match(catalogSource, /Search Engine/);
  assert.match(catalogSource, /Behavioral Story Bank/);
  assert.match(catalogSource, /CAP theorem/);
  assert.match(catalogSource, /Web Browser/);
  assert.match(catalogSource, /Grind 75/);
  assert.match(componentSource, /onAction/);
  assert.match(componentSource, /buildDesignLabPracticePrompt/);
  assert.match(componentSource, /overflowWrap/);
});

test("design lab is wired as a first-class workspace", () => {
  assert.match(indexSource, /DesignLab/);
  assert.match(indexSource, /activeTab==="designLab"/);
  assert.match(workspaceSource, /Design Lab/);
  assert.match(workspaceSource, /ti-puzzle/);
  assert.match(indexSource, /startDesignLabAction/);
  assert.match(sessionSource, /normalizeWorkspaceTab/);
  assert.match(workspaceSource, /designLab/);
});
