import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import test from "node:test";

const componentUrl = new URL("../components/java-digest/JavaDigest.js", import.meta.url);
const componentSource = existsSync(componentUrl) ? readFileSync(componentUrl, "utf8") : "";
const globalStylesSource = readFileSync(new URL("../styles/globals.css", import.meta.url), "utf8");
const indexSource = readFileSync(new URL("../pages/index.js", import.meta.url), "utf8");
const workspaceSource = readFileSync(new URL("../lib/workspaces.mjs", import.meta.url), "utf8");
const tutorialPageSource = readFileSync(new URL("../pages/java/tutorial/[slug].js", import.meta.url), "utf8");

test("java digest component renders topic, article, and roadmap sections", () => {
  assert.match(componentSource, /JAVA_DIGEST_TRACKS/);
  assert.match(componentSource, /CSES_JAVA_PARTS/);
  assert.match(componentSource, /Java Digest/);
  assert.match(componentSource, /Java Curriculum/);
  assert.match(componentSource, /Java \+ Spring/);
  assert.match(componentSource, /Java \+ Spring Study Path/);
  assert.match(componentSource, /JAVA_SPRING_STUDY_PATHS/);
  assert.match(componentSource, /StudyPathCard/);
  assert.match(componentSource, /Quick Reference/);
  assert.match(componentSource, /Interview Q&A/);
  assert.match(componentSource, /JAVA_INTERVIEW_QA/);
  assert.match(componentSource, /STAR story/);
  assert.match(componentSource, /Production Scenarios/);
  assert.match(componentSource, /End-to-end triage/);
  assert.match(componentSource, /Customer impact/);
  assert.match(componentSource, /JAVA_PRODUCTION_SCENARIOS/);
  assert.match(componentSource, /Table of contents/);
  assert.match(componentSource, /Print lesson/);
  assert.match(componentSource, /Copy link/);
  assert.match(componentSource, /canonical/);
  assert.match(componentSource, /navigateArticle/);
  assert.match(componentSource, /exactArticle/);
  assert.match(componentSource, /Detailed answer/);
  assert.match(componentSource, /QuickReferenceCard/);
  assert.match(componentSource, /Self-check:/);
  assert.match(componentSource, /path.level/);
  assert.match(componentSource, /reference.level/);
  assert.match(componentSource, /Tutorial Library/);
  assert.match(componentSource, /Practice Lab/);
  assert.match(componentSource, /JAVA_TUTORIAL_CATALOG/);
  assert.match(componentSource, /JAVA_VERSION_TOPIC_GUIDE/);
  assert.match(componentSource, /JAVA_PROGRAM_EXAMPLES/);
  assert.match(componentSource, /JAVA_QUIZ_BANK/);
  assert.match(componentSource, /tutorialSearch/);
  assert.match(componentSource, /tutorialCategory/);
  assert.match(componentSource, /Find a topic/);
  assert.match(componentSource, /Remember it:/);
  assert.match(componentSource, /Recall without looking:/);
  assert.match(componentSource, /Do it:/);
  assert.match(componentSource, /Detailed pattern answer/);
  assert.match(componentSource, /How it works:/);
  assert.match(componentSource, /Advantages:/);
  assert.match(componentSource, /Disadvantages:/);
  assert.match(componentSource, /STAR answer:/);
  assert.match(componentSource, /parseStarStory/);
  assert.match(componentSource, /Make it yours:/);
  assert.match(componentSource, /\["Situation", "Task", "Action", "Result"\]/);
  assert.match(componentSource, /Competitive Programming in Java/);
  assert.match(componentSource, /VIEW_METADATA/);
  assert.match(componentSource, /viewMetadata\.title/);
  assert.match(componentSource, /viewMetadata\.description/);
  assert.match(componentSource, /Search Interview Topic/);
  assert.match(componentSource, /java-digest-search-control/);
  assert.match(componentSource, /buildJavaDigestGeneratedTopicPrompt/);
  assert.match(componentSource, /\/api\/chat/);
  assert.match(componentSource, /directAnswer/);
  assert.match(componentSource, /AI Interview Explainer/);
  assert.match(componentSource, /CsesChapterCard/);
  assert.match(componentSource, /CsesPartSection/);
  assert.match(componentSource, /expandedChapterId/);
  assert.match(componentSource, /expandedPartId/);
  assert.match(componentSource, /toggleExpandedPart/);
  assert.match(componentSource, /java-digest-part-/);
  assert.match(componentSource, /aria-expanded=\{expanded\}/);
  assert.match(componentSource, /java-digest-progress/);
  assert.match(componentSource, /complete, original Java practice path/);
  assert.match(componentSource, /Detailed Explanation/);
  assert.match(componentSource, /Beginner Explainer/);
  assert.match(componentSource, /What is this\?/);
  assert.match(componentSource, /Why does it matter\?/);
  assert.match(componentSource, /Where is it used\?/);
  assert.match(componentSource, /How To Think About It/);
  assert.match(componentSource, /Java Implementation Notes/);
  assert.match(componentSource, /Worked Example/);
  assert.match(componentSource, /Java Sketch/);
  assert.match(componentSource, /Deep Study Path/);
  assert.match(componentSource, /Interview Answer/);
  assert.match(componentSource, /Common Mistakes/);
  assert.match(componentSource, /Practice Tasks/);
  assert.match(componentSource, /Explain More/);
  assert.match(componentSource, /Show Less/);
  assert.doesNotMatch(componentSource, /Java Implementation Checkpoint/);
  assert.match(componentSource, /Study Chapter in Java/);
  assert.match(componentSource, /buildCsesJavaPracticePrompt/);
  assert.match(componentSource, /searchDraft/);
  assert.match(componentSource, /submitSearch/);
  assert.match(componentSource, /interface/);
  assert.match(componentSource, /segment tree/);
  assert.match(componentSource, /Articles/);
  assert.match(componentSource, /Article Filters/);
  assert.match(componentSource, /All Articles/);
  assert.match(componentSource, /expandedArticleId/);
  assert.match(componentSource, /Open Lesson/);
  assert.match(componentSource, /Close Lesson/);
  assert.match(componentSource, /Roadmaps/);
  assert.match(componentSource, /Complete Java Senior Refresher/);
  assert.match(componentSource, /PDF \+ Curated Q&A Bank/);
  assert.doesNotMatch(componentSource, /The PDF&apos;s senior interview questions and answer blocks are presented below verbatim as searchable study cards/);
  assert.match(componentSource, /Filter Java senior refresher questions and answers/);
  assert.match(componentSource, /All sections/);
  assert.match(componentSource, /Filter refresher questions by section/);
  assert.match(componentSource, /java-digest-refresher-toolbar/);
  assert.match(componentSource, /Random Question/);
  assert.match(componentSource, /Mark Reviewed/);
  assert.match(componentSource, /Mark Mastered/);
  assert.doesNotMatch(componentSource, /<iframe/);
  assert.doesNotMatch(componentSource, /Ask AI About This Refresher/);
  assert.match(componentSource, /Practice Mode/);
  assert.match(componentSource, /Reveal Source Answer/);
  assert.match(componentSource, /Score with AI/);
  assert.match(componentSource, /Search interface, deserialization, segment tree/);
  assert.match(componentSource, /Java Digest \{JAVA_DIGEST_VERSION\}/);
  assert.match(componentSource, /Mastery \{competencySummary\.masteryScore\}%/);
  assert.match(componentSource, /Coverage \{competencySummary\.completedTopics\}/);
  assert.match(componentSource, /java-digest-radar/);
  assert.match(componentSource, /Coach Me/);
  assert.match(componentSource, /Mock Drill/);
  assert.match(componentSource, /Build My Plan/);
  assert.match(componentSource, /View Full Roadmap/);
  assert.match(componentSource, /roadmap\.days\.slice\(0, 3\)/);
  assert.match(componentSource, /expandedRoadmapId/);
  assert.match(componentSource, /expandedRefresherQuestionId/);
  assert.match(componentSource, /fetch\("\/api\/java-senior-refresher"/);
  assert.match(componentSource, /\}, \[activeView, refresherQuestions\.length\]\);/);
  assert.doesNotMatch(componentSource, /\}, \[activeView, refresherLoading, refresherQuestions\.length\]\);/);
  assert.doesNotMatch(componentSource, /expandedRefresherQuestions/);
  assert.match(componentSource, /buildJavaDigestCoachPrompt/);
  assert.match(componentSource, /buildJavaDigestMockPrompt/);
  assert.doesNotMatch(componentSource, /#a7f3d0|#d1fae5/);
  assert.match(componentSource, /var\(--jd-text\)/);
  assert.match(globalStylesSource, /--jd-background/);
  assert.match(globalStylesSource, /--jd-surface-sunken/);
  assert.match(globalStylesSource, /\.java-digest-card\.is-expanded/);
  assert.doesNotMatch(globalStylesSource, /\.java-digest \[style\*=/);
});

test("published tutorial pages guard stale slugs and provide share fallback", () => {
  assert.match(tutorialPageSource, /if \(!tutorial\) return \{ notFound: true \}/);
  assert.match(tutorialPageSource, /navigator\.clipboard\.writeText/);
  assert.match(tutorialPageSource, /error\?\.name === "AbortError"/);
});

test("java digest is wired as a first-class workspace", () => {
  assert.match(indexSource, /JavaDigest/);
  assert.match(indexSource, /activeTab==="javaDigest"/);
  assert.match(indexSource, /startJavaDigestAction/);
  assert.match(workspaceSource, /javaDigest/);
  assert.match(workspaceSource, /Java Digest/);
  assert.match(workspaceSource, /ti-news/);
});
