import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { gotoSeededApp } from './helpers/app.js';

test.use({ serviceWorkers: 'block' });
for (const width of [390, 1440]) test(`advanced workshop and mock review at ${width}px`, async ({ page }) => {
  await page.setViewportSize({ width, height: 900 });
  let aiCalls = 0;
  await page.route('**/api/chat', route => { aiCalls++; return route.abort(); });
  await gotoSeededApp(page, { activeTab: 'course', homeDemoSeen: true });
  const workshops = page.getByRole('region', { name: 'Advanced AI engineering workshops' });
  await workshops.getByLabel('Choose a workshop').selectOption('advanced-serving');
  await expect(workshops.getByText(/average in-flight requests are about 60/)).toBeVisible();
  await workshops.getByText('Reveal workshop solution and acceptance checks').click();
  await expect(workshops.getByText(/Average in-flight work is 60/)).toBeVisible();
  const simulator = page.getByRole('region', { name: 'Timed scenario interviews' });
  await simulator.getByLabel('Interview scenario').selectOption('cache-review');
  await simulator.getByLabel('Time budget').selectOption('0');
  await simulator.getByRole('button', { name: 'Start interview' }).click();
  await expect(simulator.getByRole('timer')).toHaveText('Untimed round');
  await expect(simulator.getByRole('region', { name: 'Interview answer review' })).toHaveCount(0);
  const next = simulator.getByRole('button', { name: 'Submit answer and get follow-up' });
  await expect(next).toBeDisabled();
  await simulator.getByLabel('Your main answer', { exact: true }).fill('Disable shared caching and test isolation using two tenants and the same question.');
  await next.click();
  await expect(simulator.getByText(/A developer adds tenantId/)).toBeVisible();
  const finish = simulator.getByRole('button', { name: 'Finish round and review answers' });
  await expect(finish).toBeDisabled();
  await simulator.getByLabel('Your follow-up answer').fill('Derive tenant and effective permissions from authenticated server state, not the body.');
  await finish.click();
  const review = simulator.getByRole('region', { name: 'Interview answer review' });
  await expect(review.getByRole('heading', { name: 'Follow-up answer explained' })).toBeVisible();
  await review.getByRole('checkbox').first().check();
  await expect(review.getByRole('status')).toContainText('1/4');
  await review.getByLabel('Rewrite your answer after review').fill('Contain, invalidate, enforce trusted access scope, and independently test revocation.');
  const download = page.waitForEvent('download');
  await review.getByRole('button', { name: 'Download my interview review' }).click();
  const file = await download;
  expect(file.suggestedFilename()).toBe('cache-review-interview-review.md');
  const contents = await readFile(await file.path(), 'utf8');
  expect(contents).toContain('Disable shared caching');
  expect(contents).toContain('1/4 criteria marked');
  expect(contents).toContain('independently test revocation');
  expect(await simulator.evaluate(el => el.scrollWidth - el.clientWidth)).toBeLessThanOrEqual(1);
  await page.screenshot({ path: `/private/tmp/advanced-interview-${width}.png` });
  await review.getByRole('button', { name: 'Try this scenario again' }).click();
  await expect(simulator.getByRole('region', { name: 'Interview answer review' })).toHaveCount(0);
  await simulator.getByRole('button', { name: 'Start interview' }).click();
  await expect(simulator.getByLabel('Your main answer', { exact: true })).toHaveValue('');
  await simulator.getByLabel('Interview scenario').selectOption('rag-launch');
  await expect(simulator.getByRole('button', { name: 'Start interview' })).toBeVisible();
  expect(aiCalls).toBe(0);
});

test('mock timer pauses, resumes and expires without revealing answers', async ({ page }) => {
  await gotoSeededApp(page, { activeTab: 'course', homeDemoSeen: true });
  await page.clock.install();
  const simulator = page.getByRole('region', { name: 'Timed scenario interviews' });
  await simulator.getByLabel('Time budget').selectOption('300');
  await simulator.getByRole('button', { name: 'Start interview' }).click();
  await page.clock.fastForward(60000);
  await expect(simulator.getByRole('timer')).toHaveText('4:00 remaining');
  await simulator.getByRole('button', { name: 'Pause timer' }).click();
  await page.clock.fastForward(60000);
  await expect(simulator.getByRole('timer')).toHaveText('4:00 remaining');
  await simulator.getByRole('button', { name: 'Resume timer' }).click();
  await page.clock.fastForward(241000);
  await expect(simulator.getByRole('timer')).toHaveText('0:00 remaining');
  await expect(simulator.getByRole('status')).toContainText('Time is up');
  await expect(simulator.getByRole('region', { name: 'Interview answer review' })).toHaveCount(0);
  await simulator.getByLabel('Your main answer', { exact: true }).fill('Preserve my draft after expiry.');
  await simulator.getByRole('button', { name: 'Submit answer and get follow-up' }).click();
  await expect(simulator.getByLabel('Your main answer', { exact: true })).toHaveValue('Preserve my draft after expiry.');
});
