import { test, expect } from '@playwright/test';
import { gotoSeededApp } from './helpers/app.js';

test.use({ serviceWorkers: 'block' });
for (const width of [390, 1440]) test(`beginner paths and inspectable RAG at ${width}px`, async ({ page }) => {
  await page.setViewportSize({ width, height: 900 });
  let calls = 0;
  await page.route('**/api/chat', route => { calls++; return route.abort(); });
  await gotoSeededApp(page, { activeTab: 'course', homeDemoSeen: true });
  const genai = page.getByRole('region', { name: 'Generative AI for Developers', exact: true });
  await genai.getByLabel('Choose a lesson').selectOption('1');
  await expect(genai.getByRole('button', { name: 'Check answer' })).toBeDisabled();
  await genai.getByRole('radio', { name: '800 tokens', exact: true }).check();
  await genai.getByRole('button', { name: 'Check answer' }).click();
  await expect(genai.getByRole('status')).toContainText('Not quite.');
  await genai.getByRole('radio', { name: '300 tokens', exact: true }).check();
  await expect(genai.getByRole('status')).toHaveCount(0);
  await genai.getByRole('button', { name: 'Check answer' }).click();
  await expect(genai.getByRole('status')).toContainText('Correct.');
  await genai.getByRole('button', { name: 'Next lesson' }).click();
  await expect(genai.getByRole('status')).toHaveCount(0);
  const rag = page.getByRole('region', { name: 'RAG from Scratch', exact: true });
  await rag.getByLabel('Choose a lesson').selectOption('2');
  await rag.getByText('Show exercise solution', { exact: true }).click();
  await expect(rag.getByText(/The baseline compares exact vocabulary terms/)).toBeVisible();
  const playground = page.getByRole('region', { name: 'RAG playground', exact: true });
  await playground.getByRole('button', { name: 'Run retrieval', exact: true }).click();
  await expect(playground.getByRole('status')).toContainText('[password-1]');
  await playground.getByText('Inspect the context packet', { exact: true }).click();
  await expect(playground.getByText('"sources":', { exact: false }).last()).toBeVisible();
  await playground.getByRole('button', { name: 'Paraphrase example' }).click();
  await expect(playground.getByRole('status')).toHaveCount(0);
  await playground.getByRole('button', { name: 'Run retrieval', exact: true }).click();
  await expect(playground.getByRole('status')).toContainText('No matching evidence');
  await playground.getByRole('button', { name: 'Shared-term example' }).click();
  await playground.getByLabel('Top-k', { exact: true }).selectOption('2');
  await playground.getByRole('button', { name: 'Run retrieval', exact: true }).click();
  await expect(playground.getByRole('status')).toContainText('[api-1]');
  await expect(playground.getByRole('status')).toContainText('[password-1]');
  expect(await playground.evaluate(el => el.scrollWidth - el.clientWidth)).toBeLessThanOrEqual(1);
  await page.screenshot({ path: `/private/tmp/beginner-rag-${width}.png` });
  await playground.getByLabel('Your question (maximum 500 characters)').fill(' ');
  await expect(playground.getByRole('button', { name: 'Run retrieval', exact: true })).toBeDisabled();
  expect(calls).toBe(0);
});
