import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { gotoSeededApp } from './helpers/app.js';
test.use({ serviceWorkers: 'block' });

for (const width of [390, 768, 1440]) test(`revise, compare and resume across design workspaces at ${width}px`, async ({ page }) => {
  await page.setViewportSize({ width, height: 900 });
  await page.emulateMedia({ colorScheme: 'light' });
  let ai = 0;
  await page.route('**/api/chat', route => { ai++; return route.abort(); });
  await gotoSeededApp(page, { activeTab: 'designLab', homeDemoSeen: true });
  await page.getByRole('button', { name: 'Revise a design', exact: true }).click();
  const workshop = page.getByRole('region', { name: 'Design revision workspace' });
  await workshop.getByLabel('Revision title').fill('Outage exercise');
  await expect(workshop.getByLabel('Requirements and success criteria')).toContainText('100 notifications');
  await workshop.getByRole('button', { name: 'Freeze baseline and introduce provider outage' }).click();
  await expect(workshop.getByRole('img', { name: 'Before: frozen baseline architecture diagram' })).toBeVisible();
  await expect(workshop.getByRole('img', { name: 'After: current revision architecture diagram' })).toBeVisible();
  await expect(workshop.getByText(/60,000 jobs arrive/)).toBeVisible();
  await workshop.getByText('Edit connections and failure controls', { exact: true }).click();
  const connection = workshop.getByRole('group', { name: 'Connection 3', exact: true });
  await connection.getByLabel('Protocol', { exact: true }).fill('HTTPS v2');
  await connection.getByLabel('Data flow', { exact: true }).fill('Delivery command with idempotency key');
  await connection.getByLabel('Maximum attempts including first').fill('3');
  await connection.getByLabel('Timeout (ms) — 0 means unspecified').fill('100');
  await workshop.getByText('Edit components and assumptions', { exact: true }).click();
  await workshop.getByRole('group', { name: 'Queue', exact: true }).getByLabel('Capacity / second / replica').fill('50');
  await expect(workshop.getByRole('region', { name: 'Failure path review' })).toContainText('bottleneck');
  await expect(workshop.getByRole('region', { name: 'Failure path review' })).toContainText('3 attempts');
  await expect(workshop.getByRole('region', { name: 'Failure path review' })).toContainText('timeout');
  await workshop.getByLabel('Decisions and trade-offs').fill('Keep durable buffering; bound retry load.');
  await workshop.getByLabel('Explain each change and what stayed').fill('Preserve acceptance semantics; revise provider calls.');
  await workshop.getByLabel('Unresolved risks and evidence that would change your mind').fill('Verify deduplication retention with the provider.');
  await workshop.getByRole('button', { name: 'Save revision', exact: true }).click();
  await expect(workshop.getByRole('status')).toContainText('saved in this browser');
  const pending = page.waitForEvent('download');
  await workshop.getByRole('button', { name: 'Download revision JSON' }).click();
  const file = await pending;
  const saved = JSON.parse(await readFile(await file.path(), 'utf8'));
  expect(saved.baseline.nodes[3].available).toBe(true);
  expect(saved.graph.nodes[3].available).toBe(false);
  expect(saved.baseline.edges[2].protocol).toBe('HTTPS');
  expect(saved.graph.edges[2].protocol).toBe('HTTPS v2');
  expect(saved.risks).toContain('deduplication');
  await page.getByRole('button', { name: 'Continue in System Canvas' }).click();
  await page.getByText('Editable architecture and revisions', { exact: true }).click();
  await expect(workshop.getByLabel('Revision title')).toHaveValue('Outage exercise');
  await expect(workshop.getByLabel('Decisions and trade-offs')).toHaveValue('Keep durable buffering; bound retry load.');
  await page.reload();
  await page.getByText('Editable architecture and revisions', { exact: true }).click();
  await expect(workshop.getByLabel('Revision title')).toHaveValue('Outage exercise');
  await page.getByRole('button', { name: 'Continue in Design Lab' }).click();
  await expect(workshop.getByLabel('Revision title')).toHaveValue('Outage exercise');
  expect(await workshop.evaluate(el => el.scrollWidth - el.clientWidth)).toBeLessThanOrEqual(1);
  await workshop.getByRole('img', { name: 'After: current revision architecture diagram' }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: `/private/tmp/design-revision-${width}-${test.info().project.name}.png` });
  expect(ai).toBe(0);
});

test('removing a component removes its connections; backup restores the whole revision', async ({ page }) => {
  await gotoSeededApp(page, { activeTab: 'designLab', homeDemoSeen: true });
  await page.getByRole('button', { name: 'Revise a design', exact: true }).click();
  const workshop = page.getByRole('region', { name: 'Design revision workspace' });
  await workshop.getByLabel('Revision title').fill('Preserved');
  await workshop.getByRole('button', { name: 'Save revision', exact: true }).click();
  await workshop.getByText('Edit components and assumptions', { exact: true }).click();
  await workshop.getByRole('button', { name: 'Remove Worker', exact: true }).click();
  await workshop.getByText('Edit connections and failure controls', { exact: true }).click();
  await expect(workshop.getByLabel('Protocol', { exact: true })).toHaveCount(1);
  await workshop.getByRole('button', { name: 'Restore saved revision' }).click();
  await expect(workshop.getByLabel('Protocol', { exact: true })).toHaveCount(3);
  await page.evaluate(() => { Storage.prototype.setItem = () => { throw new Error('Unavailable'); }; });
  await workshop.getByRole('button', { name: 'Save revision', exact: true }).click();
  await expect(workshop.getByRole('status')).toContainText('storage is unavailable');
});
