/** Original teaching examples. They describe bounded scenarios, not universal rules. */
export const ADVICE_FAILS_REVIEWED_AT = "2026-09-18";

export const ADVICE_FAILS_ARTICLES = [
  {
    slug: "transactional-didnt-start-a-transaction",
    number: "01",
    topic: "Spring transactions",
    title: "Why @Transactional didn't start a transaction",
    description: "The annotation was present, an exception escaped, and the debit still committed. The missing piece was the proxy boundary.",
    failure: "A controller calls transferService.submit(). submit() calls this.transfer(), which debits an account and then throws. With no outer transaction, the JDBC connection auto-commits the debit. The annotation on transfer() is metadata; in Spring's default proxy mode, that local call does not pass through transaction advice.",
    reproduction: "Run this with transaction management enabled but no transaction on submit(). Assert that the debit remains after the exception. Then inspect TransactionSynchronizationManager.isActualTransactionActive() inside transfer(): it is false for this call path.",
    brokenCode: "public void submit(Transfer request) {\n  this.transfer(request);\n}\n\n@Transactional\npublic void transfer(Transfer request) {\n  jdbc.update(\"update account set balance = balance - ? where id = ?\", request.amount(), request.from());\n  throw new IllegalStateException(\"failure after debit\");\n}",
    correction: "Put the transactional operation on a Spring-managed collaborator and call that collaborator through injection. Keep the database work and the failure inside the advised method; let the exception escape unless an explicit rollback rule says otherwise.",
    fixedCode: "@Service\nfinal class TransferFacade {\n  private final TransactionalTransfer transfer;\n  TransferFacade(TransactionalTransfer transfer) { this.transfer = transfer; }\n  void submit(Transfer request) { transfer.execute(request); }\n}\n\n@Service\nfinal class TransactionalTransfer {\n  @Transactional\n  void execute(Transfer request) {\n    jdbc.update(\"update account set balance = balance - ? where id = ?\", request.amount(), request.from());\n    throw new IllegalStateException(\"failure after debit\");\n  }\n}",
    conditions: "This correction applies to Spring proxy transactions, a Spring-managed collaborator, a configured transaction manager, and an exception that reaches the interceptor. An existing outer transaction changes the symptom. AspectJ weaving has different self-invocation behavior. A database transaction does not undo an already accepted remote payment.",
    verification: "Write an integration test that invokes the real facade, injects the failure after the debit, and asserts both account balances are unchanged. Also test the intended checked-exception rule explicitly; Spring's default rollback rule differs from its runtime-exception rule.",
    rollback: "Ship the boundary change behind ordinary application rollout controls. If it misbehaves, revert the caller to the last known transactional boundary; do not compensate balances blindly—reconcile committed rows first.",
    references: [{ label: "Spring: Using @Transactional", url: "https://docs.spring.io/spring-framework/reference/data-access/transaction/declarative/annotations.html" }],
  },
  {
    slug: "adding-threads-made-service-slower",
    number: "02",
    topic: "Java concurrency",
    title: "Why adding threads made the service slower",
    description: "More workers increased queueing, context switching, and downstream contention; they did not create more database capacity.",
    failure: "A service replaces a bounded executor of 16 threads with 200 threads to reduce request latency. Every task blocks on a connection pool of 16 connections. The extra threads wait, contend for CPU, extend the runnable queue, and make tail latency worse while the database remains the bottleneck.",
    reproduction: "Create 200 tasks that each acquire one of 16 semaphore permits, sleep for 50 ms, and release it. Compare a 16-worker executor to a 200-worker executor. Track completion time, active threads, queue depth, and time waiting for a permit; the second pool cannot make more than 16 protected operations run at once.",
    brokenCode: "ExecutorService workers = Executors.newFixedThreadPool(200);\nfor (Request request : requests) {\n  workers.submit(() -> {\n    connectionPool.acquire();\n    try { queryDatabase(request); }\n    finally { connectionPool.release(); }\n  });\n}",
    correction: "Size concurrency from the constrained downstream resource and apply backpressure before work enters an unbounded queue. Use a bounded executor or semaphore, an explicit timeout, and a rejection policy that the caller can handle. Increase database capacity only after measurements show it is safe and useful.",
    fixedCode: "ThreadPoolExecutor workers = new ThreadPoolExecutor(\n    16, 16, 0, TimeUnit.MILLISECONDS,\n    new ArrayBlockingQueue<>(64),\n    new ThreadPoolExecutor.CallerRunsPolicy());\n\nworkers.submit(() -> queryDatabaseWithinDeadline(request));",
    conditions: "This applies when the bottleneck is a bounded downstream resource or CPU saturation. It is not a universal thread-count formula: virtual threads can reduce the cost of parked threads, but they do not increase connection-pool, database, rate-limit, or CPU capacity. A caller-runs policy is appropriate only when applying backpressure to that caller is safe.",
    verification: "Load test with production-like query latency and pool settings. Compare p50/p95/p99 latency, accepted and rejected work, executor queue depth, database active connections, CPU, and error rate. Exercise overload and recovery—not only the happy-path throughput test.",
    rollback: "Keep the previous executor settings deployable. If rejection causes unacceptable user behavior, lower admission first or restore the proven limit while investigating; do not raise the queue without a memory and deadline budget.",
    references: [{ label: "Java ThreadPoolExecutor API", url: "https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/concurrent/ThreadPoolExecutor.html" }],
  },
  {
    slug: "cache-caused-stale-reads",
    number: "03",
    topic: "Caching",
    title: "Why a cache caused stale reads",
    description: "The cache was fast and correct for its key, but its invalidation contract did not match the reader's freshness promise.",
    failure: "A profile update writes the database and deletes the cache key. A second reader races between those two actions, repopulates the old value, and leaves it cached after the delete has already happened. Users continue to see the old display name until the TTL expires.",
    reproduction: "Use an in-memory Map and three controlled steps: reader A misses and pauses before cache.set(oldValue); the writer updates the database and deletes the key; reader A resumes and writes oldValue. A following read returns stale data even though the write succeeded.",
    brokenCode: "Profile read(String id) {\n  return cache.get(id).orElseGet(() -> {\n    Profile profile = repository.find(id);\n    cache.put(id, profile);\n    return profile;\n  });\n}\n\nvoid update(Profile profile) {\n  repository.save(profile);\n  cache.remove(profile.id());\n}",
    correction: "Choose and document a freshness contract. For read-your-writes, write the new version to the cache after a successful database commit (or bypass cache for the writer) and reject cache values older than the required version. For eventual consistency, use a bounded TTL, versioned invalidation, and surface the permitted staleness in the API contract.",
    fixedCode: "@Transactional\nvoid update(Profile profile) {\n  Profile saved = repository.save(profile);\n  afterCommit(() -> cache.put(saved.id(), new CacheValue(saved.version(), saved)));\n}\n\nProfile read(String id, long minimumVersion) {\n  CacheValue cached = cache.get(id);\n  if (cached != null && cached.version() >= minimumVersion) return cached.profile();\n  return repository.find(id);\n}",
    conditions: "The right fix depends on the promise. Writing through is not enough when multiple writers, replicas, local caches, or out-of-order events exist. Version checks require a monotonic version for the entity. A TTL limits stale duration but never guarantees read-your-writes.",
    verification: "Turn the three-step race into a deterministic test using latches. Add tests for update failures, cache write failures, concurrent writers, expiry, and a reader requesting a newer version. Instrument cache hit rate and stale-version rejections separately.",
    rollback: "Make the read path capable of bypassing the cache. On a freshness incident, disable the affected cache namespace, invalidate it, and monitor database headroom before restoring cached reads.",
    references: [{ label: "Redis: cache consistency patterns", url: "https://redis.io/docs/latest/develop/clients/patterns/" }],
  },
  {
    slug: "successful-retry-created-a-duplicate",
    number: "04",
    topic: "API reliability",
    title: "Why a successful retry created a duplicate",
    description: "A timeout told the client the response was unknown—not that the original write had failed.",
    failure: "The payment service commits an order, then the response is lost. The client retries POST /orders. The service treats the second request as a new command and commits a second order. Both executions can be successful from their own point of view.",
    reproduction: "In a test double, persist the first order and then throw a timeout before returning the response. Send the exact command again. Without a durable idempotency record, the order table contains two rows. A client retry count is not an idempotency mechanism.",
    brokenCode: "@PostMapping(\"/orders\")\nOrder create(@RequestBody CreateOrder request) {\n  return orders.save(Order.from(request));\n}",
    correction: "Require a client-generated idempotency key for a command and persist it with a request fingerprint and the completed response in the same transactional boundary as the effect. On a matching replay, return the recorded response. Reject a key reused with a different command payload.",
    fixedCode: "@Transactional\nOrderResponse create(String idempotencyKey, CreateOrder request) {\n  String fingerprint = fingerprint(request);\n  IdempotencyRecord prior = records.findForKey(idempotencyKey);\n  if (prior != null) return prior.matches(fingerprint)\n      ? prior.response() : throw new ConflictException();\n\n  Order order = orders.save(Order.from(request));\n  OrderResponse response = OrderResponse.from(order);\n  records.save(IdempotencyRecord.completed(idempotencyKey, fingerprint, response));\n  return response;\n}",
    conditions: "This works only if the key is scoped to the command owner, stored durably for the retry window, and protected by a uniqueness constraint. Concurrent first attempts need serialization or a pending-record protocol. External side effects still need their own idempotency key or an outbox/compensation design.",
    verification: "Test a lost response after commit, a replay after process restart, concurrent calls with one key, a payload mismatch, and record expiry. Verify the database uniqueness constraint, not just application-level lookup. Count duplicate-key replays and conflicts.",
    rollback: "Deploy support for idempotency keys before requiring them. If the new path fails, preserve recorded outcomes and fall back only for clients that have not opted in; replaying unknown commands is unsafe.",
    references: [{ label: "AWS: retry with backoff pattern", url: "https://docs.aws.amazon.com/prescriptive-guidance/latest/cloud-design-patterns/retry-backoff.html" }],
  },
  {
    slug: "index-wasnt-used",
    number: "05",
    topic: "PostgreSQL performance",
    title: "Why an index wasn't used",
    description: "The index existed, but the query predicate selected most rows. A sequential scan was the cheaper plan.",
    failure: "A team creates an index on orders(status) and expects a dashboard query for status = 'COMPLETED' to use it. Ninety-five percent of rows are completed. Index traversal plus random heap reads cost more than reading the table sequentially, so the planner chooses a sequential scan.",
    reproduction: "Load a test table with roughly 95% COMPLETED rows, run ANALYZE, and compare EXPLAIN (ANALYZE, BUFFERS) for COMPLETED versus a rare status. Keep statistics current and use representative row counts; a tiny local table proves little about the production plan.",
    brokenCode: "CREATE INDEX orders_status_idx ON orders (status);\n\nSELECT id, total_cents\nFROM orders\nWHERE status = 'COMPLETED';",
    correction: "Design for the actual selective predicate and access path. If the dashboard filters by tenant and recent time, measure a composite index such as (tenant_id, created_at DESC) with the appropriate status predicate, or a partial index when its predicate is stable and demonstrably selective. Re-run ANALYZE and verify the whole workload.",
    fixedCode: "CREATE INDEX CONCURRENTLY orders_tenant_recent_completed_idx\n  ON orders (tenant_id, created_at DESC)\n  WHERE status = 'COMPLETED';\n\nSELECT id, total_cents\nFROM orders\nWHERE tenant_id = $1\n  AND status = 'COMPLETED'\n  AND created_at >= $2\nORDER BY created_at DESC\nLIMIT 50;",
    conditions: "An index scan is not a goal by itself. The proposed partial index applies only to queries whose predicate implies its WHERE clause and to a workload where its write, storage, and maintenance cost fits. Parameterization and plan caching can change planning behavior; verify the production-like query form and data distribution.",
    verification: "Capture EXPLAIN (ANALYZE, BUFFERS) in a safe environment with representative statistics. Compare rows estimated versus actual, read latency, write latency, WAL, index size, and the plans for both common and rare statuses. Never use ANALYZE on a mutating statement in production merely to inspect it.",
    rollback: "Create indexes with an operationally appropriate migration plan. If write cost or plan quality regresses, remove only the new index after validating no constraint or other query depends on it, then restore the prior measured plan.",
    references: [{ label: "PostgreSQL: Examining index usage", url: "https://www.postgresql.org/docs/current/indexes-examine.html" }],
  },
];

export function adviceFailsArticle(slug) {
  return ADVICE_FAILS_ARTICLES.find((article) => article.slug === String(slug || "").toLowerCase()) || null;
}
