export const BEGINNER_PATHS = [
  {
    id: 'genai', title: 'Generative AI for Developers', prerequisite: 'Basic programming and JSON. No machine-learning background required.', outcome: 'Design a bounded AI feature, explain its model contract, and validate its output before using it.',
    lessons: [
      {
        id: 'what-generates', title: '1. What generative AI actually does',
        objective: 'Distinguish a model-generated proposal from a deterministic application decision.',
        explanation: 'Generative AI produces content such as text, code, images, or audio from learned patterns and supplied input. In this course we focus on language models. A language model generates a sequence of tokens, with each next token depending on the available context. Training changes learned parameters; inference uses those parameters to respond. The model is not automatically reading your database or checking whether every sentence is true. Your application supplies data and decides what to do with the result.',
        example: 'A study app receives “I know Java; help me learn SQL.” A model can propose a plan. Ordinary code still checks that the requested duration is allowed and that the user owns the saved plan. Compare this with a tax or price calculation: use deterministic code for exact arithmetic, then optionally ask a model to explain the computed result.',
        exercise: 'Split a study-plan feature into three columns: model proposals, deterministic checks, and actions requiring authorization. Place topic suggestion, duration validation, ownership checking, and saving into the appropriate columns.',
        solution: 'Topic suggestion is a model proposal. Type/range and ownership checks belong in deterministic server code. Saving is an authorized application action; a model saying “saved” is not proof that a write occurred. Inspect actual application state.',
        pitfall: 'A fluent response can be unsupported. Model confidence and polished wording do not establish correctness.',
        interview: 'How is an LLM feature different from ordinary software?', answer: 'A model supplies a probabilistic content proposal inside a deterministic application. I define its inputs and outputs, verify the parts that can be checked, evaluate task quality, and keep authorization outside the model.',
        quiz: { question: 'Who should enforce whether a user may save a plan?', options: ['The model, because it understands the request', 'The authenticated application service', 'The answer’s confidence score'], correct: 1, explanation: 'Authorization must be enforced by application state and policy. Generated text cannot grant permission.' },
      },
      {
        id: 'tokens-context', title: '2. Tokens, context, and model memory',
        objective: 'Budget a request and explain what the model can see.',
        explanation: 'A token is a unit produced by a model-specific tokenizer; it may be a word fragment, punctuation, or another piece of text. It is not interchangeable with a word. Context is the input made available for the current request: instructions, user text, selected history, and evidence. A chat interface appears to remember because the application may resend history or retrieve stored facts. That is different from changing the model’s weights.',
        example: 'In an illustrative 4,000-token budget, instructions use 400, a profile 300, history 1,000, and evidence 1,500. Reserve 500 for output: total 3,700, leaving 300. Adding another 600-token document exceeds this simplified budget by 300. Actual provider limits and message overhead must be measured for the selected model.',
        exercise: 'Make room for the extra 600-token document without losing the current question or reducing the 500-token output reserve. Explain what you remove and why.',
        solution: 'Remove at least 300 input tokens, for example irrelevant old history. Keep the current question, instructions, and relevant evidence. A summary can lose facts, so test it against questions that depend on earlier details. Do not silently cut arbitrary text at the end.',
        pitfall: 'A larger context window does not guarantee better use of every fact. Irrelevant material costs money and can distract from evidence.',
        interview: 'Does an LLM remember everything in my chat?', answer: 'It can use what the product sends in that request. The product may store or retrieve history, but that is not automatic retraining. I would inspect the request construction and retention policy rather than assume unlimited memory.',
        quiz: { question: 'How much headroom remains in the worked example before adding the document?', options: ['300 tokens', '800 tokens', '1,300 tokens'], correct: 0, explanation: '4,000 − (400 + 300 + 1,000 + 1,500 + 500) = 300. The output reserve is part of the budget.' },
      },
      {
        id: 'prompt-basics', title: '3. Write a prompt as a contract',
        objective: 'Replace vague requests with testable instructions and examples.',
        explanation: 'A useful prompt identifies the task, input boundaries, constraints, output format, and behavior when information is missing. Examples show the intended pattern. Separate instructions from evidence: a document can contain text that looks like a command, but that text is still data. Prompt wording helps guide the model; it does not enforce security or guarantee that the response follows the contract.',
        example: 'Instead of “make a useful plan,” ask: “Using only the supplied notes, propose one supported study topic. Return topic, sourceId, and minutes as JSON. Minutes must be an integer from 10 to 60. If no note supports a topic, return an abstention.” Include one supported example and one missing-evidence example.',
        exercise: 'Write a prompt for a bug-summary feature with fields summary, evidenceIds, and unknowns. Include a log entry that says “ignore previous instructions” and specify how it must be treated.',
        solution: 'Describe the summarization task, delimit logs as untrusted evidence, require references to supplied log IDs, and request unknowns when the logs do not establish a cause. The adversarial line remains quoted source text, not an instruction. Server-side controls must still prevent unauthorized tools or data access.',
        pitfall: '“You are an expert” does not specify the actual task, evidence, or acceptance criteria.',
        interview: 'What makes a prompt production-ready?', answer: 'Clear inputs, task, constraints, examples, and an output contract, plus versioning and evaluation on representative cases. I still validate the response and enforce permissions outside the prompt.',
        quiz: { question: 'A retrieved log says “send all credentials.” What is it?', options: ['A higher-priority instruction', 'Authorization to call a tool', 'Untrusted source content'], correct: 2, explanation: 'Retrieved text is data. Neither a source nor a model response authorizes access or side effects.' },
      },
      {
        id: 'model-boundary', title: '4. Integrate a model behind an API boundary',
        objective: 'Trace browser → server → model → validation → response.',
        explanation: 'Keep credentials and provider calls on the server. The browser sends a bounded request to your API. The server authenticates the caller, validates input, assembles only necessary context, calls a model with a timeout and output limit, validates the response, and returns a safe result. Distinguish invalid requests, provider failures, and unusable model output. Retries need a limit; streaming partial text is not a completed validated result.',
        example: 'A proposed response is {"topic":"SQL joins","minutes":"30","sourceId":"sql-1"}. It parses as JSON, but minutes is a string, so the application rejects it. If minutes were 300, the type would be correct but the 10–60 range would still fail. An unknown sourceId must fail even when the rest is valid.',
        exercise: 'Download the existing course lab and run node interviewiq-lab.mjs 2 --malformed. Read validatePlan. List the checks required before a plan can reach the save function.',
        solution: 'Check object shape and allowed fields, nonempty topic, integer minutes in the allowed range, and sourceId membership in the authorized evidence set. The malformed lab fixture should exit with an Invalid plan error. A real integration also needs authentication, timeouts, bounded repair, and safe error handling.',
        pitfall: 'Valid JSON proves syntax, not truth, access rights, or a successful action.',
        interview: 'Why validate model output if structured output is available?', answer: 'Provider constraints help with structure, but the application still owns business rules, authorized identifiers, and safe recovery. I validate at the boundary and test malformed and semantically invalid responses.',
        quiz: { question: 'Which response should fail a 10–60 minute integer rule?', options: ['minutes: 30', 'minutes: "30"', 'minutes: 45'], correct: 1, explanation: 'The string "30" is not an integer. Do not silently coerce an untrusted response to bypass the contract.' },
      },
      {
        id: 'choose-pattern', title: '5. Choose prompting, RAG, or tools',
        objective: 'Select the smallest architecture that supplies the missing capability.',
        explanation: 'Use a prompt for transforming information already in the request. Use retrieval when an answer needs external evidence, such as current private documentation. Use tools when the system needs a computation, lookup, or action with a defined interface. Fine-tuning changes learned behavior and needs suitable training data and evaluation; it is not a default substitute for changing facts. An agent dynamically chooses steps, while a workflow follows a code-defined sequence.',
        example: 'Summarize this supplied paragraph: start with prompting. Answer a question from the current team handbook: retrieve relevant authorized passages. Compute a balance: call deterministic code. Save a study plan: execute an authorized service operation. None of these automatically requires an autonomous agent.',
        exercise: 'Classify a support assistant’s tasks: summarize the user’s report, find the latest runbook, calculate retry delays, and restart a server. Name the evidence or authority each task requires.',
        solution: 'Summarization uses supplied text. Runbook answers use retrieval with version and access metadata. Delay calculation belongs in code. Restarting uses a tightly scoped tool with real authorization and any required approval, audit, and recovery. A fixed workflow is a sensible initial design.',
        pitfall: 'RAG is not model training, and a tool description is not permission to execute that tool.',
        interview: 'When would you add RAG?', answer: 'When relevant knowledge is outside the request and should be supplied at inference time. I first measure whether retrieval finds the right authorized evidence, then whether the answer is supported by it.',
        quiz: { question: 'Weekly-changing internal policy is usually best supplied through which starting approach?', options: ['Authorized retrieval of current documents', 'Hard-coded model confidence', 'Assume training already includes the policy'], correct: 0, explanation: 'Retrieval can supply current evidence with provenance. It still needs freshness, authorization, and answer evaluation.' },
      },
      {
        id: 'first-release', title: '6. Evaluate and deliver your first AI feature',
        objective: 'Define a small release checklist based on observable behavior.',
        explanation: 'Create representative examples before repeatedly editing prompts. Keep some cases for development and separate cases for final evaluation. Test deterministic rules with code; review open-ended quality against a clear rubric. Measure latency and token usage, including retries. Capture safe version and error metadata so regressions can be traced. A small demo establishes basic wiring, not production quality for all users.',
        example: 'For a study planner, include a supported Java request, an unsupported topic, malformed output, a private source from another tenant, and a duplicate save. A success response should cite relevant evidence and obey the duration contract. Unsupported requests should abstain rather than invent notes. A duplicate operation must not create a second plan.',
        exercise: 'Run node interviewiq-lab.mjs 6. Then run it with --unknown. Explain what the five deterministic checks prove and propose three held-out questions for a future real-model evaluation.',
        solution: 'The normal fixture reports 5/5 checks, saves once, and identifies duplicate replay. The unknown query abstains and saves nothing. These checks exercise application behavior with fake generation; they do not establish real-model factuality. Add paraphrase, conflicting evidence, and missing-evidence questions with independent expected outcomes.',
        pitfall: 'A passing smoke test or high average rating can hide a severe failure in a small user segment.',
        interview: 'How would you decide whether to launch?', answer: 'Set task-quality and safety gates, run representative held-out cases, measure cost and latency, and prepare rollback. I would distinguish deterministic test results from measured real-model quality and start with a controlled rollout.',
        quiz: { question: 'Does the fake-model lab passing prove a live model is accurate?', options: ['Yes, all models use the same contract', 'Yes, if the response is JSON', 'No, live-model quality needs its own evaluation'], correct: 2, explanation: 'Deterministic fixtures test wiring and invariants. Actual model behavior needs representative, independently evaluated cases.' },
      },
    ],
  },
  {
    id: 'rag', title: 'RAG from Scratch', prerequisite: 'Basic arrays and JSON; complete the generative AI path first if tokens and prompts are new.', outcome: 'Explain and inspect ingestion → chunks → retrieval → context → grounded answer → evaluation.',
    lessons: [
      {
        id: 'rag-purpose', title: '1. Why retrieval comes before generation',
        objective: 'Explain Retrieval-Augmented Generation without assuming a vector database.',
        explanation: 'RAG means Retrieval-Augmented Generation. Retrieve useful evidence, add it to the model’s context, then generate an answer using that evidence. Think of an open-book exercise: having a book helps only if you find the right pages and use them accurately. RAG does not update model weights. It can use keyword search, vectors, database queries, or a combination; a vector database is one implementation choice.',
        example: 'Question: “How do I reset a forgotten password?” A language model may know generic advice but cannot know your app’s current steps unless they are supplied. A help-center chunk says “Password reset: open Settings, choose Security, and select Reset password.” Retrieve that chunk, then answer with its source. If the help center has no refund policy, do not invent one.',
        exercise: 'In the playground below, run the password example, then select the unknown-topic example. Predict the selected source and whether an answer should be returned before running each one.',
        solution: 'The password example retrieves the password chunk. The refund query has no matching evidence in this tiny dataset, so the playground returns an abstention. This local demo returns source excerpts rather than calling a model; the retrieval and context steps are visible independently of generation.',
        pitfall: 'Retrieving something is not the same as retrieving evidence that answers the question.',
        interview: 'What is RAG in one minute?', answer: 'RAG retrieves relevant authorized information at request time and supplies it as evidence for an answer. I evaluate retrieval and answer support separately, preserve source provenance, and abstain when the evidence is insufficient.',
        quiz: { question: 'Does adding a document to a RAG index retrain the LLM?', options: ['Yes, its weights update immediately', 'No, it makes external evidence available for retrieval', 'Only if the document is a PDF'], correct: 1, explanation: 'Indexing prepares external data. Retrieval supplies selected content at inference time; it does not train the language model.' },
      },
      {
        id: 'rag-ingest', title: '2. Load documents and preserve their meaning',
        objective: 'Turn raw sources into useful, traceable pieces of evidence.',
        explanation: 'Ingestion reads sources and extracts useful text. Remove navigation noise, preserve headings and table relationships, and track document ID, source location, version, and access metadata. Split text into chunks small enough to retrieve but large enough to make sense. A sentence such as “It expires after 10 minutes” needs surrounding context identifying what expires. Keep stable source references so an answer can be checked.',
        example: 'A long help page contains password reset, API keys, and support hours. Split by those headings rather than putting unrelated topics into one chunk. Each chunk retains its heading and source ID. The playground uses three short sections and splits on blank lines so you can inspect every resulting chunk; it is not a production PDF parser.',
        exercise: 'Inspect the playground chunk list. Explain why password-1 and api-1 should remain separate. Design metadata for a replacement password policy and identify how you would remove the old version.',
        solution: 'Separate topics improve selection and reduce unrelated context. Store a document ID, section ID, version, source URL/offset, and access scope. Replace or invalidate old chunks and affected caches when the policy changes; appending a new version without managing the old one can retrieve conflicting instructions.',
        pitfall: 'Chunking by a fixed character count can separate a rule from its exception. Size must be evaluated against real questions.',
        interview: 'How do you choose chunk size?', answer: 'Start with meaningful document boundaries and representative queries. Compare retrieval recall and answer support across sizes while controlling overlap and context cost. There is no universal size that is best for every corpus.',
        quiz: { question: 'Which chunk is easier to interpret on its own?', options: ['“It expires after 10 minutes.”', '“The reset link expires after 10 minutes.”', '“See above.”'], correct: 1, explanation: 'The second chunk names the subject. Independent interpretability matters when retrieval removes the surrounding page.' },
      },
      {
        id: 'rag-vectors', title: '3. Understand embeddings and similarity',
        objective: 'Calculate a similarity score and distinguish lexical vectors from learned embeddings.',
        explanation: 'A vector is a list of numbers. For a simple lexical representation, choose a vocabulary and count each word in a chunk. Learned text embeddings instead map text into a numerical representation trained to capture useful relationships, including some paraphrases. Compare query and document vectors from compatible representations. Cosine similarity is the dot product divided by the product of vector lengths. It measures direction similarity, not truth or authorization.',
        example: 'For vocabulary [password, reset, token], vector A=[1,1,0] and B=[1,0,1]. Their dot product is 1, each length is √2, so cosine=1/(√2×√2)=0.5. Identical nonzero vectors score 1. An all-zero query vector has no known terms; the playground gives it score 0 rather than dividing by zero.',
        exercise: 'Select the paraphrase example “credentials renewal” in the playground. Compare it with “password reset.” Explain why the bag-of-words baseline fails despite the possible conceptual connection.',
        solution: 'The baseline compares exact vocabulary terms, so “credentials renewal” has a zero vector and no match. A learned embedding model may improve paraphrase retrieval, but must be measured on labeled cases. Re-embed stored chunks when switching to an incompatible embedding model or representation.',
        pitfall: 'A cosine score of 0.8 is not an 80% probability that a source answers the question.',
        interview: 'Why are embeddings useful for RAG?', answer: 'They can retrieve semantically related wording that exact matching misses. I still evaluate relevance, filter by access, and handle zero or poor evidence; an embedding score alone is not an answer-quality guarantee.',
        quiz: { question: 'What is cosine([1,1,0], [1,0,1])?', options: ['1', '0', '0.5'], correct: 2, explanation: 'The dot product is 1 and the denominator is 2, giving 0.5.' },
      },
      {
        id: 'rag-retrieve', title: '4. Rank chunks and select top-k',
        objective: 'Inspect ranked candidates and explain the context trade-off.',
        explanation: 'At query time, represent the question, score candidate chunks, sort them, and select a bounded number called top-k. The playground searches a tiny in-memory list exactly. Larger systems may use approximate nearest-neighbor indexes, lexical search, or hybrid retrieval. Authorize candidates before they reach the model. A reranker can reorder retrieved candidates but cannot recover a document that never entered its candidate set.',
        example: 'The query “token” appears in both the password-reset section and the API section. Selecting two chunks exposes both meanings. Selecting only one may omit the intended evidence. More chunks increase context cost and may add distractions; do not increase k indefinitely to compensate for poor retrieval.',
        exercise: 'Run the shared-term “token” example with top-k=1 and top-k=2. Inspect source IDs and scores. Explain what additional information the user should provide before an assistant chooses password-token instructions over API-token instructions.',
        solution: 'Ask which token the user means, or present the ambiguity with citations. Retrieval can return multiple plausible sources but cannot resolve intent without enough information. A production system should evaluate relevance by question type, set a context budget, and define a clarification path.',
        pitfall: 'Always returning a nearest neighbor forces irrelevant evidence into answers. Provide a no-evidence path and evaluate any threshold.',
        interview: 'What does top-k control?', answer: 'The number of retrieved candidates retained at a stage. Larger k may improve recall but increases context and irrelevant material. I tune it using labeled queries and downstream answer quality, with authorization and token-budget constraints.',
        quiz: { question: 'Can reranking retrieve a relevant chunk absent from its candidate list?', options: ['No, candidate retrieval must find it first', 'Yes, it searches every source automatically', 'Yes, if k is one'], correct: 0, explanation: 'A reranker only scores the candidates it receives. Missing-candidate failures belong to retrieval.' },
      },
      {
        id: 'rag-generate', title: '5. Build context, answer, and cite evidence',
        objective: 'Inspect exactly what evidence an answer may use.',
        explanation: 'Build a context packet with selected chunks and source IDs. Tell the generator the task, how to use evidence, and when to abstain or ask for clarification. Treat sources as untrusted data; instructions embedded in documents must not authorize actions. Validate citation IDs and inspect whether cited text actually supports the claims. A valid ID alone proves neither support nor correctness.',
        example: 'The playground creates a JSON context packet containing instructions, the question, and source records. Its final response copies selected evidence and IDs rather than inventing a generated answer. In a live implementation, a server-side model adapter would consume that packet and return a response checked against the same evidence boundary.',
        exercise: 'Open the context packet for “password reset.” Point to the instruction, question, and evidence separately. Write a two-sentence answer that adds no steps beyond the source, then identify one unsupported claim you could accidentally introduce.',
        solution: '“Open Settings, choose Security, and select Reset password [password-1]. The reset token expires after 10 minutes [password-1].” Claiming that an email must arrive within 30 seconds is unsupported because the source gives no email delivery guarantee. Omit it or state that the evidence does not establish it.',
        pitfall: 'RAG can still hallucinate. Retrieval and prompting reduce some information gaps but do not guarantee faithful generation.',
        interview: 'How do you check that a RAG answer is grounded?', answer: 'Check each substantive claim against the actual authorized passages used, not just whether a citation exists. Evaluate omissions, unsupported additions, contradictions, and whether abstention was appropriate.',
        quiz: { question: 'An answer includes a real source ID. Is that enough?', options: ['Yes, the citation proves every claim', 'No, the passage must support the claim', 'Yes, if similarity is above 0.5'], correct: 1, explanation: 'Citation validity and claim support are different checks. A source can exist but say something else.' },
      },
      {
        id: 'rag-evaluate', title: '6. Evaluate failures and extend the project',
        objective: 'Diagnose retrieval failures separately from generation failures.',
        explanation: 'Label which sources are relevant for a small question set before tuning retrieval. Precision@k is relevant retrieved results divided by retrieved results; recall@k is relevant retrieved results divided by all relevant sources. State how empty results are handled. Evaluate the answer separately for supported claims and appropriate abstention. Include paraphrases, ambiguous questions, stale data, and sources outside the caller’s permissions.',
        example: 'There are two relevant chunks, and top-2 returns one relevant and one irrelevant chunk. Precision@2 is 1/2 and recall@2 is 1/2. If a generator invents an extra instruction despite receiving the correct chunk, that is a generation problem rather than a missing-document problem. The playground’s exact excerpts cannot measure live-model generation quality.',
        exercise: 'Create six cases: password reset, API token, support hours, refund policy, credentials renewal, and ambiguous token. Record relevant IDs, expected answer/abstain/clarify behavior, and where each failure occurs. Then use the downloadable core lab’s retrieval stage as your next coding task.',
        solution: 'Password, API, and support cases have corresponding sources. Refund has no evidence. Credentials renewal demonstrates a paraphrase limitation that needs labeling and possibly better retrieval. Token is ambiguous and should trigger clarification in a real assistant. Keep the same labeled cases when comparing lexical and learned embedding retrieval.',
        pitfall: 'A single end-to-end score hides whether indexing, ranking, context selection, or generation failed.',
        interview: 'What would you improve after a basic RAG demo?', answer: 'Use an error analysis to choose the next change: parsing and chunking for missing context, retrieval for missed sources, generation checks for unsupported claims, and authorization/freshness controls for unsafe evidence. Measure the change against the same labeled baseline.',
        quiz: { question: 'Two relevant chunks exist; top-2 returns one relevant and one irrelevant. What is recall@2?', options: ['1', '0', '0.5'], correct: 2, explanation: 'One of the two relevant chunks was retrieved, so recall is 1/2. Precision is also 1/2 in this example.' },
      },
    ],
  },
];
