export const BACKGROUND_JOBS_BLOG = {
  id: "java-background-jobs",
  title: "Java Background Jobs: Schedules, Leases, Retries, and Safe Shutdown",
  category: "Java operations",
  javaRelease: 17,
  summary: "A practical Java 17 course for making scheduled and asynchronous work correct across replicas, restarts, overload, and partial failure.",
  lessons: [
    "Treat a background job as a durable business operation, not as a timer callback.",
    "Make ownership, retry eligibility, capacity, and shutdown behavior explicit before adding concurrency.",
    "Measure lateness, outcomes, and backlog so an operator can distinguish delay from loss.",
  ],
  sections: [
    { heading: "Course goal", body: "Design jobs that remain correct when two replicas wake at once, a worker crashes after a side effect, a dependency slows down, or a deployment begins draining." },
    { heading: "Java production lens", body: "The standalone examples target Java 17 and model decision boundaries only. Production implementations need durable storage, transaction handling, secure job inputs, and metrics at their actual queue or scheduler boundary." },
  ],
  example: "durable job record → lease one owner → bounded execution → durable outcome → next schedule",
  interviewQuestions: [
    "Why is a process-local scheduler not sufficient for a job that must run once across replicas?",
    "What prevents a retry from duplicating an external side effect after a worker crash?",
    "Which signals prove that a job system is delayed, overloaded, or losing work?",
  ],
  practice: "Design a daily invoice job with a durable schedule, lease, idempotency key, retry classification, concurrency limit, drain rule, and an operator dashboard.",
  capstone: {
    title: "Capstone: Run a multi-replica invoice close safely",
    scenario: "Three service replicas poll due invoice-close jobs. One worker pauses during a provider call, a deployment starts draining, and the provider returns a timeout after possibly accepting a charge.",
    steps: [
      "Define the durable job identity, schedule semantics, lease expiry, fencing/version rule, and the state transitions an operator can inspect.",
      "Persist the intended invoice effect and its provider idempotency key before dispatch; classify retryable outcomes and reconcile an ambiguous provider timeout.",
      "Set bounded admission, graceful drain, overdue-job alerts, and a replay procedure that proves each invoice is either complete, safely pending, or explicitly failed.",
    ],
    outcome: "Produce a job design that converges safely after duplicate polling, restart, overload, and deployment interruption without silently dropping financial work.",
  },
};

export const BACKGROUND_JOBS_CHAPTERS = [
  { title: "1. Model the job and its completion contract", lesson: "A schedule only requests work; the durable job record defines the business operation, its unique identity, input version, due time, owner state, and terminal outcome. Decide whether skipped intervals coalesce, each occurrence must run, or a late run is invalid. A worker must write an observable outcome, not merely log that a timer fired.", whenToUse: "Use a durable job model when work must survive restarts or be audited.", avoid: "Avoid treating in-memory timer callbacks as proof that a business operation ran exactly once.", diagram: "schedule occurrence → durable job identity → claimed work → durable outcome", example: "import java.time.*;\nfinal class JobIdentityExample {\n  record Job(String key, Instant dueAt, int inputVersion) {\n    Job {\n      if (key == null || key.isBlank() || dueAt == null || inputVersion < 1)\n        throw new IllegalArgumentException(\"job identity\");\n    }\n  }\n  static String id(Job job) {\n    return job.key() + \"@\" + job.dueAt() + \"/v\" + job.inputVersion();\n  }\n}", exercise: "For a nightly statement job, choose whether a missed run is replayed individually or coalesced, then write the resulting identity and user-visible completion rule.", quiz: "What information must a durable job identity contain so a restart can distinguish a retry from a new occurrence?", answer: "The identity must tie one intended business occurrence to its due time and input/version semantics. A random execution ID alone cannot tell whether a later worker is continuing the same occurrence or creating another one." },
  { title: "2. Claim work with leases and fencing", lesson: "Multiple replicas can discover the same due job. Claim it with a durable, time-bounded lease and attach a monotonically increasing fencing token to every protected write. Lease expiry permits recovery, but an old worker may resume after its lease; the token lets the authoritative store reject that stale worker instead of accepting two owners.", whenToUse: "Use a lease plus fencing when more than one process can execute the same durable job.", avoid: "Avoid relying on a boolean running flag or a lease alone when a paused old worker can resume.", diagram: "due job → worker A claims token 7 → lease expires → worker B token 8 → stale token 7 rejected", example: "final class FencingExample {\n  record Claim(long token, long expiresAtMillis) { }\n  static boolean mayWrite(long currentToken, Claim claim, long nowMillis) {\n    return claim.token() == currentToken && nowMillis <= claim.expiresAtMillis();\n  }\n  static long nextToken(long currentToken) {\n    return Math.addExact(currentToken, 1);\n  }\n}", exercise: "Trace a worker paused beyond its lease while a second worker completes the same job. Identify every write that must check the fencing token.", quiz: "Why does lease expiry alone not prevent a resumed worker from corrupting a newer result?", answer: "A lease tells a new worker when recovery is allowed, not whether the old process has stopped. A fencing token makes the authoritative write reject an old claimant even if that process resumes and still believes it owns the job." },
  { title: "3. Make side effects idempotent and reconcile ambiguity", lesson: "Store the job's intended side effect and stable provider idempotency key before calling an external system. A timeout after dispatch is UNKNOWN, not failed: look up the same key and reconcile before retrying or compensating. For local effects, commit the result and deduplication marker in one transaction.", whenToUse: "Use stable idempotency keys for jobs that call payment, email, provisioning, or other side-effecting systems.", avoid: "Avoid issuing a new key after a lost response or marking a timeout as a definitive failure.", diagram: "durable intent + key → provider call → lost response → lookup same key → confirm or reconcile", example: "import java.util.*;\nfinal class JobRetryKeyExample {\n  record Intent(String jobId, String providerKey) {\n    Intent { if (jobId == null || jobId.isBlank() || providerKey == null || providerKey.isBlank()) throw new IllegalArgumentException(); }\n  }\n  static String retryKey(Intent intent) { return intent.providerKey(); }\n  static Optional<String> reconcile(Map<String, String> providerResults, Intent intent) {\n    return Optional.ofNullable(providerResults.get(intent.providerKey()));\n  }\n}", exercise: "Define the provider key, retention period, and reconciliation action for a job that sends tax invoices after a timeout.", quiz: "Why is a timeout after sending an external command an unknown outcome rather than a retry signal?", answer: "The external system may have committed the effect before the response was lost. Retrying with a new identity can create a second effect; query or repeat only with the original durable key under the provider's idempotency guarantee." },
  { title: "4. Bound admission and choose retry ownership", lesson: "Background work competes for database connections, CPU, and downstream quotas. Bound concurrent execution and queue length at the owner boundary; reject or defer excess work with a visible state. Tie each admission to a handle that releases once, including concurrent duplicate cleanup, and close it only when the worker actually stops using the resource. Retry only transient, idempotent operations and keep one retry owner so schedules, workers, clients, and brokers do not multiply attempts.", whenToUse: "Use bounded admission when job bursts could starve request traffic or downstream dependencies.", avoid: "Avoid unbounded executor queues and retry loops at several layers.", diagram: "due jobs → bounded admission → worker slots → dependency\nfull → defer with reason → retry at one owner", example: "import java.util.Optional;\nimport java.util.concurrent.Semaphore;\nimport java.util.concurrent.atomic.AtomicBoolean;\nfinal class JobAdmissionExample {\n  private final Semaphore permits;\n  JobAdmissionExample(int maximumRunning) {\n    if (maximumRunning < 1) throw new IllegalArgumentException();\n    permits = new Semaphore(maximumRunning);\n  }\n  Optional<Permit> tryStart() {\n    return permits.tryAcquire() ? Optional.of(new Permit()) : Optional.empty();\n  }\n  final class Permit implements AutoCloseable {\n    private final AtomicBoolean closed = new AtomicBoolean();\n    private Permit() { }\n    public void close() {\n      if (closed.compareAndSet(false, true)) permits.release();\n    }\n  }\n  // Acquire once; use try (var permit = acquired.orElseThrow()) { ... }.\n  // Close only after the work has stopped using the protected resource.\n  // Cancelling a caller does not prove its worker has stopped.\n}", exercise: "Choose a concurrency and queue/defer limit for a report job that shares a database pool with interactive requests, then state the overload outcome users and operators see.", quiz: "Why can an unbounded queue make a healthy dependency look slow?", answer: "Work waits before reaching the dependency, so queue age consumes deadlines and memory while latency rises. A visible bounded defer or rejection exposes capacity pressure early enough to protect the rest of the service." },
  { title: "5. Drain safely during deployment and cancellation", lesson: "A deployment should stop new claims before terminating workers, then give accepted work a bounded drain period. Make handlers cooperative: check cancellation between safe steps, persist progress or an UNKNOWN state before exit, and release or let the lease expire only after the result is durable. Only work that has not been dispatched may be deferred. An in-flight call remains DRAINING while the grace period remains, then becomes UNKNOWN at the deadline; an already ambiguous response remains UNKNOWN regardless of the deadline. Serialize dispatch with draining so a deferred job cannot start afterward. Never interrupt an external call and assume the side effect was undone.", whenToUse: "Use explicit draining when deployments or autoscaling can stop processes with active jobs.", avoid: "Avoid immediate process termination or pretending interruption reverses an external operation.", diagram: "drain signal → stop claiming → finish or persist UNKNOWN → release/expire lease → replacement recovers", example: "import java.util.Objects;\nfinal class DrainDecisionExample {\n  enum EffectState { NOT_DISPATCHED, IN_FLIGHT, CONFIRMED, UNKNOWN }\n  enum Outcome { COMPLETE, DRAINING, UNKNOWN, DEFERRED }\n  static Outcome onDrain(EffectState effect, boolean deadlineReached) {\n    return switch (Objects.requireNonNull(effect)) {\n      case CONFIRMED -> Outcome.COMPLETE;\n      case NOT_DISPATCHED -> Outcome.DEFERRED;\n      case UNKNOWN -> Outcome.UNKNOWN;\n      case IN_FLIGHT -> deadlineReached ? Outcome.UNKNOWN : Outcome.DRAINING;\n    };\n  }\n  // Serialize dispatch and the drain decision in the owning worker.\n  // Persist UNKNOWN with the original key before recovery; never redispatch\n  // merely because a drain deadline elapsed.\n}", exercise: "Write a drain policy for an export job that uploads one file part at a time. Specify the last safe checkpoint, deadline, and recovery state.", quiz: "What should a worker persist when shutdown interrupts it after an external request may have reached its destination?", answer: "Persist an explicit UNKNOWN or reconciliation-needed state with the original operation identity. A later worker can query the authority and continue safely; calling it cancelled or retrying blindly loses that information." },
  { title: "6. Observe lateness, backlog, and recovery", lesson: "A successful process heartbeat does not prove jobs are current. Measure due-to-start lateness, running count, deferred and failed counts by bounded reason, oldest due age, attempt count, terminal outcomes, and reconciliation age. Alert on the user or business deadline, then provide a runbook that identifies whether to add capacity, repair a dependency, reconcile, or replay.", whenToUse: "Use outcome and lateness signals when scheduled work has an operational or customer deadline.", avoid: "Avoid dashboards that report only executions started or an unbounded per-job metric label.", diagram: "due time → start time → completion outcome\nlate/failed/UNKNOWN → owner runbook → reconcile or bounded replay", example: "import java.time.*;\nfinal class JobLatenessExample {\n  static Duration lateness(Instant dueAt, Instant startedAt) {\n    Duration delay = Duration.between(dueAt, startedAt);\n    return delay.isNegative() ? Duration.ZERO : delay;\n  }\n  static boolean overdue(Duration delay, Duration target) {\n    return delay.compareTo(target) > 0;\n  }\n}", exercise: "Define one alert for overdue invoice close and one for accumulating UNKNOWN outcomes, including owner, first evidence query, and safe mitigation.", quiz: "Why is the age of the oldest due job more actionable than a raw count of worker starts?", answer: "Starts can rise while work never catches up. Oldest due age measures the business delay directly and helps distinguish a harmless burst from a backlog that is violating the job's completion objective." },
];
