export const CONNECTION_POOLS_BLOG = {
  id: "java-connection-pools",
  title: "Java Connection Pools: Ownership, Timeouts, and Safe Release",
  category: "Java data access",
  javaRelease: 17,
  summary: "A practical Java 17 course for keeping database connection pools responsive under slow dependencies, cancellation, leaks, and concurrent load.",
  lessons: [
    "A checked-out connection has one owner and must be released exactly once after its final database use.",
    "Pool exhaustion is a capacity and latency signal, not proof that SQL is slow.",
    "Deadlines, cancellation, transactions, and overload policy must preserve ownership instead of racing cleanup.",
  ],
  sections: [
    { heading: "Course goal", body: "Learn to make connection-pool behavior explicit: who owns a checkout, how long it may wait, which work may hold it, and what users and operators see when capacity is exhausted." },
    { heading: "Java production lens", body: "The standalone Java 17 examples model ownership and decision boundaries. A production pool also needs its driver's validation, server-side database limits, transaction manager, leak detection, metrics, and credentials handled by approved infrastructure." },
  ],
  example: "request deadline → bounded acquisition → transaction-only database use → exactly-once release → latency and saturation signals",
  interviewQuestions: [
    "Why can a full connection pool occur while the database CPU is low?",
    "When is it safe to release a connection after cancellation?",
    "Which metrics distinguish slow queries, long transactions, and pool starvation?",
  ],
  practice: "Design a checkout endpoint that has a 500 ms deadline, a small shared database pool, an optional recommendation call, and a user-visible overload response.",
  capstone: {
    title: "Capstone: Keep checkout responsive during pool pressure",
    scenario: "A checkout service shares a 20-connection pool with order history. A new implementation holds connections while calling a slow tax provider, clients abandon requests, and a deployment drains one replica.",
    steps: [
      "Define the checkout owner, acquisition deadline, transaction boundary, release point, and what cancellation does—and does not—prove about database work.",
      "Move remote work outside the checkout lifetime, set bounded pool and request admission, and define a safe overloaded response without falsely confirming an order.",
      "Instrument wait time, active/idle/pending counts, checkout duration, transaction duration, query latency, abandoned requests, and database saturation; verify the fix with deterministic contention tests.",
    ],
    outcome: "Produce a connection-pool policy that protects interactive traffic, releases ownership once, and explains whether pressure comes from queries, transactions, callers, or capacity.",
  },
};

export const CONNECTION_POOLS_CHAPTERS = [
  { title: "1. Treat checkout as owned, bounded work", lesson: "A pool checkout is a scarce lease to a database session, not a generic request token. Give it one owner, acquire it within the remaining request deadline, and close it exactly once after its final SQL operation. Use try-with-resources so exceptional paths share the same release rule. A caller cancellation only means the caller stopped waiting; it does not prove the database driver or worker has stopped using the connection.", whenToUse: "Use an explicit checkout lifetime for every request, job, or batch unit that borrows a pooled connection.", avoid: "Avoid acquiring before validation, remote I/O, queue waits, or work that does not need the database.", diagram: "remaining deadline → acquire connection → database-only work → close once\ncancelled caller → worker confirms stop → close", example: "import java.util.Objects;\nimport java.util.concurrent.atomic.AtomicBoolean;\nfinal class ConnectionLeaseExample {\n  static final class Lease implements AutoCloseable {\n    private final Runnable release;\n    private final AtomicBoolean closed = new AtomicBoolean();\n    Lease(Runnable release) { this.release = Objects.requireNonNull(release); }\n    public void close() { if (closed.compareAndSet(false, true)) release.run(); }\n  }\n  static Lease checkout(Runnable release) { return new Lease(release); }\n  static String query(Runnable release) {\n    try (Lease ignored = checkout(release)) { return \"result\"; }\n  }\n}", exercise: "Mark the first and last database operation in a checkout request. Move every validation, remote call, and serialization step outside that interval unless it needs the transaction.", quiz: "Why is caller cancellation not itself permission to return a connection to the pool?", answer: "A cancellation can race with a worker or driver that is still reading, writing, rolling back, or closing server state. Release only when the code that owns the checkout has observed a safe completion point; otherwise another borrower can inherit a live operation." },
  { title: "2. Budget acquisition and query deadlines together", lesson: "A request deadline is shared. Reserve time for validation and response handling, bound pool acquisition by the remaining budget, and set statement and network timeouts that cannot outlive it. An acquisition timeout is overload evidence, while a query timeout is execution evidence; treat them differently. Use the same monotonic deadline source at the boundary rather than independently generous timeouts that add up beyond the caller's patience.", whenToUse: "Use a shared deadline when a request waits for a pool, database, and downstream work.", avoid: "Avoid giving every layer its own full request timeout or retrying after the remaining budget is exhausted.", diagram: "500 ms request budget → 80 ms acquire → 300 ms query → reserve response time\nno lease by 80 ms → overload outcome", example: "final class PoolDeadlineExample {\n  static long remainingMillis(long deadlineMillis, long nowMillis) {\n    if (deadlineMillis < 0 || nowMillis < 0) throw new IllegalArgumentException();\n    return Math.max(0, deadlineMillis - nowMillis);\n  }\n  static long acquireTimeoutMillis(long deadlineMillis, long nowMillis, long responseReserveMillis) {\n    if (responseReserveMillis < 0) throw new IllegalArgumentException();\n    return Math.max(0, remainingMillis(deadlineMillis, nowMillis) - responseReserveMillis);\n  }\n  static boolean mayStartQuery(long deadlineMillis, long nowMillis, long queryBudgetMillis) {\n    return queryBudgetMillis > 0 && remainingMillis(deadlineMillis, nowMillis) >= queryBudgetMillis;\n  }\n}", exercise: "Allocate a 750 ms request deadline among validation, pool acquisition, one query, and response serialization. State what outcome occurs when no connection is available by the acquisition deadline.", quiz: "Why should a pool wait consume the same budget as the query that follows it?", answer: "The user experiences one request, not separate pool and database operations. If each layer receives a full timeout, queued work begins after the caller has already lost interest, consumes capacity, and worsens the next request's latency." },
  { title: "3. Keep transactions short and local", lesson: "Begin the transaction immediately before the database changes it protects, perform only the required SQL, then commit or roll back before calling remote systems, rendering a response, or waiting for another queue. Holding a connection during remote I/O converts a slow dependency into database-pool starvation. A transaction boundary protects database invariants; it does not atomically include a remote payment or message publish, which need an outbox or reconciliation contract.", whenToUse: "Use a short local transaction for one database consistency boundary.", avoid: "Avoid keeping a transaction open across HTTP calls, user think time, retries, or asynchronous handoffs.", diagram: "validate → begin transaction → SQL + invariant → commit/rollback → remote call\nremote call inside transaction ─X→ long checkout", example: "final class TransactionBoundaryExample {\n  enum Step { VALIDATED, IN_TRANSACTION, COMMITTED, ROLLED_BACK, REMOTE_CALLED }\n  static Step next(Step step, boolean databaseSucceeded) {\n    return switch (step) {\n      case VALIDATED -> Step.IN_TRANSACTION;\n      case IN_TRANSACTION -> databaseSucceeded ? Step.COMMITTED : Step.ROLLED_BACK;\n      case COMMITTED -> Step.REMOTE_CALLED;\n      default -> throw new IllegalStateException(\"invalid transition\");\n    };\n  }\n}", exercise: "Draw the shortest transaction for creating an order plus an outbox record. Identify which payment outcome remains ambiguous after the transaction commits.", quiz: "Why does moving a remote call outside a transaction not make the workflow unsafe by itself?", answer: "It restores pool ownership and database isolation, but it exposes a cross-system boundary. Persist the local intent and use an outbox, idempotency key, or reconciliation rule so the remote effect can converge without pretending one transaction covered both systems." },
  { title: "4. Diagnose pressure before changing pool size", lesson: "A full pool can mean slow queries, lock waits, long transactions, leaked connections, a traffic burst, or a remote call held inside a checkout. Measure acquisition wait and timeout counts, active/idle/pending connections, checkout duration, transaction duration, query latency, database CPU, lock waits, and connection age together. Increasing the pool without a database capacity budget can add contention and make tail latency worse.", whenToUse: "Use correlated pool and database signals whenever requests queue or acquisition times out.", avoid: "Avoid diagnosing from active-count or database CPU alone, or raising the pool size before identifying the holding path.", diagram: "pool wait + pending ↑ → compare query latency, transaction age, lock waits, DB saturation\nlong checkout + normal SQL → inspect ownership", example: "import java.time.Duration;\nfinal class PoolPressureExample {\n  record Snapshot(int active, int idle, int pending, Duration queryP95, Duration checkoutP95) {\n    Snapshot { if (active < 0 || idle < 0 || pending < 0) throw new IllegalArgumentException(); }\n  }\n  static String likelyCause(Snapshot snapshot) {\n    if (snapshot.pending() == 0) return \"no-pool-queue\";\n    if (snapshot.checkoutP95().compareTo(snapshot.queryP95()) > 0) return \"long-checkout-or-non-query-wait\";\n    return \"query-or-database-pressure\";\n  }\n}", exercise: "Given high acquisition wait, normal query p95, and long checkout p95, write the first two traces or metrics you would inspect before changing pool size.", quiz: "Why can a healthy-looking database CPU graph coexist with a saturated pool?", answer: "Connections may be checked out while callers wait on a lock, remote service, application queue, or abandoned path rather than executing CPU-heavy SQL. The pool reports ownership duration, while CPU reports only one possible part of that duration." },
  { title: "5. Handle cancellation, retries, and stale ownership safely", lesson: "Cancellation must reach the owner that can stop or safely finish the database operation; then that owner commits, rolls back, or closes before releasing the lease. Do not let a timeout callback and a normal completion both return the same connection unless release is idempotent. Retry only an operation whose transaction outcome is known or whose command has a durable idempotency contract. After a network error during commit, the outcome may be unknown: query an authoritative record or reconcile instead of replaying a write blindly.", whenToUse: "Use explicit ownership and reconciliation rules for cancellable requests and retryable database commands.", avoid: "Avoid releasing from a watchdog while the original worker can still use the connection, or retrying an ambiguous commit as if it failed.", diagram: "cancel request → owner stops or rolls back → release once\ncommit response lost → UNKNOWN → query/reconcile → safe next action", example: "import java.util.concurrent.atomic.AtomicBoolean;\nfinal class CompletionRaceExample {\n  private final AtomicBoolean released = new AtomicBoolean();\n  boolean releaseOnce() { return released.compareAndSet(false, true); }\n  static String retryDecision(boolean commitOutcomeKnown, boolean idempotent) {\n    if (!commitOutcomeKnown) return \"RECONCILE\";\n    return idempotent ? \"RETRY\" : \"DO_NOT_RETRY\";\n  }\n}", exercise: "Trace a request whose response deadline fires while the driver is still committing. Define the owner, the durable state to inspect, the release event, and whether a retry is allowed.", quiz: "What is the safe default after a lost commit response?", answer: "Treat it as UNKNOWN, not failed. The database may have committed even though the client did not receive confirmation. Reconcile using an operation identity or authoritative state before any retry, compensation, or user-visible final answer." },
  { title: "6. Protect capacity with admission and operational policy", lesson: "The pool is one bounded dependency inside a larger service. Set request admission, pool size, database connection budget, queue limit, and acquisition timeout intentionally. Reject or defer work before it consumes every thread; return a clear retryable overload response only for operations whose semantics permit it. Drain deployments by stopping new admission, allowing active database work to reach a safe commit or rollback point, and releasing each checkout through its owner.", whenToUse: "Use bounded admission and a documented overload policy when many endpoints share finite database connections.", avoid: "Avoid unbounded request queues, treating every timeout as retryable, or terminating a process before active transactions have reached a safe outcome.", diagram: "request → bounded admission → pool checkout → commit/rollback → release\nfull admission/pool → explicit overload or defer → metrics + runbook", example: "import java.util.Optional;\nimport java.util.concurrent.Semaphore;\nfinal class PoolAdmissionExample {\n  private final Semaphore permits;\n  PoolAdmissionExample(int capacity) {\n    if (capacity < 1) throw new IllegalArgumentException();\n    permits = new Semaphore(capacity);\n  }\n  Optional<Permit> tryAdmit() { return permits.tryAcquire() ? Optional.of(new Permit()) : Optional.empty(); }\n  final class Permit implements AutoCloseable {\n    private boolean closed;\n    private Permit() { } // Only tryAdmit can create an acquired handle.\n    public synchronized void close() { if (!closed) { closed = true; permits.release(); } }\n  }\n}", exercise: "Choose a connection budget for interactive checkout and reporting. Specify which workload is rejected or deferred first, what the client sees, and the operator signal that triggers investigation.", quiz: "Why is an unbounded request queue dangerous when the pool is full?", answer: "It turns a finite dependency into growing memory and deadline debt. Work waits until requests expire, then may still run and compete with current users. A bounded rejection or defer policy preserves capacity and makes pressure visible early." },
];
