// Concrete examples precede terminology. IDs match the existing lesson routes.
const guide = (title, story, steps, takeaway, terms, question, answer) => ({ title, story, steps, takeaway, terms, question, answer });
export const COURSE_VISUAL_GUIDES = {
  'llm-foundations': guide('What actually goes into a model request?', 'Maya asks our study app: “What should I practise about Java collections?” The app must package the question and useful notes before asking a language model (LLM) to draft an answer.', [
    ['Maya → application', 'Question: “What should I practise?” Profile: knows Java. These are application data.'],
    ['Application → model', 'Send instructions + latest question + selected chat history + notes. The model does not automatically open our database.'],
    ['Model → application', 'Draft: “Compare List and Set for 30 minutes.” This generated text is a proposal.'],
    ['Application → Maya', 'Check the duration and supporting note before displaying the plan. Saving is a separate action.'],
  ], 'Context is the packet sent for this request. A context window is its size limit, including room for the reply in this simplified example.', [['Token', 'A piece of text counted by the selected model’s tokenizer; not necessarily a whole word.'], ['Inference', 'Running the model to produce a response. Its learned parameters are not updated by this request.'], ['Headroom', 'Unused capacity after input and output reservation. It is not evidence that the answer is true.']], 'If the app stores yesterday’s chat but does not send it, can the model read that chat automatically?', 'No. Stored application data must be supplied or retrieved into the request. Learned patterns are different from access to that chat.'),
  'prompt-contracts': guide('Follow a response through three checks', 'Maya wants a 30-minute Java plan. The response below is made-up model output so we can inspect the boundary.', [
    ['Ask with a contract', 'Use note java-1. Return topic, sourceId, and integer minutes between 10 and 60.'],
    ['Parse the response', '{"topic":"Java collections","sourceId":"java-1","minutes":"30"} is valid JSON.'],
    ['Check types → STOP', '"30" is text, not a number. Reject this proposal before showing it as a usable plan.'],
    ['If corrected → check meaning', 'With minutes: 30, check the allowed source and whether its passage supports the topic.'],
  ], 'A clear prompt describes what you want. Application checks decide what you accept.', [['Schema', 'Rules about fields and their types.'], ['Abstain', 'Say there is insufficient evidence instead of inventing an answer.']], 'Would minutes: 300 pass?', 'It passes the integer check but fails the allowed 10–60 range.'),
  'retrieval-rag': guide('Find the page before writing the answer', 'Maya asks about Java collections. The app has Java notes, SQL notes, and another customer’s private notes.', [
    ['Filter by access', 'Keep Maya’s Java and SQL notes. Exclude the other customer’s note before it can enter context.'],
    ['Search allowed notes', '“Java collections” matches java-1: “List ordering and Set uniqueness.”'],
    ['Attach evidence → draft', 'Send the question and java-1 to generation; ask for a plan supported by that passage.'],
    ['Check citation → answer', 'Verify the claim against java-1. With no supporting note, return “I don’t have evidence for that.”'],
  ], 'RAG adds a search step before generation. Finding a similar passage and writing a supported answer are separate jobs.', [['RAG', 'Retrieval-Augmented Generation: find evidence, supply it, then generate.'], ['Embedding', 'A numerical representation used to compare related text. The local lab instead matches words.'], ['Tenant', 'A customer or organization whose data must be kept separate.']], 'Where would a missed synonym cause failure?', 'During search. The right note never reaches generation; changing the answer prompt cannot recover an absent source.'),
  'evaluation-cost': guide('Choose with a scorecard, not a feeling', 'You compare two hypothetical models on the same 100 questions. The product requires p95 latency below 1,200 ms.', [
    ['Fix the exam', 'Keep the same questions, evidence, and grading rules for both candidates.'],
    ['Measure candidate A', '82/100 correct; p95 response time 900 ms. Meets this latency target.'],
    ['Measure candidate B', '90/100 correct; p95 response time 1,800 ms. Fails this latency target.'],
    ['Apply every gate', 'B cannot launch under these constraints. A still needs to meet the separate quality and privacy gates.'],
  ], 'More correct answers do not erase an unacceptable delay or a privacy failure.', [['Held-out', 'Examples kept away from prompt tuning, used for the final comparison.'], ['p95', 'The 95th-percentile measured response time; the slow tail matters.']], 'At $0.002 per attempt, what do two attempts cost?', '$0.004 per request under these illustrative rates; multiply by request count, then add other service costs.'),
  'workflows-agents': guide('A proposal is not a saved plan', 'The model proposes a 30-minute Java plan. Follow the application states before anything is saved.', [
    ['Draft → validate', 'Check the plan fields and evidence. Invalid proposals stop here.'],
    ['Valid → pending approval', 'Show the exact plan. No approval or cancellation means no save.'],
    ['Approved → compare version', 'If 30 minutes changed to 45 after approval, stop and request approval of the new plan.'],
    ['Matching approval → save once', 'Record the operation ID. An identical replay returns the existing result instead of saving again.'],
  ], 'A workflow uses steps chosen by code. An agent chooses steps dynamically; both still need application-enforced permissions.', [['State', 'Where an operation currently stands, such as pending or saved.'], ['Idempotency', 'Handling a repeated operation without repeating its side effect.']], 'If a save times out, does that prove nothing was saved?', 'No. The response may be lost after the write. Look up the operation or use a service that safely deduplicates retries.'),
  'ai-assisted-coding': guide('See the bug before asking AI to fix it', 'Two notes match: a private note scores 10 and Maya’s allowed note scores 8. We want one allowed result.', [
    ['Bug: rank → take 1', 'The private note wins the only slot.'],
    ['Then filter → empty', 'Removing the private note now leaves no result. Maya’s useful note was already discarded.'],
    ['Fix: filter → rank → take 1', 'Remove private notes first. Maya’s score-8 note now wins.'],
    ['Prove the change', 'Use both notes in a test. Expect the allowed note and an unchanged original corpus.'],
  ], 'Tell the coding assistant the failing example and expected behavior, then independently inspect the patch and test.', [['Fixture', 'Controlled example data used by a test.'], ['Regression', 'Previously correct behavior broken by a change.']], 'Why is a test with only the allowed note too weak?', 'Both the buggy and fixed orders pass it. The private higher-scoring note is what triggers this bug.'),
};

// Small, lesson-specific storyboards for both introductory paths and advanced workshops.
const additional = [
  ['what-generates', 'Who does what?', 'Build a study plan for Maya.', ['Maya asks|“Help me learn SQL.”', 'Model proposes|“Practise joins for 30 minutes.”', 'Application checks|Duration, source support, and ownership.', 'Authorized service saves|Only the actual write makes the plan saved.'], 'Generated words are a suggestion; inspect application state to confirm an action.'],
  ['tokens-context', 'The request is a packed envelope', 'The app has a long chat, but sends only selected information.', ['Stored outside|Full chat and document collection remain in app storage.', 'Pack the request|Instructions, question, selected history, and evidence.', 'Reserve reply space|Input and output reservation share this illustrative limit.', 'Over capacity → stop|Remove irrelevant old material while preserving the question.'], 'The model can use the selected packet; storing a chat does not automatically send it.'],
  ['prompt-basics', 'Turn a wish into a contract', 'Replace “make a good plan” with an inspectable request.', ['Task|Suggest one Java study topic.', 'Evidence|Use only the attached java-1 note.', 'Response|topic + sourceId + integer minutes, 10–60.', 'Missing evidence|Return an explicit “not enough information.”'], 'These instructions guide generation; a validator still enforces the rules.'],
  ['model-boundary', 'Trace the network boundary', 'The browser requests a study plan.', ['Browser → your server|Send the question; keep provider credentials off the browser.', 'Server → model|Authenticate, assemble permitted context, set limits.', 'Model → server|Return a proposed plan; failures and malformed output are possible.', 'Server → browser|Validate before presenting a usable result.'], 'Streaming text can appear before a complete, validated result exists.'],
  ['choose-pattern', 'Match the missing capability', 'Different requests need different components. These are alternatives, not a sequence.', ['Text already supplied|Summarize it with a prompt.', 'Current handbook missing|Retrieve authorized passages first.', 'Exact arithmetic needed|Use a calculation tool.', 'Learned behavior needs adaptation|Consider fine-tuning with reviewed examples and evaluation.'], 'Use the component that addresses the observed gap. An agent is not required for every AI feature.'],
  ['first-release', 'A passing demo is the starting line', 'The local fake model always follows scripted behavior.', ['Local checks|Reject malformed plans and duplicate writes.', 'Live evaluation|Ask new questions and grade source support.', 'Operational checks|Measure response times, usage, and failure behavior.', 'Release decision|Compare all results to predefined gates; prepare rollback.'], 'Local correctness and real-model answer quality require different evidence.'],
  ['rag-purpose', 'An open-book answer', 'Question: “When does the reset link expire?”', ['Question|The answer must come from the current help guide.', 'Retrieve|Find the reset-link paragraph.', 'Supply evidence|“The reset link expires after 10 minutes.”', 'Answer and verify|“10 minutes” with a source that actually supports it.'], 'Retrieval supplies pages to this request; it does not retrain the model.'],
  ['rag-ingest', 'Keep meaning when cutting a document', 'A help page contains headings, paragraphs, and navigation.', ['Document|Password reset → The reset link expires after 10 minutes.', 'Clean|Remove menu text; retain the subject and heading.', 'Chunk|Keep “reset link” with “10 minutes” in one understandable piece.', 'Attach metadata|Source ID, location, version, and access rules travel with the chunk.'], 'A chunk saying only “It expires after 10 minutes” loses the subject.'],
  ['rag-vectors', 'Turn words into comparable coordinates', 'Toy vocabulary: [password, reset, hours]. These counts illustrate vectors, not learned embeddings.', ['Question: password reset|Vector [1, 1, 0].', 'Reset note: password reset|Vector [1, 1, 0]; same direction.', 'Support note: hours|Vector [0, 0, 1]; perpendicular direction.', 'Compare|Cosine is 1 for the reset note and 0 for the hours note.'], 'Coordinates must use the same representation. Similarity is not a probability that an answer is true.'],
  ['rag-retrieve', 'Top-k means a limited shortlist', 'Suppose three authorized chunks have illustrative scores 0.9, 0.6, and 0.2.', ['Score|A: 0.9 · B: 0.6 · C: 0.2.', 'Sort|A comes before B, then C.', 'Choose k = 2|Only A and B enter the shortlist.', 'Rerank shortlist|Can reorder A and B; cannot recover omitted C.'], 'Inspect whether the needed passage survived selection before debugging generation.'],
  ['rag-generate', 'A citation needs a support check', 'The source says “reset links expire in 10 minutes.”', ['Context|Question plus the reset passage and its source ID.', 'Draft|“Links expire in 30 minutes [reset-1].”', 'ID check passes|reset-1 is a real supplied source.', 'Support check fails|The passage says 10, not 30. Reject or correct the claim.'], 'A real citation can still be attached to an unsupported statement.'],
  ['rag-evaluate', 'Locate the failed stage', 'Relevant sources are A and B. Search returns A and unrelated C.', ['Expected evidence|Two relevant sources: A, B.', 'Retrieved evidence|A, C: one relevant out of two returned.', 'Calculate|Precision = 1/2; recall = 1/2.', 'Review answer separately|Did it accurately use A, or invent an unsupported claim?'], 'Retrieval metrics describe the evidence found; they do not grade the final answer.'],
  ['advanced-retrieval', 'Two search routes, one checked packet', 'An exact error code and a paraphrase may need different search signals.', ['Authorized candidates|Search only within the caller’s permitted scope.', 'Parallel searches|Lexical search finds exact terms; dense search finds related representations.', 'Merge → rerank|Deduplicate source IDs and combine ranks, then select candidates.', 'Recheck → context|Confirm current permissions, deletion state, and source versions before use.'], 'Fusion cannot make revoked or stale evidence safe.'],
  ['advanced-evaluation', 'A better average can still block release', 'In 100 paired cases, eight improve and two regress.', ['Baseline|82 unchanged passes + 2 regressions = 84 passes.', 'Candidate|82 unchanged passes + 8 improvements = 90 passes.', 'Inspect regressions|One exposes another tenant’s data.', 'Gate → blocked|The candidate fails the hard privacy gate despite its six-point gain.'], 'Keep safety gates separate from averages and inspect the same cases in both versions.'],
  ['advanced-serving', 'A request has more than one clock', 'Follow a request from arrival to a usable response.', ['Queue + retrieval|Wait for capacity and collect evidence.', 'Prefill|Process the input; no answer token yet.', 'Decode + stream|Generate tokens; the user sees partial text.', 'Validate → usable result|Only the completed response can pass the contract checks.'], 'First-token latency measures visible progress. Completed-result latency measures when the result is usable.'],
  ['advanced-tools', 'Recover after the response is lost', 'A calendar provider accepts operation K, but its HTTP response never arrives.', ['Persist intent|Record K, actor, approved payload, and execution state.', 'Call provider|Use K as a deduplication key if supported.', 'Timeout → unknown|Do not mark it failed merely because the reply is missing.', 'Reconcile|Look up K or use a safe deduplicated retry; otherwise escalate for recovery.'], 'Local database transactions do not atomically include an arbitrary external HTTP service.'],
  ['advanced-adaptation', 'Diagnose before changing the model', 'Sort 100 failures by cause. These branches suggest separate experiments.', ['60 missing evidence|Try current, authorized retrieval.', '25 invalid format|Improve the contract and enforce validation.', '15 reasoning failures|Compare prompts and models on the same supplied evidence.', 'Remaining behavior gap|Consider tuning only with suitable data and independent evaluation.'], 'Choose an intervention by failure cause and measure whether it fixes that cause.'],
  ['advanced-incidents', 'Watch a cache cross a tenant boundary', 'Two customers ask the same question: “What is my study plan?”', ['Tenant A asks|Cache stores A’s answer under question text only.', 'Tenant B asks|The same key returns A’s private answer.', 'Contain|Disable the unsafe cache and invalidate unsafe entries.', 'Repair and verify|Use trusted authorization scope and relevant versions; test both identities and revocation.'], 'A cache hit must preserve the same access rules as an uncached response.'],
];
for (const [id, title, story, steps, takeaway] of additional) {
  COURSE_VISUAL_GUIDES[id] = { title, story, steps: steps.map(step => step.split('|')), takeaway };
}

export function calculateTeachingBudget(history = 1600, extraDocument = false) {
  const parts = [
    ['Instructions', 800], ['Profile + latest question', 600], ['Selected history', history],
    ['Retrieved notes', 3000], ...(extraDocument ? [['Extra document', 1500]] : []), ['Reserved reply', 1000],
  ];
  const used = parts.reduce((sum, [, tokens]) => sum + tokens, 0);
  return { parts, used, remaining: 8000 - used };
}
