const PATTERN_ATLAS = [
  {
    id: "sliding-window",
    title: "Sliding Window",
    icon: "ti-arrows-horizontal",
    difficulty: "Beginner",
    beginnerMeaning: "Use a moving contiguous window when the answer lives inside a subarray or substring.",
    memoryHook: "Keep a frame over the array, then slide or resize it instead of restarting.",
    visualHint: { type: "window", items: ["L", "3", "-1", "5", "R"] },
    whenToUse: [
      "The problem asks for subarray or substring.",
      "You need max, min, count, or length over a contiguous range.",
      "Each step can add the right item and sometimes remove the left item.",
    ],
    examples: ["Maximum sum subarray of size K", "Longest substring without repeating characters", "Minimum window substring"],
    pitfalls: ["Forgetting that the range must be contiguous", "Shrinking the window without explaining the condition"],
    drillId: "drill-two-pointers",
  },
  {
    id: "two-pointers",
    title: "Two Pointers",
    icon: "ti-arrows-left-right",
    difficulty: "Beginner",
    beginnerMeaning: "Use two moving positions when comparing both ends or walking two sequences together.",
    memoryHook: "Two fingers move only when you can prove what gets skipped.",
    visualHint: { type: "pointers", items: ["L", "1", "2", "7", "9", "R"] },
    whenToUse: [
      "The input is sorted or can be sorted.",
      "You are searching for a pair, removing duplicates, or reversing.",
      "Moving one pointer safely eliminates choices.",
    ],
    examples: ["Two Sum in sorted array", "Remove duplicates", "Valid palindrome"],
    pitfalls: ["Using it on unsorted input without a reason", "Moving both pointers when only one is justified"],
    drillId: "drill-two-pointers",
  },
  {
    id: "binary-search",
    title: "Binary Search",
    icon: "ti-binary-tree",
    difficulty: "Beginner",
    beginnerMeaning: "Use it when the answer space is ordered and one check tells you which half to discard.",
    memoryHook: "The answer always stays inside low and high.",
    visualHint: { type: "range", items: ["low", "2", "5", "mid", "9", "high"] },
    whenToUse: [
      "The data is sorted or the answer space is monotonic.",
      "A true/false check can discard half the candidates.",
      "The problem asks for first, last, minimum valid, or maximum valid.",
    ],
    examples: ["Search sorted array", "First bad version", "Minimum capacity to ship packages"],
    pitfalls: ["Wrong loop boundary", "Not defining what low and high mean"],
    drillId: "drill-arrays",
  },
  {
    id: "prefix-sum",
    title: "Prefix Sum",
    icon: "ti-sum",
    difficulty: "Beginner",
    beginnerMeaning: "Precompute running totals so a range sum becomes a quick subtraction.",
    memoryHook: "Range sum equals prefix at right minus prefix before left.",
    visualHint: { type: "prefix", items: ["2", "5", "4", "8", "13"] },
    whenToUse: [
      "The question asks many range sum queries.",
      "Subarray sums need to be checked repeatedly.",
      "You can trade a little memory for faster lookups.",
    ],
    examples: ["Range sum query", "Subarray sum equals K", "Find pivot index"],
    pitfalls: ["Off-by-one prefix indexes", "Forgetting prefix 0 before the array starts"],
    drillId: "drill-arrays",
  },
  {
    id: "hashing",
    title: "Hashing",
    icon: "ti-hash",
    difficulty: "Beginner",
    beginnerMeaning: "Use a map or set to remember facts so future checks are fast.",
    memoryHook: "Write down what you have seen, then ask the map instead of searching again.",
    visualHint: { type: "map", items: ["a -> 3", "b -> 2", "c -> 1"] },
    whenToUse: [
      "You need frequency, membership, or complement lookup.",
      "Brute force keeps searching for something already seen.",
      "Order is less important than fast lookup.",
    ],
    examples: ["Two Sum", "Group anagrams", "Longest consecutive sequence"],
    pitfalls: ["Pairing an element with itself", "Ignoring duplicate counts"],
    drillId: "drill-hashing",
  },
  {
    id: "backtracking",
    title: "Recursion + Backtracking",
    icon: "ti-route-alt-left",
    difficulty: "Intermediate",
    beginnerMeaning: "Try a choice, explore it, then undo it before trying the next choice.",
    memoryHook: "Choose, explore, unchoose.",
    visualHint: { type: "tree", items: ["[]", "[1]", "[1,2]", "[2]"] },
    whenToUse: [
      "The problem asks for all subsets, permutations, or combinations.",
      "You must explore choices with constraints.",
      "A partial answer can be abandoned early.",
    ],
    examples: ["Subsets", "Permutations", "N-Queens"],
    pitfalls: ["Forgetting to undo state", "Not pruning invalid branches"],
    drillId: "drill-trees",
  },
  {
    id: "stack-queue",
    title: "Stack / Queue",
    icon: "ti-stack-2",
    difficulty: "Beginner",
    beginnerMeaning: "Use stack for most-recent unfinished work and queue for first-in-first-out work.",
    memoryHook: "Stack is plates. Queue is a line.",
    visualHint: { type: "stack", items: ["top", "5", "3", "2"] },
    whenToUse: [
      "Nested or previous-state problems need a stack.",
      "Level order or shortest steps need a queue.",
      "The next item follows LIFO or FIFO order.",
    ],
    examples: ["Valid parentheses", "Next greater element", "Sliding window maximum"],
    pitfalls: ["Using a stack when distance/levels require a queue", "Popping without checking empty state"],
    drillId: "drill-stack-queue",
  },
  {
    id: "linked-list",
    title: "Linked List Techniques",
    icon: "ti-link",
    difficulty: "Beginner",
    beginnerMeaning: "Use slow/fast pointers, dummy nodes, and careful rewiring for node chains.",
    memoryHook: "Never lose the next pointer before rewiring.",
    visualHint: { type: "list", items: ["1", "2", "3", "4", "null"] },
    whenToUse: [
      "The input is a node chain instead of an array.",
      "You need cycle detection, middle node, merge, or reverse.",
      "A dummy node can simplify head changes.",
    ],
    examples: ["Detect cycle", "Reverse list", "Merge two sorted lists"],
    pitfalls: ["Losing the rest of the list", "Forgetting null checks"],
    drillId: "drill-two-pointers",
  },
  {
    id: "heap",
    title: "Heap / Priority Queue",
    icon: "ti-triangle-square-circle",
    difficulty: "Intermediate",
    beginnerMeaning: "Use a heap when you repeatedly need the smallest or largest item fast.",
    memoryHook: "Heap keeps the best candidate at the top.",
    visualHint: { type: "heap", items: ["10", "7", "9", "2", "5"] },
    whenToUse: [
      "The problem asks for top K, kth, or running median.",
      "You need repeated min or max extraction.",
      "Sorting everything would do more work than needed.",
    ],
    examples: ["Kth largest element", "Merge K sorted lists", "Task scheduler"],
    pitfalls: ["Using a max heap when a fixed-size min heap is cleaner", "Not explaining heap size"],
    drillId: "drill-arrays",
  },
  {
    id: "trees",
    title: "Trees + Traversals",
    icon: "ti-binary-tree",
    difficulty: "Intermediate",
    beginnerMeaning: "Solve one node, ask children for answers, then combine the results.",
    memoryHook: "Define what each recursive call returns.",
    visualHint: { type: "tree", items: ["1", "2", "3", "4", "5"] },
    whenToUse: [
      "The input has parent-child structure.",
      "The answer can be built from left and right subtrees.",
      "Traversal order matters: preorder, inorder, postorder, or level order.",
    ],
    examples: ["Max depth", "Validate BST", "Lowest common ancestor"],
    pitfalls: ["Not defining the helper return value", "Ignoring recursion stack space"],
    drillId: "drill-trees",
  },
  {
    id: "dp",
    title: "Dynamic Programming",
    icon: "ti-table",
    difficulty: "Advanced",
    beginnerMeaning: "Store answers to repeated subproblems after defining state, transition, and base cases.",
    memoryHook: "Never pay twice for the same subproblem.",
    visualHint: { type: "dp", items: ["dp[0]", "dp[1]", "dp[2]", "dp[n]"] },
    whenToUse: [
      "The same smaller problem appears many times.",
      "The best answer can be built from previous answers.",
      "Greedy choices are not obviously safe.",
    ],
    examples: ["Climbing stairs", "House robber", "Longest increasing subsequence"],
    pitfalls: ["Coding before defining state", "Skipping base cases"],
    drillId: "drill-dp-basics",
  },
  {
    id: "graphs",
    title: "Graph Algorithms",
    icon: "ti-graph",
    difficulty: "Intermediate",
    beginnerMeaning: "Use visited plus BFS or DFS to explore relationships without repeating nodes forever.",
    memoryHook: "Visited is the seatbelt.",
    visualHint: { type: "graph", items: ["A-B", "A-C", "B-D", "C-D"] },
    whenToUse: [
      "The input is connections, dependencies, or a grid.",
      "You need reachability, shortest unweighted path, or components.",
      "Cycles are possible.",
    ],
    examples: ["Number of islands", "Course schedule", "Shortest path in unweighted graph"],
    pitfalls: ["Missing visited set", "Choosing DFS when BFS distance is required"],
    drillId: "drill-graph-bfs-dfs",
  },
  {
    id: "kadane",
    title: "Kadane's Algorithm",
    icon: "ti-chart-line",
    difficulty: "Intermediate",
    beginnerMeaning: "Track the best subarray ending here and the best answer seen overall.",
    memoryHook: "Carry the useful streak; drop the harmful prefix.",
    visualHint: { type: "array", items: ["-2", "1", "-3", "4", "-1", "2"] },
    whenToUse: [
      "The problem asks for maximum subarray sum.",
      "Negative numbers can hurt a running segment.",
      "You need one pass and constant space.",
    ],
    examples: ["Maximum subarray", "Maximum circular subarray", "Best profit streak variants"],
    pitfalls: ["Resetting to zero when all numbers are negative", "Confusing subsequence with subarray"],
    drillId: "drill-arrays",
  },
  {
    id: "greedy",
    title: "Greedy Algorithm",
    icon: "ti-target-arrow",
    difficulty: "Intermediate",
    beginnerMeaning: "Make the locally best choice only when you can prove it never blocks the optimal answer.",
    memoryHook: "Greedy needs proof, not vibes.",
    visualHint: { type: "intervals", items: ["A", "B", "C", "D"] },
    whenToUse: [
      "Sorting plus local choice naturally improves the result.",
      "You can prove exchange or dominance.",
      "The problem asks for intervals, scheduling, or minimum operations.",
    ],
    examples: ["Activity selection", "Jump game", "Merge intervals"],
    pitfalls: ["Using greedy without a proof", "Sorting by the wrong key"],
    drillId: "drill-arrays",
  },
  {
    id: "bit-manipulation",
    title: "Bit Manipulation",
    icon: "ti-binary",
    difficulty: "Advanced",
    beginnerMeaning: "Use binary representation when toggles, masks, parity, or XOR properties simplify state.",
    memoryHook: "XOR cancels equal values.",
    visualHint: { type: "bits", items: ["0101", "0110", "0011"] },
    whenToUse: [
      "The problem mentions bits, XOR, masks, or powers of two.",
      "You need compact subset state.",
      "Pairs cancel and one value remains.",
    ],
    examples: ["Single number", "Counting bits", "Subsets with masks"],
    pitfalls: ["Forgetting operator precedence", "Not explaining the binary property used"],
    drillId: "drill-arrays",
  },
];

const DECISION_STEPS = [
  {
    question: "Is the input an array or string and the answer is a contiguous range?",
    yes: "Start with Sliding Window or Prefix Sum.",
    no: "Ask whether you need a pair, lookup, tree, graph, or DP state.",
  },
  {
    question: "Are you looking for a pair or comparing both ends?",
    yes: "If sorted, try Two Pointers. If unsorted lookup is needed, try Hashing.",
    no: "Check whether the problem is about a subarray, tree, graph, or choices.",
  },
  {
    question: "Does a range sum repeat across many queries or subarrays?",
    yes: "Use Prefix Sum. For only positive values and adjustable length, Sliding Window is often cleaner.",
    no: "If the range is not contiguous, avoid window patterns.",
  },
  {
    question: "Can a true/false check discard half the search space?",
    yes: "Use Binary Search over indexes or over the answer.",
    no: "Look for maps, stacks, recursion, greedy proof, or DP state.",
  },
  {
    question: "Do you need the next greater, matching bracket, or most recent unfinished item?",
    yes: "Use Stack. If processing by levels or distance, use Queue/BFS.",
    no: "Move to Trees, Graphs, Greedy, or DP.",
  },
  {
    question: "Are you exploring all valid choices?",
    yes: "Use Backtracking: choose, explore, unchoose.",
    no: "If repeated subproblems appear, use DP.",
  },
];

const COMPLEXITY_CHEATS = [
  { structure: "Array", access: "O(1)", search: "O(n)", insert: "O(n)", delete: "O(n)", beginnerNote: "Fast by index, slower when shifting is needed." },
  { structure: "HashMap", access: "O(1) avg", search: "O(1) avg", insert: "O(1) avg", delete: "O(1) avg", beginnerNote: "Great for lookup, frequency, and complements." },
  { structure: "Stack", access: "Top only", search: "O(n)", insert: "O(1)", delete: "O(1)", beginnerNote: "Use for most-recent unfinished work." },
  { structure: "Queue", access: "Front only", search: "O(n)", insert: "O(1)", delete: "O(1)", beginnerNote: "Use for level order and BFS distance." },
  { structure: "Binary Search Tree", access: "O(log n) avg", search: "O(log n) avg", insert: "O(log n) avg", delete: "O(log n) avg", beginnerNote: "Can degrade to O(n) if not balanced." },
  { structure: "Heap", access: "O(1) top", search: "O(n)", insert: "O(log n)", delete: "O(log n)", beginnerNote: "Best when you repeatedly need min or max." },
  { structure: "Graph BFS/DFS", access: "N/A", search: "O(V + E)", insert: "Depends", delete: "Depends", beginnerNote: "Visited prevents cycles and repeated work." },
];

const VISUAL_PLAYGROUND_MODULES = [
  {
    id: "array-list",
    title: "ArrayList",
    icon: "ti-layout-grid",
    category: "Linear",
    beginnerMeaning: "A resizable row of indexed slots. Reading by index is fast, but inserting near the front shifts many items.",
    visualModel: { type: "array", items: ["A", "B", "C", "_"] },
    operations: ["Access by index", "Append", "Insert with shifting", "Remove with shifting"],
    useWhen: "Use when order matters and you mostly read by index or append.",
    complexityHint: "Access O(1), search O(n), insert/delete O(n) when shifting.",
    commonMistake: "Assuming every insert is O(1). Appending is cheap; middle inserts are not.",
  },
  {
    id: "linked-list",
    title: "Linked List",
    icon: "ti-link",
    category: "Linear",
    beginnerMeaning: "Nodes point to the next node. Rewiring can be cheap once you have the node, but finding it takes a walk.",
    visualModel: { type: "list", items: ["1", "2", "3", "null"] },
    operations: ["Traverse", "Insert after node", "Delete after node", "Reverse links"],
    useWhen: "Use when the problem gives nodes directly or asks for pointer rewiring.",
    complexityHint: "Search O(n), insert/delete O(1) only after you already have the position.",
    commonMistake: "Losing the next pointer before reconnecting the chain.",
  },
  {
    id: "stack",
    title: "Stack",
    icon: "ti-stack-2",
    category: "Linear",
    beginnerMeaning: "Last in, first out. The newest unfinished item is always handled first.",
    visualModel: { type: "stack", items: ["top", ")", "(", "["] },
    operations: ["Push", "Pop", "Peek top", "Match nested state"],
    useWhen: "Use for parentheses, undo behavior, monotonic next-greater logic, or recursion simulation.",
    complexityHint: "Push and pop are O(1). Searching inside the stack is O(n).",
    commonMistake: "Popping before checking whether the stack is empty.",
  },
  {
    id: "queue",
    title: "Queue",
    icon: "ti-arrows-transfer-down",
    category: "Linear",
    beginnerMeaning: "First in, first out. Items are processed in the same order they arrive.",
    visualModel: { type: "queue", items: ["front", "A", "B", "C", "rear"] },
    operations: ["Enqueue", "Dequeue", "Peek front", "Level-order process"],
    useWhen: "Use for BFS, level order traversal, and shortest unweighted distance.",
    complexityHint: "Enqueue and dequeue are O(1) with the right implementation.",
    commonMistake: "Using an array shift in JavaScript and accidentally making dequeue O(n).",
  },
  {
    id: "hash-table",
    title: "Hash Table",
    icon: "ti-table",
    category: "Lookup",
    beginnerMeaning: "A key is converted into a bucket so lookup is usually constant time.",
    visualModel: { type: "map", items: ["key", "hash", "bucket", "value"] },
    operations: ["Put key", "Get key", "Count frequency", "Check complement"],
    useWhen: "Use for seen sets, frequencies, grouping, and complement lookup.",
    complexityHint: "Average O(1), worst O(n) if many keys collide.",
    commonMistake: "Forgetting duplicates require counts, not just presence.",
  },
  {
    id: "binary-heap",
    title: "Binary Heap",
    icon: "ti-triangle-square-circle",
    category: "Priority",
    beginnerMeaning: "A tree-shaped array where the best priority item stays at the top.",
    visualModel: { type: "heap", items: ["10", "9", "7", "5", "2"] },
    operations: ["Peek top", "Push", "Pop top", "Keep top K"],
    useWhen: "Use for kth largest, top K, scheduling, and repeated min or max extraction.",
    complexityHint: "Peek O(1), push/pop O(log n), search O(n).",
    commonMistake: "Sorting every time instead of maintaining only the needed heap.",
  },
  {
    id: "binary-search-tree",
    title: "Binary Search Tree",
    icon: "ti-binary-tree",
    category: "Trees",
    beginnerMeaning: "Left values are smaller, right values are larger. Balanced height keeps operations logarithmic.",
    visualModel: { type: "tree", items: ["8", "3", "10", "1", "6"] },
    operations: ["Search", "Insert", "Delete", "Inorder traversal"],
    useWhen: "Use when sorted order and dynamic updates matter.",
    complexityHint: "O(log n) average if balanced, O(n) if the tree becomes a chain.",
    commonMistake: "Claiming O(log n) without saying the tree must be balanced.",
  },
  {
    id: "graph-structures",
    title: "Graph Structures",
    icon: "ti-graph",
    category: "Graphs",
    beginnerMeaning: "Nodes connected by edges. Store neighbors, then explore with visited plus BFS or DFS.",
    visualModel: { type: "graph", items: ["A-B", "A-C", "B-D", "C-D"] },
    operations: ["Build adjacency list", "BFS", "DFS", "Detect components"],
    useWhen: "Use for networks, dependencies, grids, islands, and reachability.",
    complexityHint: "BFS/DFS is O(V + E) with adjacency lists.",
    commonMistake: "Skipping visited and looping forever on cycles.",
  },
  {
    id: "union-find",
    title: "Union-Find DS",
    icon: "ti-hierarchy",
    category: "Graphs",
    beginnerMeaning: "Tracks which items belong to the same group while connections are added.",
    visualModel: { type: "sets", items: ["A-B", "C", "D-E", "merge"] },
    operations: ["Find parent", "Union groups", "Path compression", "Count components"],
    useWhen: "Use for connectivity, redundant connection, Kruskal, and grouping as edges arrive.",
    complexityHint: "Almost O(1) amortized with path compression and union by rank.",
    commonMistake: "Finding roots but forgetting to compress paths or rank unions.",
  },
  {
    id: "sorting",
    title: "Sorting Algorithms",
    icon: "ti-sort-ascending",
    category: "Algorithms",
    beginnerMeaning: "Reorder data so later logic can use adjacency, two pointers, binary search, or greedy choices.",
    visualModel: { type: "bars", items: ["5", "1", "4", "2", "8"] },
    operations: ["Compare", "Swap/merge", "Partition", "Use sorted order"],
    useWhen: "Use before interval merging, pair search, greedy scheduling, or deduplication.",
    complexityHint: "Common comparison sorts are O(n log n); simple nested sorts are O(n^2).",
    commonMistake: "Forgetting sorting may change original index meaning.",
  },
  {
    id: "bitmask",
    title: "Bitmask",
    icon: "ti-binary",
    category: "Bits",
    beginnerMeaning: "Uses binary digits as compact yes/no switches for sets, flags, and parity tricks.",
    visualModel: { type: "bits", items: ["0101", "AND", "0011", "0001"] },
    operations: ["Set bit", "Clear bit", "Toggle bit", "Check membership"],
    useWhen: "Use for subsets, flags, XOR cancellation, and compact DP state.",
    complexityHint: "Bit operations are O(1) for fixed-width integers.",
    commonMistake: "Mixing up operator precedence when combining shifts and comparisons.",
  },
  {
    id: "skip-list",
    title: "Skip List",
    icon: "ti-layers-linked",
    category: "Advanced",
    beginnerMeaning: "A linked list with express lanes that skip ahead, giving average logarithmic search.",
    visualModel: { type: "levels", items: ["top: 1 -> 9", "mid: 1 -> 4 -> 9", "base: 1 -> 2 -> 4 -> 7 -> 9"] },
    operations: ["Search by levels", "Insert tower", "Delete tower", "Maintain sorted order"],
    useWhen: "Use as a mental model for layered search; interviews more often use trees or binary search.",
    complexityHint: "Search/insert/delete average O(log n), space O(n).",
    commonMistake: "Treating it like a normal linked list and missing the layered shortcuts.",
  },
];

const BIG_O_CHART = {
  title: "Big-O Cheat Sheet",
  subtitle: "A beginner map for how runtime grows as input size gets bigger.",
  curves: [
    { label: "O(1)", rating: "Excellent", shape: "Flat", example: "Array index lookup", explanation: "Work stays the same even when input grows." },
    { label: "O(log n)", rating: "Excellent", shape: "Slow climb", example: "Binary search", explanation: "Each step cuts the remaining search space." },
    { label: "O(n)", rating: "Good", shape: "Straight line", example: "Single scan", explanation: "Work grows once per item." },
    { label: "O(n log n)", rating: "Fair", shape: "Steady curve", example: "Merge sort", explanation: "Usually acceptable for sorting and divide-and-conquer." },
    { label: "O(n^2)", rating: "Bad", shape: "Steep curve", example: "All pairs", explanation: "Nested loops over the same input grow quickly." },
    { label: "O(2^n)", rating: "Horrible", shape: "Explosion", example: "All subsets", explanation: "Every extra item can double the choices." },
    { label: "O(n!)", rating: "Horrible", shape: "Wall", example: "All permutations", explanation: "Permutations become impossible for large n." },
  ],
  rules: [
    "Drop constants: O(2n) becomes O(n).",
    "Keep the dominant term: O(n^2 + n) becomes O(n^2).",
    "Different inputs can use different letters, such as O(n + m).",
    "Space complexity counts extra memory, not the input itself unless you copy it.",
  ],
};

const OPERATION_COMPLEXITIES = [
  {
    structure: "ArrayList",
    access: { average: "O(1)", worst: "O(1)" },
    search: { average: "O(n)", worst: "O(n)" },
    insert: { average: "O(n)", worst: "O(n)" },
    delete: { average: "O(n)", worst: "O(n)" },
    note: "Great by index; shifting makes middle edits linear.",
  },
  {
    structure: "Linked List",
    access: { average: "O(n)", worst: "O(n)" },
    search: { average: "O(n)", worst: "O(n)" },
    insert: { average: "O(1)", worst: "O(1)" },
    delete: { average: "O(1)", worst: "O(1)" },
    note: "O(1) insert/delete assumes you already have the node.",
  },
  {
    structure: "Stack",
    access: { average: "Top only", worst: "Top only" },
    search: { average: "O(n)", worst: "O(n)" },
    insert: { average: "O(1)", worst: "O(1)" },
    delete: { average: "O(1)", worst: "O(1)" },
    note: "Use for last-in-first-out decisions.",
  },
  {
    structure: "Queue",
    access: { average: "Front only", worst: "Front only" },
    search: { average: "O(n)", worst: "O(n)" },
    insert: { average: "O(1)", worst: "O(1)" },
    delete: { average: "O(1)", worst: "O(1)" },
    note: "Use for BFS and first-in-first-out processing.",
  },
  {
    structure: "Hash Table",
    access: { average: "N/A", worst: "N/A" },
    search: { average: "O(1) avg", worst: "O(n)" },
    insert: { average: "O(1) avg", worst: "O(n)" },
    delete: { average: "O(1) avg", worst: "O(n)" },
    note: "Average is excellent; collisions create the worst case.",
  },
  {
    structure: "Binary Search Tree",
    access: { average: "O(log n)", worst: "O(n)" },
    search: { average: "O(log n)", worst: "O(n)" },
    insert: { average: "O(log n)", worst: "O(n)" },
    delete: { average: "O(log n)", worst: "O(n)" },
    note: "Balanced trees keep the average promise.",
  },
  {
    structure: "Binary Heap",
    access: { average: "O(1) top", worst: "O(1) top" },
    search: { average: "O(n)", worst: "O(n)" },
    insert: { average: "O(log n)", worst: "O(log n)" },
    delete: { average: "O(log n)", worst: "O(log n)" },
    note: "Best for repeated min or max, not arbitrary lookup.",
  },
  {
    structure: "Skip List",
    access: { average: "O(log n)", worst: "O(n)" },
    search: { average: "O(log n)", worst: "O(n)" },
    insert: { average: "O(log n)", worst: "O(n)" },
    delete: { average: "O(log n)", worst: "O(n)" },
    note: "Layered linked structure with probabilistic balance.",
  },
  {
    structure: "Graph BFS/DFS",
    access: { average: "N/A", worst: "N/A" },
    search: { average: "O(V + E)", worst: "O(V + E)" },
    insert: { average: "Depends", worst: "Depends" },
    delete: { average: "Depends", worst: "Depends" },
    note: "V is vertices, E is edges.",
  },
  {
    structure: "Sorting Algorithms",
    access: { average: "N/A", worst: "N/A" },
    search: { average: "After sort: O(log n)", worst: "After sort: O(log n)" },
    insert: { average: "N/A", worst: "N/A" },
    delete: { average: "N/A", worst: "N/A" },
    note: "Merge/heap sort O(n log n); simple nested sorts O(n^2).",
  },
];

function clone(value) {
  return JSON.parse(JSON.stringify(value));
}

export function listDsaPatternAtlas() {
  return clone(PATTERN_ATLAS);
}

export function buildDsaPatternDecisionTree() {
  return {
    title: "Pattern Identifier",
    subtitle: "A beginner path for choosing the first pattern to try before coding.",
    steps: clone(DECISION_STEPS),
  };
}

export function listDsaComplexityCheats() {
  return clone(COMPLEXITY_CHEATS);
}

export function listDsaVisualPlaygroundModules() {
  return clone(VISUAL_PLAYGROUND_MODULES);
}

export function buildDsaBigOChart() {
  return clone(BIG_O_CHART);
}

export function listDsaOperationComplexities() {
  return clone(OPERATION_COMPLEXITIES);
}
