// Canonical executable lessons: prompts, tests, code lines and traces share one definition.
export const EXECUTABLE_LESSONS = [
  { id: 'max', title: 'Maximum value', statement: 'Return the largest integer, or null for an empty array.', constraints: '0–100 safe integers. Null input is rejected. Duplicates and negative values are valid.', bruteForce: 'Sort a copy and read its final value: O(n log n) time and O(n) copy space.', improved: 'Scan once, retaining the largest value seen.', invariant: 'best is the maximum of the processed prefix, or null before the first item.', complexity: 'Each of n values is visited exactly once: O(n) time. One accumulator: O(1) auxiliary space.', code: ['let best = null;', 'for (const value of values) {', '  if (best === null || value > best) best = value;', '}', 'return best;'], tests: [{ input: [4, 1, 7, 3], output: 7 }, { input: [], output: null }, { input: [-5, -5, -9], output: -5 }], execute(values) { let best = null; const frames = [{ line: 1, index: -1, best }]; values.forEach((value, index) => { if (best === null || value > best) best = value; frames.push({ line: 3, index, value, best }); }); frames.push({ line: 5, index: values.length, best }); return { output: best, frames }; } },
  { id: 'duplicates', title: 'Contains duplicate', statement: 'Return true when any integer occurs more than once; otherwise return false.', constraints: '0–100 safe integers. No sorting assumed. Null input is rejected.', bruteForce: 'Compare each pair: n(n−1)/2 comparisons, O(n²) time and O(1) extra space.', improved: 'Check a set before inserting each value.', invariant: 'seen contains exactly the distinct values from earlier indices.', complexity: 'At most n membership checks and n insertions: expected O(n) time, O(n) auxiliary space.', code: ['const seen = new Set();', 'for (const value of values) {', '  if (seen.has(value)) return true;', '  seen.add(value);', '}', 'return false;'], tests: [{ input: [1, 2, 1], output: true }, { input: [], output: false }, { input: [-1, 0, 1, -1], output: true }], execute(values) { const seen = new Set(); const frames = [{ line: 1, index: -1, seen: [] }]; for (const [index, value] of values.entries()) { const duplicate = seen.has(value); frames.push({ line: 3, index, value, seen: [...seen], duplicate }); if (duplicate) return { output: true, frames }; seen.add(value); frames.push({ line: 4, index, value, seen: [...seen] }); } frames.push({ line: 6, index: values.length, seen: [...seen] }); return { output: false, frames }; } },
  { id: 'binary-search', title: 'Binary search', statement: 'Return any index whose value equals the target, or −1 when absent.', constraints: '0–100 safe integers sorted in nondecreasing order. Duplicate matches may return any matching index. Null input and unsorted arrays are rejected.', bruteForce: 'Scan all n values: O(n) time and O(1) space.', improved: 'Halve the inclusive search interval after comparing the midpoint.', invariant: 'If a match exists, at least one matching index is inside [low, high].', complexity: 'Each comparison halves the candidate interval: O(log n) time and O(1) auxiliary space.', code: ['let low = 0, high = values.length - 1;', 'while (low <= high) {', '  const mid = low + Math.floor((high - low) / 2);', '  if (values[mid] === target) return mid;', '  if (values[mid] < target) low = mid + 1;', '  else high = mid - 1;', '}', 'return -1;'], tests: [{ input: [1, 3, 5], target: 5, output: 2 }, { input: [], target: 4, output: -1 }, { input: [2, 2, 2], target: 3, output: -1 }], execute(values, target) { let low = 0; let high = values.length - 1; const frames = [{ line: 1, low, high }]; while (low <= high) { const mid = low + Math.floor((high - low) / 2); frames.push({ line: 3, low, high, mid, value: values[mid] }); if (values[mid] === target) { frames.push({ line: 4, low, high, mid }); return { output: mid, frames }; } if (values[mid] < target) { low = mid + 1; frames.push({ line: 5, low, high, mid }); } else { high = mid - 1; frames.push({ line: 6, low, high, mid }); } } frames.push({ line: 8, low, high }); return { output: -1, frames }; } },
];
export function runLesson(id, values, target = 0) {
  const lesson = EXECUTABLE_LESSONS.find(item => item.id === id);
  if (!lesson) throw new Error('Unknown lesson');
  if (!Array.isArray(values) || values.length > 100 || !values.every(Number.isSafeInteger)) throw new Error('Use a JSON array of at most 100 safe integers.');
  if (id === 'binary-search' && (!Number.isSafeInteger(target) || values.some((v, i) => i > 0 && v < values[i - 1]))) throw new Error('Binary search requires sorted input and a safe integer target.');
  return lesson.execute(values, target);
}
