const cause = (title, evidence, against, next) => ({ title, evidence, against, next });
const javaRef = (type) => ({ href: `https://docs.oracle.com/en/java/javase/21/docs/api/java.base/${type}.html`, title: `Java 21: ${type.split('/').at(-1)}` });
export const JAVA_SPRING_SYMPTOMS = [
  {
    slug: 'hashmap-entry-disappears', title: 'A HashMap entry exists, but get returns null', category: 'Collections', aliases: 'java missing lost vanished disappeared hashmap lookup key null cache',
    summary: 'Separate unstable key identity from missing entries and stored null values.', observations: 'Iteration sees an entry while lookup misses. Compare the exact key instance, equality fields, and stored value before blaming a collision.', firstStep: 'Record key hash/equality fields at insertion and lookup in a small test. Check containsKey with an equivalent immutable key.',
    causes: [cause('A key changed after insertion', 'Equality or hash fields differ between insertion and lookup.', 'The key is immutable and equivalent-key tests pass.', 'Use a stable ID; do not mutate identity while the key is stored.'), cause('equals and hashCode disagree', 'Equal instances produce different hash codes.', 'Equivalent instances have consistent hashes and lookups succeed.', 'Test equal, unequal, and collision cases against the key contract.'), cause('Null value or wrong lookup key', 'The map permits null values, or the lookup uses a different type/identifier.', 'The expected immutable key is present with a non-null value.', 'Distinguish absence with containsKey and inspect the producer of the key.')],
    fixture: 'MutableKey.java', expected: 'Mutable key lookup: null\nImmutable ID lookup: found', fixtureScope: 'JDK-only HashMap example. Demonstrates one mutable-key failure and a stable-ID repair; behavior after key mutation is not guaranteed for all Map implementations.',
    references: [javaRef('java/util/HashMap'), javaRef('java/util/Map')], related: [{ href: '/detective/the-vanishing-map-entry', title: 'Investigate the vanished entry' }],
  },
  {
    slug: 'transaction-does-not-roll-back', title: 'A Spring transaction does not roll back', category: 'Spring', aliases: 'spring transactional transaction rollback roll back annotation ignored committed self invocation proxy',
    summary: 'Verify the transaction boundary and rollback rule before changing annotations.', observations: 'A database change survives a failure. Check the actual transaction and connection involved; an external side effect is not part of a local database rollback.', firstStep: 'Trace the call through the injected bean, inspect transaction activity, and identify the exception that reaches the boundary.',
    causes: [cause('The call bypasses proxy advice', 'A same-object call or manually created object reaches the method without the proxy.', 'The call crosses the managed proxy and the expected transaction is active.', 'Move the boundary to an injected collaborator; verify with an integration test.'), cause('The rollback rule does not match', 'A checked exception escapes under default rules, or the application catches the failure.', 'An unchecked failure escapes and no override changes its rollback behavior.', 'Make the intended exception policy explicit and test commit as well as rollback.'), cause('The effect belongs to another boundary', 'A different manager, independent transaction, or remote API owns the surviving effect.', 'The effect is on the enlisted connection within the failing transaction.', 'Map resource ownership; use an outbox or compensation for cross-system effects.')],
    fixture: 'ProxyBoundary.java', expected: 'Self call intercepted: false\nExternal call intercepted: true', fixtureScope: 'A JDK dynamic-proxy model verifies self-invocation versus proxy entry. It does not run Spring, JDBC, rollback rules, or AspectJ weaving. The diagnosis assumes Spring proxy mode; verify the real bean and transaction manager in an integration test.',
    references: [{ href: 'https://docs.spring.io/spring-framework/reference/core/aop/proxying.html', title: 'Spring: proxy boundaries' }, { href: 'https://docs.spring.io/spring-framework/reference/data-access/transaction/declarative/rolling-back.html', title: 'Spring: rollback rules and configuration' }], related: [{ href: '/detective/the-rollback-that-never-happened', title: 'Investigate the missing rollback' }],
  },
  {
    slug: 'async-method-blocks-caller', title: 'A Spring @Async method still blocks its caller', category: 'Spring', aliases: 'spring async asynchronous synchronous blocking caller same thread self invocation executor future join get',
    summary: 'Separate advice bypass from executor policy and an immediate wait for the result.', observations: 'The caller does not return promptly. Thread names alone do not prove whether work was submitted; inspect submission, execution, and waiting separately.', firstStep: 'Trace the injected call, executor selection, and any Future.get or join in the caller.',
    causes: [cause('Async interception never runs', 'Local self-invocation or a non-managed object bypasses the configured interceptor.', 'The managed proxy submits the task to the expected executor.', 'Check async enablement and call through an injected collaborator.'), cause('The executor executes on the caller', 'A synchronous executor or caller-runs rejection policy handles this task.', 'A worker accepts the task and the caller is waiting elsewhere.', 'Inspect executor identity, saturation, queue bounds, and rejection behavior.'), cause('The caller waits immediately', 'A get or join follows submission on the request path.', 'The caller returns without waiting and latency is inside submission.', 'Decide whether the API can return asynchronously; do not hide a required result behind an annotation.')],
    fixture: 'ProxyBoundary.java', expected: 'Self call intercepted: false\nExternal call intercepted: true', fixtureScope: 'JDK proxy-boundary model only. It isolates self-invocation, not Spring async execution or scheduling. Spring proxy mode is assumed; AspectJ interception differs.',
    references: [{ href: 'https://docs.spring.io/spring-framework/reference/integration/scheduling.html', title: 'Spring: task execution and @Async' }], related: [{ href: '/build/java-dependency-injection', title: 'Build a container and inspect what it omits' }],
  },
  {
    slug: 'request-sees-previous-user', title: 'A request sees the previous user’s context', category: 'Concurrency', aliases: 'java spring wrong user tenant threadlocal thread local context leak stale reused worker',
    summary: 'Track context ownership across pooled threads, asynchronous work, and shared state.', observations: 'A request observes another request’s identity or tenant. Confirm the source of the value before assuming the authentication layer is wrong.', firstStep: 'Follow one context value from creation to cleanup, including error exits and thread changes, using synthetic identities.',
    causes: [cause('ThreadLocal survives worker reuse', 'A pooled worker retains a value after a task exits without remove.', 'Cleanup runs on that worker on every path before reuse.', 'Use a finally cleanup boundary; test two different requests on the same worker.'), cause('A singleton stores request state', 'A shared field is overwritten by overlapping requests.', 'Request-specific data is confined to independent objects.', 'Make request state explicit and keep shared services stateless where possible.'), cause('Async propagation uses stale data', 'A task captures or restores the wrong context across an executor boundary.', 'The captured context belongs to the current request and is cleared afterward.', 'Test capture, restore, and cleanup around both successful and failed tasks.')],
    fixture: 'ContextReuse.java', expected: 'Without cleanup: tenant-A\nAfter cleanup: null', fixtureScope: 'A single reused Java executor worker reproduces retained ThreadLocal context and cleanup. Synthetic tenant strings only; it does not exercise Spring Security context propagation.',
    references: [javaRef('java/lang/ThreadLocal')], related: [{ href: '/detective/the-report-from-another-tenant', title: 'Investigate a tenant-boundary failure' }],
  },
  {
    slug: 'concurrent-modification-single-thread', title: 'ConcurrentModificationException occurs on one thread', category: 'Collections', aliases: 'java concurrentmodificationexception cme iterator iteration list remove single thread',
    summary: 'An iterator can detect an invalid structural change without any second thread.', observations: 'A fail-fast iterator throws during traversal. This is a bug signal, not a reliable concurrent-access detector.', firstStep: 'Find every structural mutation between iterator creation and its next operation, including callbacks.',
    causes: [cause('The collection is changed outside its iterator', 'The loop calls collection.add or remove while retaining an iterator.', 'The iterator owns permitted removal and no other mutation occurs.', 'Use iterator.remove where supported, or collect changes and apply afterward.'), cause('A callback changes the same collection', 'A listener or helper mutates the collection during iteration.', 'Callbacks cannot reach the traversed collection.', 'Trace callback ownership and use a documented snapshot if appropriate.'), cause('Another task mutates shared state', 'Access is not confined or protected by one consistent policy.', 'Thread confinement is demonstrated for the full lifetime.', 'Choose synchronization or a concurrent collection with the required iteration semantics.')],
    fixture: 'IteratorMutation.java', expected: 'Direct mutation detected\nIterator removal leaves: [b]', fixtureScope: 'A deterministic single-thread ArrayList example. Fail-fast detection is best effort; never depend on the exception for synchronization.',
    references: [javaRef('java/util/ConcurrentModificationException')], related: [{ href: '/java/hashmap-vs-concurrenthashmap', title: 'Compare collection concurrency contracts' }],
  },
  {
    slug: 'heap-grows-after-requests', title: 'Java heap keeps growing after requests finish', category: 'Memory', aliases: 'java jvm heap memory leak oom outofmemory retained cache garbage collection gc grows growth',
    summary: 'Distinguish retained live objects from allocation bursts and non-heap memory.', observations: 'A rising heap graph alone does not prove a leak. Compare live-set trends under comparable load and account for warm-up.', firstStep: 'Correlate post-collection live data with load; inspect retaining paths and ownership of growing collections.',
    causes: [cause('A long-lived owner retains request objects', 'A cache, listener registry, or queue holds a growing set of otherwise finished objects.', 'Retained size reaches a stable bound and objects are released.', 'Define eviction or lifecycle cleanup and test the bound.'), cause('Allocation rate outpaces reclamation temporarily', 'The heap falls back after collection while allocation and pause activity spike.', 'Live data keeps increasing across comparable collections.', 'Profile allocation sites and object lifetime before increasing the heap.'), cause('The rising metric is not Java heap', 'RSS grows while heap live data is stable; direct buffers or native resources dominate.', 'Heap retention explains the process growth.', 'Separate heap, metaspace, thread stacks, and native allocations using the relevant runtime tools.')],
    fixture: 'RetainedRequests.java', expected: 'Retained requests: 100\nAfter lifecycle cleanup: 0', fixtureScope: 'A bounded Java object-retention example, not an OutOfMemoryError or a GC timing benchmark. Removing this owner’s references does not prove immediate reclamation.',
    references: [{ href: 'https://docs.oracle.com/en/java/javase/21/troubleshoot/troubleshooting-memory-leaks.html', title: 'JDK 21: diagnosing memory leaks' }], related: [{ href: '/explain-log/blocked-pool-thread-dump', title: 'Inspect a queueing-related artifact' }],
  },
  {
    slug: 'null-pointer-only-some-requests', title: 'NullPointerException occurs for only some requests', category: 'Java basics', aliases: 'java spring nullpointerexception npe null missing optional field unboxing request payload',
    summary: 'Find the absent value and the violated input contract before adding blanket null guards.', observations: 'The same endpoint succeeds for most requests. Compare the failing field path and permitted absence rules, not just the top stack frame.', firstStep: 'Build a minimal synthetic failing input and locate the exact dereference or unboxing operation.',
    causes: [cause('An optional value is auto-unboxed', 'A boxed Boolean or number is null at an operation requiring a primitive.', 'The boxed value is present on the failing path.', 'Decide whether absence is invalid or has an explicit default; test both.'), cause('A nested input or lookup result is absent', 'A missing field or unsuccessful lookup reaches code that assumes a value.', 'Boundary validation guarantees the value for this execution path.', 'Validate the actual contract and preserve the distinction between missing and empty.'), cause('An object bypasses intended initialization', 'A manually constructed object lacks a dependency expected from application wiring.', 'The object is fully constructed with mandatory dependencies.', 'Use explicit constructor requirements and test the real wiring path.')],
    fixture: 'NullableInput.java', expected: 'Null unboxing detected\nExplicit absent-as-false policy: false', fixtureScope: 'JDK-only boxed-Boolean example. The default is a stated teaching policy, not a universal fix for invalid inputs; no Spring request binding is exercised.',
    references: [javaRef('java/lang/NullPointerException')], related: [{ href: '/explain-log/null-profile-stack-trace', title: 'Decode a null-profile stack trace' }],
  },
];
