export const JAVA_DEBUGGING_LESSONS = [
  { id: "overflow", title: "Integer overflow", symptom: "A correct-looking sum becomes negative or wraps around.", rule: "Promote before arithmetic: (long) a + b; use long for counts, distances, and products.", drill: "Test values near Integer.MAX_VALUE and print intermediate types." },
  { id: "comparator", title: "Unsafe comparators", symptom: "Sorting fails only for very large positive and negative values.", rule: "Use Integer.compare(a, b) or Comparator.comparingInt; never return a - b.", drill: "Sort [-2_000_000_000, 2_000_000_000] and verify the order." },
  { id: "deque", title: "Queue direction errors", symptom: "BFS visits nodes in the wrong order or throws on an empty queue.", rule: "Use ArrayDeque, addLast/removeFirst for BFS, and check isEmpty before removing.", drill: "Trace the frontier after each level on a four-node graph." },
  { id: "visited", title: "Late visited marking", symptom: "A graph enqueues duplicates or loops forever.", rule: "Mark a node visited when scheduling it, not only after removing it.", drill: "Add a cycle and count how many times each node enters the queue." },
  { id: "recursion", title: "Stack overflow", symptom: "A deep tree or graph crashes despite correct logic.", rule: "Prefer iterative DFS/BFS with ArrayDeque when depth can approach n.", drill: "Replace recursive traversal with an explicit stack and parent tracking." },
  { id: "aliasing", title: "Shared mutable rows", symptom: "Updating one matrix row changes every row.", rule: "Allocate each row independently; do not fill a 2D array with one shared array reference.", drill: "Mutate [0][0] and assert [1][0] is unchanged." },
  { id: "bounds", title: "Off-by-one boundaries", symptom: "The solution misses the first/last item or throws on an empty input.", rule: "Choose inclusive or half-open intervals once and write the invariant beside the loop.", drill: "Run empty, one-item, exact-boundary, and one-past-boundary cases." },
  { id: "input", title: "Slow input and output", symptom: "An O(n) solution times out on large data.", rule: "Use BufferedInputStream/FastScanner and batch output with StringBuilder.", drill: "Compare Scanner with buffered parsing on 200,000 integers." },
];
