import { createProductionBlog, createProductionChapters } from "./productionBlogFactory.mjs";

const topics = [
  { title: "Requests, limits, and scheduling", lesson: "A request reserves placement capacity; a limit constrains runtime use. Choose both from measured workload demand, not a copied YAML value.", diagram: "deployment → requests → scheduler placement → limits → throttling or OOM behavior", example: "requests: capacity needed to place\nlimits: maximum runtime budget", avoid: "Avoid assuming a CPU limit and a memory limit fail in the same way." },
  { title: "Startup, readiness, and liveness", lesson: "Startup protects slow initialization, readiness controls traffic admission, and liveness restarts a stuck process. Each probe must answer only its own question.", diagram: "startup succeeds → readiness admits traffic\nliveness failure → restart; readiness failure → remove from service", example: "startup: can initialization finish?\nreadiness: can this instance serve now?", avoid: "Avoid making liveness depend on a transient downstream service." },
  { title: "Graceful termination", lesson: "A pod should stop accepting new work, finish or safely abandon bounded in-flight work, and release its owned resources before its termination deadline.", diagram: "drain signal → readiness false → in-flight owner reaches safe point → process exits", example: "terminate = stopAdmission(); awaitOwnersUntil(deadline); close();" },
  { title: "Autoscaling from the right signal", lesson: "Scale on the constrained resource or backlog, not merely average CPU. A queue-backed worker often needs lag and age alongside compute usage.", diagram: "workload signal → HPA decision → replicas → measure queue age and latency", example: "scale signal = queue age + bounded CPU", avoid: "Avoid scaling faster than dependency, database, or node capacity can support." },
  { title: "Multi-tenant cluster boundaries", lesson: "Namespaces, service accounts, RBAC, quotas, and network policy give teams bounded ownership. They do not replace application-level tenant authorization.", diagram: "team namespace → service account + RBAC → quota → workload boundary", example: "namespace policy = least privilege + finite shared capacity" },
  { title: "Safe deployment and rollback", lesson: "A rollout is a controlled production experiment. Gate promotion on readiness, error rate, latency, saturation, and business correctness, then keep a known-good revision ready.", diagram: "new revision → small cohort → user signals → promote or rollback", example: "gate = errors, p99, saturation, correctness" },
];
export const KUBERNETES_CHAPTERS = createProductionChapters(topics);
export const KUBERNETES_BLOG = createProductionBlog({ id: "kubernetes-java-production", title: "Kubernetes for Production Java Services", category: "Cloud-native Java", sourceUrl: "https://kubernetes.io/docs/setup/production-environment/", summary: "A practical course on running Java services safely on Kubernetes: resource budgets, probes, graceful shutdown, autoscaling, multi-team boundaries, and reversible rollouts.", chapters: KUBERNETES_CHAPTERS, capstone: { title: "Capstone: Deploy a checkout service safely", scenario: "A Java checkout service starts slowly, calls payment and inventory, and sees burst traffic during promotions.", steps: ["Set resource requests and limits from measured capacity, then define startup, readiness, and liveness probes.", "Drain requests and bound in-flight work during termination; separate local readiness from remote dependency health.", "Canary the new revision with latency, error, saturation, and business-success gates before promotion."], outcome: "A Kubernetes deployment that protects capacity and fails predictably without hiding user impact." } });
