import { createProductionBlog, createProductionChapters } from "./productionBlogFactory.mjs";

const topics = [
  { title: "Define the task contract", lesson: "Describe the user outcome, permitted tools, data boundary, failure behavior, and escalation path before optimizing a prompt or selecting a model.", diagram: "user task → model/tool contract → bounded action → verifiable outcome", example: "contract includes allowed actions and fallback" },
  { title: "Build an evaluation dataset", lesson: "Use representative successful, adversarial, ambiguous, and historical cases with a known expected property. Keep sensitive production data out unless the handling policy allows it.", diagram: "real task classes → curated cases → expected properties → evaluation run", example: "dataset changes are versioned" },
  { title: "Choose graders that match the risk", lesson: "Use deterministic checks for structured output and policy boundaries; use calibrated human or model-based grading only where judgment is necessary.", diagram: "output → schema/policy checks → quality grader → release decision", example: "hard failure before subjective score" },
  { title: "Evaluate retrieval separately", lesson: "Measure whether the right evidence was retrieved before judging the generated answer. A fluent unsupported answer is not a retrieval success.", diagram: "question → retrieval → evidence coverage → grounded answer → citation check", example: "retrieval recall and answer support are separate" },
  { title: "Constrain tool use and data flow", lesson: "Validate tool arguments, apply least privilege, make writes idempotent, and require confirmation for external effects. Treat prompts and retrieved text as untrusted input.", diagram: "untrusted input → policy + validation → constrained tool → audited outcome", example: "tool parameters are allowlisted and typed" },
  { title: "Gate change and monitor drift", lesson: "Compare candidates against a baseline with risk-weighted thresholds, canary high-impact changes, and monitor failure classes after release.", diagram: "baseline eval → candidate eval → canary → production feedback → next dataset", example: "regression gate protects known failures" },
];
export const LLM_EVALS_CHAPTERS = createProductionChapters(topics);
export const LLM_EVALS_BLOG = createProductionBlog({ id: "production-llm-evals-guardrails", title: "Production LLM Evaluation and Guardrails", category: "AI engineering", sourceUrl: "https://platform.openai.com/docs/api-reference/evals", summary: "A practical course on task contracts, evaluation datasets, graders, retrieval quality, tool safety, and regression gates for LLM-powered systems.", chapters: LLM_EVALS_CHAPTERS, capstone: { title: "Capstone: Ship a support copilot safely", scenario: "A support assistant retrieves internal guidance and can draft but not directly submit customer actions.", steps: ["Define permitted capabilities, constrained tool schemas, data boundaries, and the escalation path for uncertainty.", "Build a versioned evaluation set spanning grounded answers, missing evidence, prompt injection, and tool misuse.", "Gate model and prompt changes against a baseline, then canary with user feedback and failure-class monitoring."], outcome: "An LLM feature that improves through measured evaluation without turning fluent output into unreviewed authority." } });
