export const MULTITHREADING_BLOG = {
  id: 'java-multithreading-production',
  title: 'Java Multithreading: Correctness, Cancellation, and Production Interviews',
  category: 'Java multithreading',
  javaRelease: 17,
  summary: 'A deep Java 17 course on memory visibility, atomic state changes, lock ownership, bounded executors, cancellation, virtual-thread trade-offs, and real-world interview answers.',
  lessons: [
    'Start from an invariant and the ownership of shared state; choose a concurrency primitive only after that.',
    'Treat interruption, timeout, and cancellation as requests that need a cooperative safe point and a durable outcome.',
    'Use bounded admission, lifecycle ownership, and operational evidence so concurrency protects latency instead of hiding overload.',
  ],
  sections: [
    { heading: 'Course goal', body: 'Build Java services that remain correct when requests race, workers are interrupted, dependencies stall, and a process drains. Each chapter pairs a precise guarantee with the production limit it does not provide.' },
    { heading: 'Java 17 production lens', body: 'Examples compile on Java 17 and use standard-library types. Virtual threads are covered as an architectural decision for Java 21+; they lower per-thread waiting cost but do not make database connections, CPU, rate limits, or external systems unbounded.' },
  ],
  example: 'shared invariant → happens-before / atomic transition → bounded execution → cooperative cancellation → observable outcome',
  interviewQuestions: [
    'Which invariant does this code protect, and which threads can change it?',
    'What establishes visibility and atomicity here—and what does not?',
    'What happens if a timeout, cancellation, or process shutdown races with normal completion?',
  ],
  interviewQa: [
    { question: 'When is volatile enough, and when is it not?', answer: 'volatile is enough for publishing a simple independently written flag or reference when readers need visibility and ordering. It does not make read-modify-write, check-then-act, or several fields atomic. Use an atomic operation, a lock, or immutable replacement when the invariant spans a transition.' },
    { question: 'How do you stop a running task safely?', answer: 'Cancellation is cooperative. Request interruption, make blocking operations interruptible or time-bounded, check interruption at safe points, restore the interrupt flag when propagating, and let the task owner commit, roll back, close resources, and publish one terminal outcome. Do not release resources merely because the caller stopped waiting.' },
    { question: 'Why can a CompletableFuture timeout still leave work running?', answer: 'orTimeout completes the future exceptionally; it does not universally interrupt the underlying action or cancel downstream I/O. The executor, client, and task need a shared deadline and cancellation contract. Otherwise late work can still consume capacity or perform a side effect after the caller has received a timeout.' },
    { question: 'How would you size a thread pool?', answer: 'Start with the bounded downstream capacity, request deadline, blocking ratio, CPU budget, and queue/rejection policy—not core count alone. Measure queue age, active workers, rejected work, dependency saturation, and p95/p99. A larger pool can amplify a slow database or remote dependency.' },
    { question: 'Do virtual threads remove the need for pools and backpressure?', answer: 'No. They make many blocking tasks practical, but shared resources remain finite. Bound database connections, HTTP concurrency, memory, CPU-heavy work, request admission, and fan-out. Check library behavior and pinning risks, then measure the real bottleneck.' },
    { question: 'How do you debug a suspected deadlock or starvation incident?', answer: 'Capture several thread dumps or JFR events, identify lock owners and wait cycles, correlate executor queue age and active counts with request traces, and inspect the dependency being waited on. Fix the ordering, ownership, or bounded-admission rule; avoid treating a thread dump as proof without the workload timeline.' },
  ],
  practice: 'Design a payment-authorisation fan-out that has a 700 ms deadline, a bounded database pool, a cancellable remote call, one idempotent completion record, and a shutdown policy.',
  capstone: {
    title: 'Capstone: Keep a concurrent checkout correct under a dependency stall',
    scenario: 'Two requests try to reserve the last item while a tax provider stalls. One caller times out, a deployment begins draining, and a delayed worker resumes after the replacement has finished the operation.',
    steps: [
      'State the inventory invariant, choose the atomic or transactional owner, and show the exact duplicate, stale, and reordered transitions the owner rejects.',
      'Set an end-to-end deadline, bounded executor or virtual-thread admission policy, database and remote-call limits, and the cooperative cancellation safe points.',
      'Record one durable operation identity and terminal outcome; test simultaneous reservations, interruption, timeout, rejected admission, drain, and a late completion before measuring queue age and tail latency.',
    ],
    outcome: 'Produce a concurrency design that preserves one inventory outcome per operation while making overload, cancellation, stale ownership, and recovery visible to users and operators.',
  },
};

export const MULTITHREADING_CHAPTERS = [
  { title: '1. Define shared-state ownership and happens-before', lesson: 'A concurrency primitive is not the design; the invariant and its owner are. Prefer immutable snapshots and confine mutable state to one thread where possible. When state crosses threads, establish a happens-before edge through thread start/join, monitor release/acquire, a volatile write/read, a successful atomic operation, or a concurrent collection contract. Publishing a partially initialized object or assuming time creates visibility is unsafe.', whenToUse: 'Use explicit safe publication whenever one thread constructs state and another reads it.', avoid: 'Avoid exposing mutable objects before construction completes or relying on sleep, logging, or a nonvolatile flag for visibility.', diagram: 'construct immutable snapshot → publish through happens-before → reader observes complete state\nno publication edge → stale/default observation is permitted', example: 'import java.util.concurrent.atomic.AtomicReference;\nfinal class SafePublicationExample {\n  record Config(String region, int limit) {\n    Config { if (region == null || region.isBlank() || limit < 1) throw new IllegalArgumentException(); }\n  }\n  private final AtomicReference<Config> current = new AtomicReference<>(new Config("default", 1));\n  void replace(Config next) { current.set(java.util.Objects.requireNonNull(next, "config")); }\n  Config read() { return current.get(); }\n}', exercise: 'Choose which fields of a mutable order summary must become immutable or be guarded before a second worker may read it.', quiz: 'What guarantee does safe publication give a reader of an immutable snapshot?', answer: 'The reader sees the reference and the values established before the publication edge, so it does not observe a half-constructed snapshot. This does not make later multi-step business updates atomic; each replacement still needs an invariant and transition rule.' },
  { title: '2. Make check-then-act transitions atomic', lesson: 'A volatile counter can make the latest value visible while still losing increments because increment is read, add, write. When one decision depends on the current state, perform compare-and-set or hold a narrow lock around the whole transition. Include the expected version or operation identity so a late or duplicate completion cannot overwrite a newer decision. Do not split validation and update across unrelated synchronization boundaries.', whenToUse: 'Use CAS or a lock when a decision and state change must occur as one observable transition.', avoid: 'Avoid get-then-set sequences, separate synchronized methods, or reusing a completion identity for a different intent.', diagram: 'read AVAILABLE → CAS AVAILABLE→HELD → one winner\nloser reads HELD → reject/reload; stale completion → version mismatch', example: 'import java.util.concurrent.atomic.AtomicReference;\nfinal class AtomicReservationExample {\n  enum State { AVAILABLE, HELD, SOLD }\n  private final AtomicReference<State> state = new AtomicReference<>(State.AVAILABLE);\n  boolean reserve() { return state.compareAndSet(State.AVAILABLE, State.HELD); }\n  boolean confirm() { return state.compareAndSet(State.HELD, State.SOLD); }\n  State snapshot() { return state.get(); }\n}', exercise: 'Model a reservation that expires. Decide which transition owns expiry, how confirmation rejects an expired hold, and how an older worker is prevented from confirming a newer hold.', quiz: 'Why is compareAndSet safer than get followed by set for a last-item reservation?', answer: 'CAS verifies that the state is still the expected value at the same atomic boundary as the write. Only one contender can change AVAILABLE to HELD; a loser sees failure and must reload or return an explicit conflict instead of overwriting the winner.' },
  { title: '3. Use locks, conditions, and interruption with ownership', lesson: 'Use synchronized for simple, non-interruptible monitor ownership; use ReentrantLock when interruptible acquisition, timed acquisition, or conditions are required. Keep critical sections small and do not call slow remote systems while holding a lock. An InterruptedException is a cancellation signal: either propagate it or restore the interrupt flag after cleanup. The owner that acquired the lock or resource must release it in finally, not a watchdog that cannot prove the worker stopped.', whenToUse: 'Use an interruptible or timed lock when waiting must honor cancellation or a request deadline.', avoid: 'Avoid swallowing InterruptedException, calling blocking I/O under a lock, or unlocking from a thread that did not acquire the lock.', diagram: 'tryLock(remaining budget) → protected invariant → finally unlock\ninterrupt → cleanup safe point → propagate/restore → one owner releases', example: 'import java.util.concurrent.TimeUnit;\nimport java.util.concurrent.locks.ReentrantLock;\nfinal class InterruptibleLockExample {\n  private final ReentrantLock lock = new ReentrantLock();\n  boolean update(long waitMillis) throws InterruptedException {\n    if (waitMillis < 0) throw new IllegalArgumentException();\n    if (!lock.tryLock(waitMillis, TimeUnit.MILLISECONDS)) return false;\n    try { return true; } finally { lock.unlock(); }\n  }\n}', exercise: 'Rewrite a method that catches InterruptedException and continues its loop. State the safe cleanup point, the caller-visible outcome, and whether the interrupt is propagated or restored.', quiz: 'Why is swallowing interruption dangerous in a server?', answer: 'It erases a control signal used for deadlines, shutdown, and task cancellation. The task can keep holding locks, threads, connections, or permits after its owner believes it is stopping, turning graceful drain into delayed saturation or a stale write.' },
  { title: '4. Bound executors and own their lifecycle', lesson: 'An executor has worker count, queue capacity, admission rule, rejection behavior, task timeout contract, and shutdown owner. A bounded queue makes overload visible before memory and latency explode; the response may be rejection, defer, or caller-runs only when that behavior is safe for the calling thread. Submit through execute and handle RejectedExecutionException; queue and active-count snapshots cannot reserve capacity or predict shutdown. Shutdown must stop admission, let owned tasks reach a defined safe point, and preserve ambiguous side effects for reconciliation rather than assuming interrupt reversed them.', whenToUse: 'Use a bounded executor for finite CPU, blocking, or downstream capacity shared by requests.', avoid: 'Avoid unbounded queues, creating executors per request, or treating shutdownNow as proof that work did not run.', diagram: 'request → bounded queue → worker → safe completion → terminal outcome\nfull → explicit reject/defer; drain → stop admission → finish/record UNKNOWN', example: 'import java.util.concurrent.*;\nfinal class BoundedExecutorExample {\n  static ThreadPoolExecutor create() {\n    return new ThreadPoolExecutor(2, 2, 0, TimeUnit.MILLISECONDS,\n      new ArrayBlockingQueue<>(2), new ThreadPoolExecutor.AbortPolicy());\n  }\n  // Use with the AbortPolicy configured by create(). True means accepted,\n  // not completed; task failures belong to the task owner.\n  static boolean tryExecute(ThreadPoolExecutor executor, Runnable task) {\n    try { executor.execute(task); return true; }\n    catch (RejectedExecutionException rejected) { return false; }\n  }\n}', exercise: 'Choose worker, queue, rejection, and drain behavior for thumbnail generation that shares CPU with checkout. State the user response and the metric that proves the policy is protecting checkout.', quiz: 'Why is an unbounded executor queue not a harmless default?', answer: 'It converts finite worker or dependency capacity into growing memory and queue age. Requests can expire before execution but still run later, consume resources, and hide the overload signal needed to shed or defer safely.' },
  { title: '5. Compose async work without orphaning cancellation', lesson: 'CompletableFuture is a completion graph, not automatic structured ownership. Pass a common deadline into each client, keep cancellation and timeout semantics explicit, map failures at the boundary, and avoid blocking join on the same saturated executor that must run its continuations. A timeout result does not prove a remote write failed. For Java 21+, virtual threads simplify thread-per-task blocking code, but fan-out and downstream resources still need bounds and a parent-owned cancellation policy.', whenToUse: 'Use async composition for independent work when you can state the parent deadline, failure policy, and resource limits.', avoid: 'Avoid calling join while occupying a worker needed by the dependency, treating orTimeout as universal cancellation, or launching unowned background work.', diagram: 'parent deadline → child A + child B → combine outcome\nchild timeout → cancel request → child reaches safe point / reconcile ambiguous effect', example: 'import java.util.concurrent.*;\nfinal class FutureBoundaryExample {\n  static CompletableFuture<String> combine(CompletableFuture<String> left, CompletableFuture<String> right) {\n    return left.thenCombine(right, (a, b) -> a + ":" + b);\n  }\n  static String outcome(Throwable failure) {\n    return failure == null ? "COMPLETE" : "RECONCILE_OR_FAIL";\n  }\n}', exercise: 'Design a profile-and-entitlements fan-out. Name the shared deadline, which result can degrade, which must fail the request, and what late result must not overwrite after the parent returns.', quiz: 'Why can a future timeout leave capacity consumed?', answer: 'The future can complete with timeout while its underlying task, socket read, or provider command continues unless every layer cooperates with cancellation and deadlines. That late work may still hold a worker or create an ambiguous side effect.' },
  { title: '6. Test schedules and diagnose evidence, not luck', lesson: 'Sleep-based concurrency tests are probabilistic. Use latches, barriers, controlled executors, injected clocks, and bounded waits to force the schedule that exposes a race. In production, correlate thread dumps or JFR lock/park events with executor active/queue/rejected counts, request traces, dependency latency, and CPU. Deadlock needs a wait cycle; starvation may instead be a full pool, blocked queue, or tasks waiting for work on their own executor.', whenToUse: 'Use deterministic schedule control for races, cancellation, queue saturation, and shutdown tests.', avoid: 'Avoid declaring a race fixed because it did not reproduce once, or diagnosing deadlock from one blocked thread without a cycle.', diagram: 'barrier releases contenders → deterministic race → asserted one winner\nincident signals → dumps/JFR + queues + traces → ownership hypothesis → targeted fix', example: 'import java.util.concurrent.CountDownLatch;\nfinal class DeterministicRaceExample {\n  static void await(CountDownLatch latch) throws InterruptedException {\n    if (!latch.await(1, java.util.concurrent.TimeUnit.SECONDS)) throw new AssertionError("schedule timeout");\n  }\n  static int winners(boolean first, boolean second) { return (first ? 1 : 0) + (second ? 1 : 0); }\n}', exercise: 'Write a deterministic test for two reservations arriving together and a third completion arriving late. Identify the barrier point and the exact final invariant.', quiz: 'What evidence distinguishes a deadlock from executor starvation?', answer: 'A deadlock has a cycle of threads each waiting for a lock or resource held by another in the cycle. Starvation may show no cycle: all workers can be occupied by slow work, queued tasks, or a downstream wait. Queue age, worker states, lock ownership, and dependency traces separate them.' },
  { title: '7. Answer production interview questions with a failure trace', lesson: 'For a real-world concurrency question, lead with the invariant, ownership boundary, primitive, and a small failure trace. Then state cancellation, timeout, duplicate completion, stale ownership, resource release, overload behavior, and the metrics you would inspect. Say what the primitive does not guarantee: a lock does not make a remote call idempotent, a future timeout does not stop I/O, and virtual threads do not expand a database pool.', whenToUse: 'Use this answer structure for senior interviews, incident reviews, and code reviews involving concurrent state.', avoid: 'Avoid reciting primitive definitions without a shared-state invariant, failure path, or operational consequence.', diagram: 'invariant → owner → primitive → race/timeout trace → recovery → metric\nanswer proves behavior, not vocabulary', example: 'final class InterviewAnswerExample {\n  static String structure(String invariant, String owner, String recovery) {\n    if (invariant == null || owner == null || recovery == null) throw new IllegalArgumentException();\n    return invariant + " | owner=" + owner + " | recovery=" + recovery;\n  }\n}', exercise: 'Answer: “How would you make concurrent payment completion safe?” Include one idempotency identity, one atomic owner, the lost-response outcome, cancellation behavior, and three signals you would alert on.', quiz: 'What makes a concurrency interview answer production-ready rather than theoretical?', answer: 'It connects a stated invariant to an ownership and synchronization boundary, walks through a realistic race or failure, preserves the resource and side-effect outcome under cancellation or retry, and names evidence that would confirm the design in production.' },
];
