import { createHmac, randomBytes, timingSafeEqual } from "node:crypto";
const PROVIDERS = { github: { client: "GITHUB_CLIENT_ID", secret: "GITHUB_CLIENT_SECRET", authorize: "https://github.com/login/oauth/authorize", token: "https://github.com/login/oauth/access_token", scope: "read:user user:email" }, google: { client: "GOOGLE_CLIENT_ID", secret: "GOOGLE_CLIENT_SECRET", authorize: "https://accounts.google.com/o/oauth2/v2/auth", token: "https://oauth2.googleapis.com/token", scope: "openid email profile" } };
const appSecret = () => process.env.SESSION_SECRET || process.env.APP_ENCRYPTION_KEY || "";
export function providerConfig(provider) { const config = PROVIDERS[provider]; return config && process.env[config.client] && process.env[config.secret] ? config : null; }
export function oauthState(provider, nonce) { const payload = `${provider}.${nonce}`; return `${payload}.${createHmac("sha256", appSecret()).update(payload).digest("hex")}`; }
export function verifyOAuthState(value) { const [provider, nonce, signature] = String(value || "").split("."); if (!providerConfig(provider) || !nonce || !signature) return null; const expected = createHmac("sha256", appSecret()).update(`${provider}.${nonce}`).digest("hex"); return Buffer.byteLength(signature) === Buffer.byteLength(expected) && timingSafeEqual(Buffer.from(signature), Buffer.from(expected)) ? provider : null; }
export function createOAuthNonce() { return randomBytes(24).toString("hex"); }
export function oauthRedirectUri(provider) { return `${String(process.env.APP_BASE_URL || process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000").replace(/\/$/, "")}/api/auth?action=oauth-callback&provider=${provider}`; }
export function authorizationUrl(provider, state) { const config = providerConfig(provider); if (!config) return ""; const params = new URLSearchParams({ client_id: process.env[config.client], redirect_uri: oauthRedirectUri(provider), response_type: "code", scope: config.scope, state }); return `${config.authorize}?${params}`; }
export async function exchangeOAuthCode(provider, code) { const config = providerConfig(provider); if (!config || !code) throw new Error("OAuth provider is not configured"); const tokenResponse = await fetch(config.token, { method: "POST", headers: { Accept: "application/json", "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ client_id: process.env[config.client], client_secret: process.env[config.secret], code, redirect_uri: oauthRedirectUri(provider), grant_type: "authorization_code" }) }); const token = await tokenResponse.json(); if (!tokenResponse.ok || !token.access_token) throw new Error("OAuth token exchange failed"); const headers = { Authorization: `Bearer ${token.access_token}`, Accept: "application/json" }; const response = await fetch(provider === "github" ? "https://api.github.com/user" : "https://openidconnect.googleapis.com/v1/userinfo", { headers }); const profile = await response.json(); if (!response.ok || !(profile.id || profile.sub)) throw new Error("OAuth profile is incomplete"); let email = profile.email; if (provider === "github" && !email) { const emailsResponse = await fetch("https://api.github.com/user/emails", { headers }); const emails = await emailsResponse.json(); email = emails.find((item) => item.primary && item.verified)?.email || emails.find((item) => item.verified)?.email; } if (!email) throw new Error("OAuth email is unavailable"); return { provider, subject: String(profile.id || profile.sub), email, firstName: profile.given_name || String(profile.name || "").split(" ")[0], lastName: profile.family_name || String(profile.name || "").split(" ").slice(1).join(" ") }; }
