import { createProductionBlog, createProductionChapters } from "./productionBlogFactory.mjs";

const topics = [
  { title: "Choose a collector topology", lesson: "Direct export is simple; agents offload local work; gateways centralize policy. Choose the smallest topology that meets scale, security, and operational requirements.", diagram: "service SDK → agent → gateway → telemetry backend", example: "agent handles local collection; gateway handles shared policy" },
  { title: "Preserve trace and metric semantics", lesson: "Trace-aware routing keeps a trace together for tail sampling. Metric streams need one writer to avoid inconsistent or out-of-order data.", diagram: "trace ID routing → one gateway owner\nmetric stream → one writer", example: "route spans by trace identity" },
  { title: "Bound collector memory and queues", lesson: "Collectors need memory limits, batching, sending queues, and retry policies sized for an explicit outage window. An unbounded buffer is delayed data loss.", diagram: "receiver → memory limiter → batch → sending queue → exporter", example: "queue capacity follows outage budget" },
  { title: "Decide telemetry durability", lesson: "In-memory queues reduce transient loss; persistent storage or a message broker protects selected critical hops at the cost of complexity and recovery work.", diagram: "critical signal → persistent queue/WAL → retryable export → backend", example: "choose loss budget per signal" },
  { title: "Secure the pipeline", lesson: "Treat telemetry as potentially sensitive. Authenticate collectors, constrain receivers, redact data before export, and protect credentials at gateway boundaries.", diagram: "instrumentation → redact → authenticated collector → backend", example: "never export secrets or raw credentials" },
  { title: "Operate the observability system", lesson: "Monitor collector queue depth, send failures, dropped data, memory pressure, and backend latency. A telemetry outage must itself be observable.", diagram: "collector internal metrics → alert → capacity or policy change → verify", example: "signal pipeline has its own SLO" },
];
export const OTEL_COLLECTOR_CHAPTERS = createProductionChapters(topics);
export const OTEL_COLLECTOR_BLOG = createProductionBlog({ id: "opentelemetry-collector-production", title: "Operating OpenTelemetry Collectors at Scale", category: "Observability platform", sourceUrl: "https://opentelemetry.io/docs/collector/deploy/other/agent-to-gateway/", summary: "A production course on collector topology, trace and metric ownership, buffering, durability, security, and operational feedback.", chapters: OTEL_COLLECTOR_CHAPTERS, capstone: { title: "Capstone: Build a resilient telemetry pipeline", scenario: "A multi-cluster Java platform needs traces, metrics, and logs while one backend can be slow or unavailable.", steps: ["Choose direct, agent, gateway, or agent-to-gateway topology per workload and trust boundary.", "Set memory, batching, queue, retry, and selected durable storage policies from an outage and loss budget.", "Prove trace routing, metric single-writer behavior, redaction, and collector recovery with failure tests."], outcome: "A telemetry architecture that remains useful during the incidents it is meant to diagnose." } });
