import { createProductionBlog, createProductionChapters } from "./productionBlogFactory.mjs";

const topics = [
  { title: "Classify the migration", lesson: "Separate additive, backfill, behavioral, and destructive changes. The class determines compatibility, rollout order, and whether rollback remains possible.", diagram: "compatibility class → expand → migrate → verify → contract", example: "add nullable field before code requires it" },
  { title: "Expand before contract", lesson: "Make schema changes that old and new code can both tolerate, deploy compatible readers and writers, then remove old behavior only after measured adoption.", diagram: "additive schema → mixed versions → adoption evidence → removal", example: "old reader ignores optional field; new reader uses it" },
  { title: "Backfill under load", lesson: "Backfill in bounded, resumable batches with a stable cursor and rate limit. Do not let historical work consume the capacity needed by live traffic.", diagram: "checkpoint → bounded batch → commit → observe → next checkpoint", example: "cursor + batch limit + sleep policy" },
  { title: "Logical replication cutover", lesson: "Fence and drain all old writers, record the final source position, and verify the subscriber has applied it before promotion. Logical replication does not copy schema DDL or sequence state: apply compatible DDL separately and synchronize every relevant sequence before opening target writes. Budget and rehearse the write pause; zero downtime is not guaranteed.", diagram: "fence source → apply final position → verify DDL and sequences → open target writes", example: "one authoritative writer during transition", avoid: "Avoid dual writes without a clear authority and reconciliation plan." },
  { title: "Verify before switching traffic", lesson: "Compare record counts, hashes, business totals, lag, and representative reads before a cutover. A healthy process is not proof of equivalent data.", diagram: "old result + new result → comparison → gate → traffic shift", example: "verify keys, totals, and freshness" },
  { title: "Rollback and recovery", lesson: "Before target writes, a verified reversal may return to the source. After target commits, the source is stale: fence target writes and reconcile or reverse-replicate committed changes before returning authority. Without a rehearsed return path, recover forward or keep writes paused.", diagram: "target commits → fence target → reconcile changes → verify source → reopen source", example: "rollback preserves committed data and one writer" },
];
export const POSTGRES_MIGRATION_CHAPTERS = createProductionChapters(topics);
export const POSTGRES_MIGRATION_BLOG = createProductionBlog({ id: "postgres-zero-downtime-migrations", title: "Near-Zero-Downtime PostgreSQL Migrations and Logical Replication", category: "PostgreSQL operations", sourceUrl: "https://www.postgresql.org/docs/current/logical-replication-restrictions.html", summary: "A production guide to compatible schema changes, bounded backfills, logical replication, and controlled cutover. A rehearsed write pause and explicit recovery gates protect correctness; uninterrupted writes are not guaranteed.", chapters: POSTGRES_MIGRATION_CHAPTERS, capstone: { title: "Capstone: Move a large order table safely", scenario: "A busy order service needs a schema redesign and a near-zero-downtime move to a new PostgreSQL cluster.", steps: ["Classify every schema and application change; apply compatible DDL on both clusters and release the expand phase first.", "Use one coordinated initial-copy and change-stream boundary; do not independently backfill the same rows that subscription initialization copies. Compare business totals at aligned boundaries.", "Fence and drain every source writer, verify the final applied position, synchronize all relevant sequences, and validate data before opening target writes.", "Rehearse reversal before target commits and reconciliation or reverse replication after target commits. Do not route back to a stale source."], outcome: "A migration plan that can prove data correctness before it changes ownership." } });
