// Original course; protocol traces are illustrative, not deployable server code.
export const REALTIME_BLOG = {
  id: "real-time-communication-patterns",
  title: "Real-Time Communication: Polling, SSE, WebSockets, and Webhooks",
  category: "System design",
  summary: "Design a live delivery tracker by choosing communication direction, freshness, replay, and failure behavior before choosing a transport.",
  lessons: ["Start with a freshness and delivery contract.", "Choose browser updates and backend notifications independently.", "Make reconnects, duplicates, and slow consumers part of the design."],
  sections: [
    { heading: "One product, several communication needs", body: "A parcel tracker needs occasional status refreshes, a live driver map, dispatcher commands, and carrier callbacks. These do not need one universal protocol. This original tutorial uses that product to compare four mechanisms and the state each must retain." },
    { heading: "Example scope", body: "Chapters contain labeled protocol and failure traces, not complete networking implementations. The final example is a standalone Node.js 20+ replay model: copy it to replay.mjs and run node replay.mjs. It tests cursor behavior without a server, browser, database, or network; it does not prove durable delivery." },
    { heading: "Further reading", body: "Protocol references: WHATWG SSE (https://html.spec.whatwg.org/multipage/server-sent-events.html), RFC 6455 (https://www.rfc-editor.org/rfc/rfc6455), and Stripe webhook guidance (https://docs.stripe.com/webhooks). Verify protocol behavior against the applicable specification; the parcel scenarios, diagrams, and exercises here are original." },
  ],
  example: "Carrier → durable inbox → parcel state → event log → browser\nDispatcher → command API → authorization → parcel state",
  interviewQuestions: ["Why might a tracking dashboard use SSE while its carrier integration uses webhooks?", "What happens when a returning client's cursor predates retained history?", "Does reconnecting a WebSocket recover messages lost during disconnection?"],
  practice: "Design a delivery tracker for 50,000 viewers; state freshness, connection, replay, and overload budgets.",
  capstone: { title: "Capstone: Keep a parcel tracker correct through disconnects", scenario: "A carrier retries a callback, the live gateway restarts, and a customer returns after replay history expires. Dispatchers must still submit commands safely.", steps: ["Choose a transport for each edge and calculate request and connection load from a stated freshness target.", "Draw the durable inbox, parcel transaction, event log, live gateways, and snapshot-with-cursor recovery path. Define tenant authorization at every boundary.", "Test duplicate callbacks, restart during delivery, expired cursors, revoked access, and a slow browser. Set queue limits, reconnect jitter, monitoring, and deployment drain rules."], outcome: "Produce a diagram and failure table that preserve parcel state while making stale views and recovery visible." },
};

export const REALTIME_CHAPTERS = [
  {
    title: "1. Start with freshness and direction",
    lesson: "Write down who initiates updates, who receives them, and how stale the display may be. A tracking summary updated within 30 seconds may use ordinary polling. A driver map with a one-second target needs a different budget. Neither requirement says that every intermediate coordinate must be retained: current position is replaceable state, while a delivered transition is business history. Separate those contracts before sizing the system.",
    whenToUse: "Use periodic polling when bounded staleness is acceptable and request volume is affordable.",
    avoid: "Avoid persistent connections solely because the product is called real-time; also avoid rapid polling without a capacity estimate.",
    walkthrough: "Assume 50,000 active viewers polling every 10 seconds with staggered starts. The average is 5,000 requests per second even with no changes. If update arrivals are uniform relative to polls, average detection delay is about five seconds, before network and processing time.",
    diagram: "Freshness target → request budget → direction → recovery contract → transport",
    example: "Capacity worksheet (illustrative):\nviewers = 50,000; interval = 10 seconds\nrequests/second = 50,000 / 10 = 5,000\naverage polling delay ≈ interval / 2 = 5 seconds\nSynchronized clients can still create much larger bursts.",
    exercise: "Recalculate for a 30-second interval and explain whether a one-second freshness target can be met.",
    practiceProblems: "Compare a shipment summary, live map, and dispatcher console; specify which updates may be coalesced.",
    quiz: "Does switching to a persistent connection remove capacity costs?",
    answer: "No. It can reduce repeated request overhead but introduces open connections, buffers, heartbeats, fan-out, and reconnect bursts. Size these separately from event production rate.",
  },
  {
    title: "2. Long polling with a replay cursor",
    lesson: "A long-poll request returns available updates after a cursor or waits until an update or a bounded deadline. After processing the response the client issues another request. Retain events across that gap: a new event must not disappear just because no request is currently waiting. The server also needs an atomic check-and-wait or a recheck after waiter registration, otherwise an event can arrive between reading history and subscribing. Set the server wait below the proxy and client deadlines and release waiters on cancellation.",
    whenToUse: "Use for modest update rates when ordinary HTTP request infrastructure is a good fit.",
    avoid: "Avoid unbounded held requests or a design that dedicates scarce worker threads to every idle viewer.",
    walkthrough: "The browser receives event 71. Event 72 arrives before its next request. A retained cursor query returns 72 immediately instead of waiting for event 73.",
    diagram: "GET after=70 → wait or read history → event 71\nclient applies 71 → GET after=71 → retained event 72",
    example: "Application protocol trace (not an HTTP standard):\nGET /parcels/P9/updates?after=70&waitSeconds=20\n200 {events:[{id:71,status:OUT_FOR_DELIVERY}],cursor:71}\nGET /parcels/P9/updates?after=71&waitSeconds=20\n200 {events:[],cursor:71}  // bounded wait elapsed\nNetwork failure: retry the same cursor with capped backoff + jitter.",
    exercise: "Describe the server response when cursor 71 is older than retained history. Define an explicit reset response and snapshot flow.",
    practiceProblems: "Trace an event in the request gap, a canceled wait, and a reconnect burst.",
    quiz: "Should an empty timeout response advance the cursor?",
    answer: "Not in this contract. No new event was supplied. Keep the last applied cursor; advancing it could skip updates. A server-defined watermark is a different contract and needs explicit semantics.",
  },
  {
    title: "3. SSE for a live read model",
    lesson: "Server-Sent Events carry UTF-8 event records on an HTTP response with Content-Type text/event-stream. A blank line terminates each record. Native EventSource reconnects and can send Last-Event-ID; this only supplies a resume hint. The server still owns retention and replay. Receiving an ID does not prove the application persisted its effect. Send dispatcher commands through a separate authenticated API. Test streaming through the actual proxy: buffering can turn timely writes into delayed batches.",
    whenToUse: "Use for a browser view that mostly receives updates, such as parcel status or job progress.",
    avoid: "Avoid assuming EventSource provides arbitrary request headers, application acknowledgments, or durable replay automatically.",
    walkthrough: "Send event 72, disconnect, and reconnect with Last-Event-ID: 72. If 73 is retained, replay it. If history expired, explicitly tell the application to fetch a consistent snapshot and reopen from its cursor.",
    diagram: "Browser GET → event stream\nServer → event 72 → event 73 → browser\nDisconnect → Last-Event-ID → replay or reset",
    example: "SSE wire example (blank lines matter):\nContent-Type: text/event-stream\n\nid: 72\nevent: parcel\ndata: {\"parcelId\":\"P9\",\"status\":\"OUT_FOR_DELIVERY\"}\n\n: heartbeat\n\n",
    exercise: "Define a reset event that closes the stream, reloads an authorized snapshot, and resumes without racing new writes.",
    practiceProblems: "Test proxy buffering, expired sessions, and closing EventSource when the reader unmounts.",
    quiz: "Is Last-Event-ID proof that a business action completed?",
    answer: "No. It tracks stream reception, not an application transaction. Use the stream for a replaceable view or add an explicit acknowledgment and durable processing contract where effects matter.",
  },
  {
    title: "4. WebSockets for interactive commands",
    lesson: "WebSockets support messages in both directions over an established connection. In the HTTP/1.1 handshake, the client requests an upgrade and the server accepts with status 101; other HTTP versions have their own mechanisms. A socket preserves message order within a connection, not a durable history across reconnects. Define command IDs, acknowledgments, validation, and replay at the application layer. Authenticate connections, validate browser origins, and authorize each parcel subscription and command. Recheck access when sessions expire or permissions change.",
    whenToUse: "Use when both sides frequently initiate low-latency messages, such as a dispatcher coordinating drivers.",
    avoid: "Avoid using a socket as a substitute for command idempotency, persistence, or per-resource authorization.",
    walkthrough: "A dispatcher sends command C8. The server commits it, then disconnects before the acknowledgment arrives. Resending C8 must return the original result rather than issue the instruction twice.",
    diagram: "Dispatcher → command C8 → authorized handler\nCommitted result → acknowledgment → dispatcher\nLost acknowledgment → resend C8 → same result",
    example: "Application message trace (illustrative JSON):\nclient: {type:command, commandId:C8, parcelId:P9, action:HOLD}\nserver: {type:ack, commandId:C8, result:ACCEPTED}\nreconnect: {type:resume, after:72}\nserver: {type:event, id:73, parcelId:P9, status:HELD}\nThe server persists command outcomes independently of socket lifetime.",
    exercise: "Decide which messages can be dropped under overload: location samples, hold commands, or acknowledgments. Justify each policy.",
    practiceProblems: "Trace lost acknowledgments, reconnect to a different gateway, and unauthorized subscriptions.",
    quiz: "Does TCP ordering guarantee exactly-once command execution?",
    answer: "No. A disconnect can hide an already committed result. A stable command ID and atomic result storage protect retries; ordering on one connection does not settle ambiguous outcomes.",
  },
  {
    title: "5. Webhooks at the backend boundary",
    lesson: "A carrier webhook is an HTTP callback to your backend, not a channel to an offline browser. Treat delivery guarantees as provider-specific. Verify requests using the provider's signing contract and unchanged request bytes before trusting their contents. Apply timestamp tolerance where the contract supports it. Persist accepted events durably before acknowledging; then process them asynchronously. A unique provider-and-event identity plus transactional state changes can suppress duplicate local effects. External effects still need an outbox and a downstream idempotency contract.",
    whenToUse: "Use for backend integrations where another service initiates occasional event notifications.",
    avoid: "Avoid acknowledging after only an in-memory enqueue, or trusting delivery order to determine parcel state.",
    walkthrough: "The inbox commit succeeds but the success response is lost. A repeated callback finds the existing inbox record. Processing can resume from durable state without applying the delivery transition twice.",
    diagram: "Carrier POST → verify → durable inbox → acknowledge\nInbox worker → transaction: deduplicate + update + outbox → publish",
    example: "Failure trace (transaction design, not executable SQL):\n1. Verify signature; reject invalid requests.\n2. Insert inbox(provider, eventId, payload) under a unique key.\n3. Commit inbox, then return success.\n4. Worker atomically updates parcel state, records processing, and writes outbox.\n5. Crash before step 4 commit: retry. Crash after commit: stored state prevents reapply.",
    exercise: "An older IN_TRANSIT callback arrives after DELIVERED. Choose an authoritative version rule or reconciliation strategy.",
    practiceProblems: "Test duplicate delivery, invalid signatures, reordered events, and a crash after inbox commit.",
    quiz: "Why is a separate check-then-record deduplication sequence unsafe?",
    answer: "Two workers can both pass the check, or a crash can separate the effect from the record. Enforce uniqueness and commit the processing marker with the local effect. For remote effects, use a stable idempotency key or reconciliation.",
  },
  {
    title: "6. Replay, fan-out, and bounded recovery",
    lesson: "Separate durable parcel history from live gateways that own connections. A broker can route events to the correct gateway, but transient pub/sub alone does not recover missed messages. Keep a replay source and create snapshots paired with a consistent cursor. Bound per-client buffers: coalesce replaceable coordinates, or disconnect slow clients and require resynchronization. Add reconnect jitter and drain connections during deployments. Track active connections, buffer size, delivery lag, replay resets, and reconnect rate without unbounded user-ID metric labels.",
    whenToUse: "Use a shared replay contract when clients reconnect across multiple gateway instances.",
    avoid: "Avoid infinite history, unlimited client queues, or replaying another tenant's events based only on a supplied cursor.",
    walkthrough: "In the model, snapshot cursor 12 includes all state through 12. Resume after 11 returns event 12; resume after 9 requires a snapshot because events before 11 have expired. Resuming from a future cursor also resets instead of waiting indefinitely.",
    diagram: "Durable event log → live gateway → bounded client buffer\nReconnect → retained cursor? → replay\nExpired or future cursor → consistent snapshot → resume",
    exampleRuntime: "Node.js 20+; standalone deterministic model",
    example: "import assert from 'node:assert/strict';\nconst snapshot = { cursor: 12, status: 'DELIVERED' };\nconst retained = [\n  { id: 11, status: 'OUT_FOR_DELIVERY' },\n  { id: 12, status: 'DELIVERED' },\n];\nfunction resume(cursor) {\n  const floor = retained[0].id - 1;\n  if (!Number.isSafeInteger(cursor) || cursor < floor || cursor > snapshot.cursor) {\n    return { kind: 'reset', snapshot };\n  }\n  return { kind: 'events', events: retained.filter(e => e.id > cursor) };\n}\nassert.deepEqual(resume(11).events.map(e => e.id), [12]);\nassert.deepEqual(resume(12).events, []);\nassert.equal(resume(9).kind, 'reset');\nassert.equal(resume(13).kind, 'reset');\nassert.equal(resume(NaN).kind, 'reset');\nconsole.log('Replay boundaries passed');",
    exercise: "Extend the model with duplicate event reception and a bounded client buffer; keep the last applied cursor monotonic.",
    practiceProblems: "Test the oldest valid cursor, an expired cursor, a future cursor, and reconnect to another gateway.",
    quiz: "What must a snapshot cursor mean to prevent a recovery gap?",
    answer: "The snapshot represents all relevant state through that cursor under one consistent boundary. Replay then starts strictly after it. Reading state and cursor independently can skip a write between those reads.",
  },
];
