const GUIDE_SEEDS = [
  ["python", "python-interview-questions", "Python Backend Interview Questions: A Practical Study Guide", "Structured Python interview answers covering data structures, concurrency, APIs, testing, and production trade-offs.", "Python", ["Start with Python's data model and explain the invariant before the syntax.", "Choose built-in collections by access pattern and state time and space complexity.", "For services, discuss timeouts, validation, observability, and failure behavior."], "Python interview answers should connect language behavior to a backend decision. Explain the mechanism, show a small example, then name the production trade-off.", "python interview questions"],
  ["react", "react-hooks-interview-questions", "React Hooks Interview Questions and Answers", "Clear React Hooks interview explanations for useEffect, useMemo, state ownership, rendering, and performance.", "React", ["Separate render-time calculation from effects that synchronize with an external system.", "Keep state at the lowest owner that needs it and make data flow explicit.", "Measure rerenders before optimizing with memoization or transitions."], "A strong React answer starts with the render model: components derive UI from props and state, while effects synchronize with systems outside React. Then explain dependency and ownership choices.", "react hooks interview questions"],
  ["nodejs", "nodejs-backend-interview-questions", "Node.js Backend Interview Questions and Answers", "Prepare for Node.js backend interviews with event-loop mechanics, async errors, streams, APIs, and scaling trade-offs.", "Node.js", ["Explain event-loop occupancy and keep blocking CPU work out of request handlers.", "Propagate async errors and cancellation explicitly across boundaries.", "Bound streams, queues, payloads, and concurrency before optimizing throughput."], "Node.js services are event-driven: the key interview invariant is keeping the event loop available while asynchronous work is in flight. Pair every performance claim with a bounded resource and failure path.", "nodejs backend interview questions"],
  ["go", "go-concurrency-interview-questions", "Go Concurrency Interview Questions: Goroutines, Channels, and Context", "Learn how to discuss Go goroutines, channels, context cancellation, races, and production-safe concurrency.", "Go", ["Give each goroutine an owner, lifetime, and cancellation path.", "Use channels for clear ownership transfer; use mutexes for protected shared state.", "Bound workers and always close or drain resources deliberately."], "Go concurrency is about ownership and lifetime as much as syntax. A good answer says who creates work, who cancels it, how backpressure works, and how a race would be detected.", "go concurrency interview questions"],
  ["rust", "rust-ownership-interview-questions", "Rust Ownership and Borrowing Interview Questions", "Structured Rust interview answers covering ownership, borrowing, lifetimes, traits, errors, and safe concurrency.", "Rust", ["State which component owns a value and how long a borrow must remain valid.", "Use Result and Option to make failure and absence explicit at the boundary.", "Prefer message passing or synchronized ownership over unsafe shared mutation."], "Rust's ownership model makes resource lifetime and mutation rules explicit. Explain the ownership transfer first, then show how borrowing or a trait keeps the design safe without runtime garbage collection.", "rust ownership interview questions"],
  ["aws", "aws-system-design-interview", "AWS System Design Interview: Services, Reliability, and Trade-offs", "A practical AWS system design interview guide covering compute, storage, queues, networking, resilience, and cost.", "AWS", ["Start with scale, SLOs, data ownership, and failure domains before naming AWS services.", "Map each finite resource to a limit, alarm, retry budget, and recovery action.", "State consistency, security, observability, and cost trade-offs explicitly."], "AWS system design answers are strongest when services follow requirements. Draw the request path, identify failure boundaries, then justify each managed service by its operational contract.", "aws system design interview"],
  ["docker", "docker-interview-questions", "Docker Interview Questions and Answers for Backend Engineers", "Prepare for Docker interviews with images, containers, networking, security, health checks, and delivery practices.", "Docker", ["Treat the image as an immutable artifact and verify the exact digest in production.", "Keep runtime images minimal, non-root, reproducible, and observable.", "Separate build-time dependencies from runtime dependencies and test the packaged image."], "Docker packages a process and its runtime contract. Interview answers should cover image construction, startup, signals, networking, resource limits, and what happens when the container fails.", "docker interview questions"],
  ["mongodb", "mongodb-interview-questions", "MongoDB Interview Questions: Modeling, Indexes, and Consistency", "Structured MongoDB interview preparation covering document modeling, indexes, transactions, sharding, and operations.", "MongoDB", ["Model around query and update patterns rather than tables copied from a relational design.", "Use indexes deliberately and measure selectivity, working set, and write amplification.", "Define consistency, retry, and idempotency behavior for each workflow."], "MongoDB design starts with access patterns and document boundaries. Explain what is embedded, what is referenced, how indexes support real queries, and which consistency promise users receive.", "mongodb interview questions"],
  ["sql", "sql-interview-questions", "SQL Interview Questions and Answers for Backend Engineers", "A structured SQL interview guide covering joins, indexes, transactions, isolation, query plans, and pagination.", "SQL", ["Translate the business request into predicates, joins, ordering, and invariants.", "Read the actual execution plan and compare estimated versus actual rows.", "Choose isolation, constraints, and indexes together, then measure write cost."], "A strong SQL answer begins with the invariant and the access path. Explain the query shape, the plan the database should choose, and the concurrency behavior that preserves correctness.", "sql interview questions"],
];

export const PUBLIC_STACK_GUIDES = GUIDE_SEEDS.map(([stack, slug, title, description, label, steps, body, keyword]) => ({ stack, slug, title, description, label, steps, body, keyword, reviewedAt: "2026-09-03", author: "InterviewIQ Editorial Team" }));

export function getStackGuide(stack, slug) { return PUBLIC_STACK_GUIDES.find((guide) => guide.stack === String(stack || "").toLowerCase() && guide.slug === String(slug || "").toLowerCase()) || null; }
