import { createProductionBlog, createProductionChapters } from "./productionBlogFactory.mjs";

const topics = [
  { title: "Make builds reproducible", lesson: "A release must identify the source revision, dependency resolution, builder, and inputs that produced it. Reproducibility makes investigation and rollback credible.", diagram: "source revision + pinned inputs → controlled build → immutable image", example: "release points to commit and image digest" },
  { title: "Generate an SBOM", lesson: "A software bill of materials records components in an artifact so teams can assess exposure and license or policy impact after release.", diagram: "build → SBOM attestation → image registry → vulnerability decision", example: "SBOM describes the artifact, not only the repository" },
  { title: "Record build provenance", lesson: "Provenance explains how an image was built and which inputs participated. It helps distinguish a trusted rebuild from an unknown artifact.", diagram: "builder identity + inputs → provenance → attached image metadata", example: "provenance follows the immutable digest" },
  { title: "Sign and verify artifacts", lesson: "Verification gates should act on immutable digests and trusted identities, not mutable tags or a claim in a deployment manifest.", diagram: "signed digest → admission policy → trusted runtime deployment", example: "verify before promotion" },
  { title: "Turn vulnerabilities into decisions", lesson: "A finding needs artifact scope, exploitability context, owner, remediation window, and a safe exception process—not a silent scan result.", diagram: "SBOM + advisory → affected digest → owner decision → patch or accepted exception", example: "prioritize reachable, exposed risk" },
  { title: "Promote safely", lesson: "Promote the same verified artifact across environments and retain the evidence needed to roll it back. Rebuilding at promotion time creates a different release.", diagram: "verified digest → canary → production → rollback to known digest", example: "promote, do not rebuild" },
];
export const SUPPLY_CHAIN_CHAPTERS = createProductionChapters(topics);
export const SUPPLY_CHAIN_BLOG = createProductionBlog({ id: "java-container-supply-chain-security", title: "Java Container Supply-Chain Security", category: "Software supply-chain security", sourceUrl: "https://docs.docker.com/build/metadata/attestations/", summary: "A practical guide to reproducible Java container builds, SBOMs, provenance, verification, vulnerability decisions, and safe promotion.", chapters: SUPPLY_CHAIN_CHAPTERS, capstone: { title: "Capstone: Gate a Spring service release", scenario: "A Spring service ships as a container image and must prove what was built before it can reach production.", steps: ["Produce an immutable image digest with SBOM and provenance attestations.", "Verify signer and provenance at a promotion gate, then connect advisories to the precise affected digest.", "Promote the verified digest through a canary and retain a known-good digest for rollback."], outcome: "A release process that makes artifact identity, policy, and recovery evidence explicit." } });
