const concept = (name, explanation) => ({ name, explanation });
const diagram = (title, description, nodes, edges) => ({ title, description, nodes, edges });

export const SYSTEM_DESIGN_VISUAL_GUIDE = {
  title: "50 System Design Concepts, Seen Clearly",
  description: "An original visual field guide to the choices behind systems that remain fast, correct, and operable as they grow.",
  sections: [
    {
      id: "foundation", eyebrow: "01 · Begin with the service contract", title: "Foundations: decide what good means before drawing boxes",
      body: "The first ten concepts establish the language for a design discussion. Use them to turn a vague product request into a measurable, user-visible contract.",
      takeaway: "State the workload, user promise, and first constraint before choosing infrastructure.",
      concepts: [
        concept("Scalability", "The ability to absorb more users, data, or work while preserving the stated service contract."), concept("Availability", "The share of time a useful response can be delivered; define what useful means during a partial failure."), concept("Latency", "The elapsed time one user experiences from request to response; tail latency matters most to users."), concept("Throughput", "The amount of completed work per unit time; it can rise even when individual requests take longer."), concept("SLO", "A target for a user-visible outcome, such as successful reads within a latency threshold."), concept("Error budget", "The permitted amount of SLO failure that makes reliability and delivery trade-offs explicit."), concept("Capacity planning", "Estimate peak requests, payloads, retention, and growth before capacity is urgently needed."), concept("Load balancer", "A traffic distributor that selects healthy, eligible instances and protects them with admission limits."), concept("CDN", "A geographically distributed cache for public, cacheable bytes that reduces origin load and distance."), concept("DNS", "The naming layer that maps a service name to an endpoint; caching makes routing changes deliberately slow."),
      ],
      diagrams: [
        diagram("From user need to operating contract", "A product request becomes measurable constraints, then an architecture and proof signals. The order prevents fashionable infrastructure from driving the design.", [["need", "User need", "Share a photo quickly"], ["contract", "Success contract", "p95 under 250 ms; durable upload"], ["design", "Design choices", "CDN, object store, async work"], ["proof", "Evidence", "latency, failures, queue age"]], [[0, 1, "clarify"], [1, 2, "constrain"], [2, 3, "measure"]]),
        diagram("Latency and throughput are different questions", "Parallel work can raise total completed work while queues and dependencies increase the time one request waits. Measure both before changing a limit.", [["arrive", "Requests arrive", "Peak traffic"], ["admit", "Bounded admission", "Protect capacity"], ["work", "Parallel work", "Finite concurrency"], ["outcome", "User outcome", "Latency + success rate"]], [[0, 1, "admit or reject"], [1, 2, "execute"], [2, 3, "complete"]]),
      ],
    },
    {
      id: "data", eyebrow: "02 · Make data ownership explicit", title: "Data: choose the truth, then manage copies carefully",
      body: "Most architecture trade-offs become data trade-offs. These concepts help decide what owns a fact, which reads can be stale, and how growth changes the data path.",
      takeaway: "Name the authoritative write, the allowed freshness, and the recovery path for every important record.",
      concepts: [
        concept("Relational database", "A structured store with transactions and relationships; a strong fit when invariants cross records."), concept("NoSQL database", "A family of stores optimized for particular data shapes or access paths, not a universal scalability upgrade."), concept("ACID transaction", "A unit that commits all protected local changes or none, preserving an owned business invariant."), concept("Index", "A maintained access structure that speeds selective reads while adding write cost and storage use."), concept("Replication", "Copies data to improve read capacity or failure tolerance, with a deliberate plan for lag and failover."), concept("Sharding", "Splits data and write work across independent partitions when one owner cannot meet the required capacity."), concept("Partition key", "The routing value that should distribute traffic while keeping the records needed by one invariant together."), concept("Consistency model", "The promise about what a read can observe after a write, chosen per operation rather than by slogan."), concept("Cache", "A faster copy used only under an explicit freshness and invalidation policy; it is not the source of truth."), concept("Cache invalidation", "The mechanism that prevents an older copy from being presented as current after authoritative state changes."),
      ],
      diagrams: [
        diagram("A read path has one authority", "The application may return a permitted fresh cache value. On a miss it reads the source of truth and validates what it stores for later requests.", [["client", "Client", "Read with deadline"], ["app", "Application", "Authorize + policy"], ["cache", "Cache", "Fresh permitted value?"], ["store", "Source of truth", "Durable read on miss"]], [[0, 1, "request"], [1, 2, "lookup"], [2, 3, "miss only"]]),
        diagram("Partitions distribute ownership, not just rows", "A stable key routes each write to one owning partition. Rebalancing changes placement and requires capacity, verification, and a safe movement plan.", [["key", "Tenant key", "Stable routing value"], ["router", "Partition router", "Select an owner"], ["owner", "Owning shard", "Write + local invariant"], ["replica", "Read replica", "Optional stale read"]], [[0, 1, "hash or range"], [1, 2, "route"], [2, 3, "replicate"]]),
      ],
    },
    {
      id: "async", eyebrow: "03 · Move deferred work safely", title: "Asynchronous systems: separate acceptance from completion",
      body: "Queues are excellent for work that can happen later, but they shift the problem into delivery, duplicates, ordering, and recovery. These concepts make that shift explicit.",
      takeaway: "Every asynchronous command needs a durable identity, a terminal outcome, and a safe replay story.",
      concepts: [
        concept("Message queue", "A durable buffer that decouples producers from consumers and smooths bursts within a bounded operating policy."), concept("Idempotent consumer", "A handler that returns the same business effect when the same event is delivered again."), concept("Delivery guarantee", "The defined loss or duplication behavior across a boundary; at-least-once delivery requires deduplication."), concept("Ordering", "A promise usually limited to a key or partition, not every message in a distributed system."), concept("Transactional outbox", "A record committed with local state and relayed later, closing the gap between a write and event publication."), concept("Dead-letter queue", "A durable holding path for messages that cannot safely progress, with ownership and replay criteria."), concept("Backpressure", "A signal that work is arriving faster than it can finish, prompting bounded admission, slowing, or shedding."), concept("Retry policy", "A finite, classified attempt plan with jitter and an overall deadline; it never makes an unsafe command safe."), concept("Saga", "A distributed workflow of local steps and explicit compensations instead of one impossible cross-service transaction."), concept("Batch processing", "A bounded set of work with checkpointing and restart semantics, designed separately from an interactive request."),
      ],
      diagrams: [
        diagram("Durable state before background work", "The application commits state and an outbox record together. A relay publishes later; consumers deduplicate their side effect if delivery repeats.", [["command", "Command", "Stable operation identity"], ["commit", "Local commit", "State + outbox together"], ["relay", "Relay", "Publish; repeats possible"], ["consumer", "Consumer", "Deduplicate + apply effect"]], [[0, 1, "validate"], [1, 2, "after commit"], [2, 3, "at least once"]]),
        diagram("Backpressure prevents a queue from hiding overload", "An intake limit protects the durable queue. Consumers report lag and failures. The system slows or rejects noncritical work before recovery becomes impossible.", [["intake", "Incoming work", "Finite admission"], ["queue", "Durable queue", "Track age + depth"], ["worker", "Bounded worker", "Finite concurrency"], ["policy", "Overload policy", "Slow, shed, or defer"]], [[0, 1, "accept"], [1, 2, "claim"], [2, 3, "saturation signal"]]),
      ],
    },
    {
      id: "reliability", eyebrow: "04 · Contain partial failure", title: "Reliability: preserve useful work when dependencies misbehave",
      body: "A remote dependency can slow, fail, or answer ambiguously. The following concepts keep one unhealthy component from consuming the rest of the system.",
      takeaway: "A timeout is a caller decision, not evidence that the downstream operation stopped.",
      concepts: [
        concept("Timeout budget", "A finite amount of time shared across a request path, with each child call receiving only the remaining budget."), concept("Circuit breaker", "A state machine that temporarily refuses calls after measured failures to preserve local capacity."), concept("Bulkhead", "A separate pool, queue, or permit limit that prevents one dependency from exhausting all shared resources."), concept("Load shedding", "An explicit decision to reject or defer lower-value work when capacity is exhausted."), concept("Health check", "A signal about whether an instance can serve its intended work; readiness should reflect dependencies it truly requires."), concept("Failover", "A controlled switch to another healthy owner or region, with clear state, routing, and data-freshness assumptions."), concept("Graceful degradation", "A smaller but honest user experience when a noncritical capability is unavailable."), concept("Disaster recovery", "The tested ability to restore service and data within stated recovery time and recovery point objectives."), concept("Fault injection", "A controlled experiment that verifies user impact, containment, alerts, and recovery—not only exception handling."), concept("Observability", "Logs, metrics, and traces that connect a user symptom to an actionable, evidence-backed decision."),
      ],
      diagrams: [
        diagram("A failure boundary preserves the rest of the system", "A request has one deadline. Admission and a child timeout protect capacity. A classified failed dependency reaches a safe retry, degradation, or rejection policy.", [["deadline", "Caller deadline", "Finite time budget"], ["bulkhead", "Bounded admission", "Separate capacity"], ["dependency", "Remote dependency", "Timeout + outcome"], ["fallback", "Safe outcome", "Retry, degrade, or reject"]], [[0, 1, "reserve time"], [1, 2, "call"], [2, 3, "classify"]]),
        diagram("Recovery closes the loop", "An alert begins an investigation; evidence supports a bounded mitigation. The team measures the user contract again, then promotes or rolls back.", [["alert", "User symptom", "Latency, error, or stale data"], ["evidence", "Evidence", "Trace + metric + log"], ["change", "Bounded change", "Canary with rollback"], ["verify", "Verify", "Promote or restore"]], [[0, 1, "investigate"], [1, 2, "support cause"], [2, 3, "measure again"]]),
      ],
    },
    {
      id: "evolution", eyebrow: "05 · Keep change safe", title: "Evolution and operations: systems must be secure and changeable",
      body: "A design is incomplete if it cannot evolve without breaking callers, leaking data, or turning an ordinary release into a recovery event. The final concepts make ownership and safe change visible.",
      takeaway: "The strongest design ends with who owns the change, what proves it is safe, and how it is reversed.",
      concepts: [
        concept("API gateway", "An edge boundary for identity, routing, admission, and composition; domain authorization remains with the owning service."), concept("Authentication", "Verification of who or what is calling; a valid identity is not permission to perform every action."), concept("Authorization", "A decision at the resource-owning boundary based on principal, action, tenant, resource, and state."), concept("Encryption and secrets", "Protection for data and credentials in transit and at rest, with references rather than secret values in configuration or logs."), concept("Multi-tenancy", "A data and authorization boundary that prevents one customer’s request or record from crossing into another’s scope."), concept("Schema evolution", "An additive, compatible path for data and event shapes while old and new consumers coexist."), concept("Data migration", "A verifiable movement of historical state plus changes after the snapshot, with comparison and rollback criteria."), concept("Canary deployment", "A small, measured traffic slice used to test a release against the current user contract before wider exposure."), concept("Cost model", "The capacity, storage, network, and operations cost tied to the workload rather than to a technology label."), concept("Runbook", "An owned, executable response path that connects an alert to evidence, mitigation, verification, and escalation."),
      ],
      diagrams: [
        diagram("Identity is verified before owned data is touched", "The edge validates credentials and carries trusted identity. The owning service authorizes the action against the loaded resource and tenant before reading or changing state.", [["client", "Client", "Untrusted request"], ["edge", "Gateway", "Validate identity"], ["service", "Owning service", "Authorize resource + tenant"], ["data", "Owned data", "Read or change after approval"]], [[0, 1, "request"], [1, 2, "trusted identity"], [2, 3, "authorized access"]]),
        diagram("Safe change is evidence-led and reversible", "A compatible change starts dark, then reaches a controlled canary. Contract and user signals determine whether to promote or restore the known-good version.", [["prepare", "Prepare", "Compatible contract + rollback"], ["canary", "Canary", "Small traffic cohort"], ["evidence", "Evidence", "Correctness + user metrics"], ["decision", "Decision", "Promote or roll back"]], [[0, 1, "deploy"], [1, 2, "measure"], [2, 3, "gate"]]),
      ],
    },
  ],
};
