import { SUPPLEMENTAL_DIAGRAMS, SUPPLEMENTAL_OVERVIEWS } from "./techBlogSupplementalDiagrams.mjs";
import { LEARNING_DIAGRAMS } from './learningDiagrams.mjs';
import { PRODUCTION_DIAGRAMS, PRODUCTION_WORKSHOPS } from './productionBlogWorkshops.mjs';
// Explicit editorial assignments. Diagram selection never infers behavior from category words.
export const COURSE_DIAGRAMS = {
  ...SUPPLEMENTAL_DIAGRAMS,
  ...LEARNING_DIAGRAMS,
  ...PRODUCTION_DIAGRAMS,
  observeSignals: {
    title: "A slow checkout: connect three signals",
    description: "A latency metric reveals that checkout is slow across requests. A trace locates the slow payment call within one request. A log correlated with that trace explains a payment timeout. Together they support a hypothesis; no individual signal alone proves the root cause.",
    nodes: [["metric",20,30,"Metric: checkout p99","Aggregate latency rises"],["trace",275,30,"Trace: payment span","Locate time in one request"],["log",530,30,"Log: timeout event","Correlate using trace ID"]],
    edges: [["metric","trace","investigate"],["trace","log","correlate"]],
  },
  observeSpans: {
    title: "One request owns several child spans",
    description: "The inbound order request is the parent span. Database access and payment calls are separate child spans with their own durations and outcomes. The parent-child relationship shows ownership, not sequential execution or equal duration.",
    nodes: [["request",275,30,"POST /orders","Parent request span"],["sql",20,210,"Database query","Child span + outcome"],["payment",530,210,"Payment call","Child span + duration"]],
    edges: [["request","sql","parent of"],["request","payment","parent of"]],
  },
  observeContext: {
    title: "Carry context across the message boundary",
    description: "The producer injects trace context into message metadata. The consumer extracts that context and starts its processing span. The consumer relationship can be a parent or a link according to the messaging instrumentation; message delivery alone does not propagate execution context.",
    nodes: [["producer",20,30,"Producer span","Current trace context"],["message",275,30,"Message metadata","Injected trace context"],["consumer",530,30,"Consumer span","Extract; parent or link"]],
    edges: [["producer","message","inject"],["message","consumer","extract"]],
  },
  observeCardinality: {
    title: "Metric labels multiply time series",
    description: "Ten route templates combined with five status values produce up to fifty label combinations for one metric. Adding one thousand user IDs increases this to fifty thousand combinations. Histogram buckets can multiply the stored series further; use traces or controlled logs for individual request details.",
    nodes: [["routes",20,30,"10 route templates","Use /orders/{id}"],["status",275,30,"5 status values","10 × 5 = 50 combinations"],["users",530,30,"1,000 user IDs","50 × 1,000 = 50,000"]],
    edges: [["routes","status","multiply"],["status","users","unbounded growth"]],
  },
  observeSampling: {
    title: "Redact before export; sample deliberately",
    description: "Remove secrets and sensitive payloads at instrumentation boundaries before telemetry leaves the process. A tail-sampling collector can select from the traces it actually receives, using errors, latency, or a baseline policy. It cannot recover spans dropped earlier by head sampling, and its buffering and capacity limits must be measured.",
    nodes: [["app",20,30,"Application telemetry","Remove sensitive values"],["collector",275,30,"Tail-sampling collector","Bounded trace buffering"],["store",530,30,"Retained traces","Errors, slow + baseline"]],
    edges: [["app","collector","redacted export"],["collector","store","policy decision"]],
  },
  observeRecovery: {
    title: "An alert ends with verified recovery",
    description: "An alert identifies a user symptom and owner. The runbook guides an evidence check before mitigation. After the change, compare user-facing latency and errors against the recovery target; escalate or roll back when that target is not met.",
    nodes: [["alert",20,30,"Alert + owner","Checkout latency high"],["evidence",275,30,"Runbook investigation","Trace + metric + log"],["mitigate",530,30,"Mitigate safely","Bounded change"],["verify",530,210,"Verify user outcome","Recover or roll back"]],
    edges: [["alert","evidence","investigate"],["evidence","mitigate","supported cause"],["mitigate","verify","measure again"]],
  },
  gatewayTrust: {
    title: "Gateway identity and service ownership",
    description: "The gateway removes untrusted identity headers and validates credentials. An authenticated hop carries trusted identity to the owning service, which checks the resource and tenant before reading or changing state. A valid identity alone cannot authorize another customer's booking.",
    nodes: [["client",20,20,"Client request","Untrusted headers"],["edge",275,20,"Gateway checks","Validate + strip spoofing"],["service",530,20,"Owning service","Check tenant + resource"],["state",530,190,"Owned booking state","Allow only after checks"]],
    edges: [["client","edge","request"],["edge","service","authenticated hop"],["service","state","authorized"]],
  },
  networkPath: {
    title: "One remote call crosses distinct network boundaries",
    description: "Resolve the service name, race eligible addresses within one budget, establish a transport connection, verify TLS identity, then exchange HTTP messages. A later phase cannot retroactively prove an earlier one, and transport completion does not by itself prove a business outcome.",
    height: 430,
    nodes: [["dns",20,20,"Resolve service name","Cached records + lifetime"],["race",275,20,"Race addresses","One bounded connect budget"],["connect",530,20,"Connect transport","Reachable peer socket"],["tls",20,210,"Verify TLS identity","Chain + time + hostname"],["http",275,210,"Exchange HTTP","Reuse or drain connection"],["outcome",530,210,"Classify outcome","Known result or UNKNOWN"]],
    edges: [["dns","race","addresses"],["race","connect","first success"],["connect","tls","begin TLS"],["tls","http","authenticated peer"],["http","outcome","response evidence"]],
  },
  featureFlag: {
    title: "A flag changes behavior, not authorization",
    description: "An authenticated boundary supplies a stable, minimized subject to versioned flag evaluation. One immutable request decision selects a renderer or route. The owning service separately authorizes the resource. A rollout rollback changes future evaluations; it cannot undo an already-completed durable effect.",
    height: 430,
    nodes: [["identity",20,20,"Authenticated boundary","Stable subject + allowed attributes"],["rule",275,20,"Versioned flag rule","Default, owner, expiry"],["decision",530,20,"Request decision","Variant + rule version"],["behavior",20,210,"Selected behavior","Renderer or reversible route"],["auth",275,210,"Resource authorization","Principal + owned resource"],["observe",530,210,"Signals and retirement","Bounded metrics + rollback"]],
    edges: [["identity","rule","trusted context"],["rule","decision","deterministic evaluation"],["decision","behavior","immutable for request"],["identity","auth","authenticated principal"],["auth","behavior","authorized use"],["behavior","observe","outcome class"]],
  },
  moneyFlow: {
    title: "One financial decision retains its policy evidence",
    description: "A trusted boundary validates machine-readable input using authoritative currency metadata. A versioned rounding and rate snapshot produce a durable operation identity before provider dispatch. A known provider result posts or rejects the operation; a lost response remains explicitly unresolved until reconciliation uses the same identity. This diagram models decision ownership, not a payment network or ledger implementation.",
    height: 430,
    nodes: [["input",20,20,"Validated amount","Minor units + currency policy"],["policy",275,20,"Versioned policy","Rounding + rate snapshot"],["intent",530,20,"Durable intent","Operation + idempotency key"],["provider",20,210,"Provider dispatch","Known result or response loss"],["post",275,210,"Post terminal result","Posted or rejected"],["reconcile",530,210,"Reconcile UNKNOWN","Same identity + evidence"]],
    edges: [["input","policy","validated input"],["policy","intent","reproducible decision"],["intent","provider","one operation"],["provider","post","known outcome"],["provider","reconcile","ambiguous response"],["reconcile","post","authoritative evidence"]],
  },
  networkBudget: {
    title: "Every phase spends the same caller deadline",
    description: "The caller deadline bounds setup and response work together. A child operation receives only the remaining time after a response reserve. When no usable time remains, do not start another address attempt or retry. Losing a write response produces an unknown outcome that requires the original identity and reconciliation.",
    nodes: [["caller",20,20,"Caller deadline","One monotonic budget"],["remaining",275,20,"Remaining time","Subtract elapsed + reserve"],["child",530,20,"Bounded child call","Cap setup and response"],["stop",275,190,"No usable budget","Do not launch work"],["unknown",530,190,"Write response lost","Reconcile same identity"]],
    edges: [["caller","remaining","propagate"],["remaining","child","time available"],["remaining","stop","budget exhausted"],["child","unknown","ambiguous loss"]],
  },
  proxyTrust: {
    title: "Forwarded metadata needs a trusted direct hop",
    description: "A controlled proxy strips incoming forwarding claims and writes metadata derived from the connection it accepted. The application trusts those claims only when that proxy is its direct peer. Authorization still uses authenticated identity and resource ownership rather than a client address.",
    nodes: [["client",20,20,"Client request","Forwarded headers untrusted"],["proxy",275,20,"Controlled proxy","Strip then rewrite claims"],["app",530,20,"Application","Verify direct peer"],["auth",530,190,"Resource authorization","Principal + owned resource"]],
    edges: [["client","proxy","network connection"],["proxy","app","trusted hop metadata"],["app","auth","separate decision"]],
  },
  kubernetesLifecycle: {
    title: "A pod joins and leaves traffic deliberately",
    description: "Startup protects initialization. Readiness controls service traffic. During termination the workload stops admitting work, its owners reach safe points, and only then does the process exit.",
    nodes: [["start",20,20,"Startup probe","Initialization completes"],["ready",275,20,"Readiness probe","Service admits traffic"],["drain",530,20,"Termination drain","Stop new work"],["exit",275,190,"Safe exit","Owners finish or stop"]],
    edges: [["start","ready","started"],["ready","drain","termination"],["drain","exit","safe point"]],
  },
  postgresCutover: {
    title: "A database cutover preserves one writer",
    description: "Coordinate the initial copy with the change stream, then fence and drain the source. Verify final apply progress, data, schema, and sequence allocation before opening target writes. After target commits, returning to the source requires reconciliation or reverse replication; routing back alone is unsafe.",
    nodes: [["old",20,30,"Source writer","Copy with changes"],["sync",530,30,"Fence and drain","Apply final position"],["verify",530,210,"Verify promotion","Data + DDL + sequences"],["cutover",20,210,"Open target writes","Return needs reconciliation"]],
    edges: [["old","sync","rehearsed write pause"],["sync","verify","final changes applied"],["verify","cutover","all gates pass"]],
  },
  otelPipeline: {
    title: "A telemetry pipeline needs bounded ownership",
    description: "Services offload telemetry to an agent or gateway. Memory limits, queues, retries, and optional persistent storage make loss behavior explicit. Internal metrics show whether the pipeline is itself healthy.",
    nodes: [["sdk",20,20,"Service SDK","Create traces, metrics, logs"],["agent",275,20,"Agent or gateway","Process and batch"],["queue",530,20,"Bounded queue","Retry or durable storage"],["backend",275,190,"Telemetry backend","Observe pipeline health"]],
    edges: [["sdk","agent","export"],["agent","queue","bounded send"],["queue","backend","deliver"]],
  },
  supplyChain: {
    title: "An artifact carries evidence through promotion",
    description: "A controlled build produces an immutable image digest with an SBOM and provenance. Policy verifies that evidence before the same digest moves through a canary to production.",
    nodes: [["build",20,20,"Controlled build","Pinned source + inputs"],["evidence",275,20,"SBOM + provenance","Attached to image digest"],["policy",530,20,"Verification gate","Signer and policy checks"],["deploy",275,190,"Promote digest","Canary or rollback"]],
    edges: [["build","evidence","attest"],["evidence","policy","verify"],["policy","deploy","allow"]],
  },
  llmGuardrail: {
    title: "An LLM release is evaluated before it acts",
    description: "Versioned task cases test candidate behavior. Deterministic policy and tool checks reject unsafe output before calibrated quality evaluation. A canary feeds real failure classes back into the next evaluation set.",
    nodes: [["cases",20,20,"Evaluation cases","Expected properties"],["checks",275,20,"Policy + schema checks","Hard safety gate"],["quality",530,20,"Quality evaluation","Grounded helpful output"],["canary",275,190,"Canary feedback","Monitor and improve dataset"]],
    edges: [["cases","checks","run candidate"],["checks","quality","safe output"],["quality","canary","release gate"]],
  },
  lbPipeline: {"title":"Routing is three separate decisions","description":"First exclude unhealthy and draining nodes. Select an eligible backend using the workload's policy, then admit only bounded work. If no capacity is available, use an explicit bounded failure policy.","nodes":[["eligible",20,20,"Eligibility","Healthy + not draining"],["select",275,20,"Selection","Shares, load, or key"],["admit",530,20,"Admission","Bound concurrency"],["fail",530,190,"No capacity","Reject or bounded queue"]],"edges":[["eligible","select","candidates"],["select","admit","chosen node"],["admit","fail","at limit"]]},
  lbScores: {"title":"Raw counts and weighted load choose differently","description":"Backend A has 18 active connections and weight 6, yielding score 3. Backend B has 8 and weight 2, yielding score 4. Raw least connections selects B, while the normalized policy selects A. Draining C is excluded despite having no connections.","nodes":[["a",20,20,"A: 18 active","Weight 6; score 3"],["b",530,20,"B: 8 active","Weight 2; score 4"],["raw",530,190,"Raw count: B","8 is less than 18"],["weighted",20,190,"Normalized: A","3 is less than 4"]],"edges":[["a","weighted","capacity-aware"],["b","raw","unweighted"]]},
  lbRing: {"title":"Consistent hashing: one changed interval","description":"On a toy 0–99 ring, A is at 10, B at 50, and C at 90. Key 65 initially belongs to C. Inserting D at 70 moves only keys in (50,70] to D. Key 95 wraps to A before and after the change. This is a placement diagram, not data migration.","nodes":[["key",20,20,"Key 65","Seek next token"],["before",275,20,"Before: C at 90","Next clockwise token"],["insert",20,190,"Insert D at 70","Between B and C"],["after",275,190,"After: D at 70","Only (50,70] moves"],["wrap",530,190,"Key 95: A at 10","Wrap unchanged"]],"edges":[["key","before","old ring"],["insert","after","new ring"]]},
  realtimePoll: {"title":"Long polling: retain updates between requests","description":"The client requests updates after 70. The server waits and returns 71. After applying it, the client requests after 71 and receives retained event 72, including if it arrived between requests.","nodes":[["ask",20,20,"Request after 70","Bounded wait"],["reply",275,20,"Return event 71","Client applies update"],["again",530,20,"Request after 71","Replay retained event 72"]],"edges":[["ask","reply","event arrives"],["reply","again","next request"]]},
  realtimeSse: {"title":"SSE: reconnect is a replay decision","description":"The server streams updates to a browser. After disconnection a cursor is sent on reconnect. Retained history permits replay; expired history requires a consistent snapshot before resuming.","nodes":[["stream",20,20,"Stream updates","Server to browser"],["drop",275,20,"Connection drops","Reconnect with cursor"],["check",530,20,"Check retention","Authorize stream"],["replay",275,190,"Replay history","Events after cursor"],["reset",530,190,"Reset from snapshot","Resume after its cursor"]],"edges":[["stream","drop","disconnect"],["drop","check","resume"],["check","replay","retained"],["check","reset","expired"]]},
  realtimeSocket: {"title":"WebSocket commands survive lost acknowledgments","description":"A command is authorized and its result committed. If the acknowledgment is lost, the client resends the same command identity. The server returns the stored result without applying the command again.","nodes":[["send",20,20,"Send command C8","Client to server"],["commit",275,20,"Commit result","Authorize + deduplicate"],["lost",530,20,"Acknowledgment lost","Outcome unclear to client"],["retry",530,190,"Retry command C8","Same intended effect"],["result",275,360,"Return stored result","No second execution"]],"edges":[["send","commit","execute"],["commit","lost","disconnect"],["lost","retry","reconnect"],["retry","result","lookup"]]},
  realtimeWebhook: {"title":"Webhook acknowledgment follows durable acceptance","description":"Verify the callback, persist it in a durable inbox, then acknowledge. A worker atomically applies the local state change and records processing. Repeated deliveries resolve to the same inbox identity.","nodes":[["verify",20,20,"Verify callback","Signature + input limits"],["inbox",275,20,"Commit durable inbox","Unique provider/event ID"],["ack",530,20,"Acknowledge","After durable acceptance"],["worker",275,190,"Process transaction","State + marker + outbox"],["publish",530,190,"Publish outbox","Retry-safe consumers"]],"edges":[["verify","inbox","valid"],["inbox","ack","committed"],["inbox","worker","async"],["worker","publish","committed"]]},
  saga: {
    title: "Order saga: success and compensation",
    description: "After reserving stock, capture payment. A confirmed capture confirms the order. A definitive rejection releases stock before cancellation. An ambiguous timeout requires reconciliation, not immediate compensation.",
    nodes: [["reserve",20,20,"Reserve stock","Local inventory transaction"],["capture",275,20,"Capture payment","Stable idempotency key"],["confirm",530,20,"Confirm order","Payment confirmed"],["unknown",20,180,"UNKNOWN payment","Query provider; keep key"],["release",275,180,"Release stock","Retry compensation safely"],["cancel",530,180,"Cancel order","After release is confirmed"]],
    edges: [["reserve","capture","reserved"],["capture","confirm","accepted"],["capture","unknown","ambiguous timeout"],["capture","release","rejected"],["release","cancel","released"]],
  },
  cache: {
    title: "Cache-aside: hit and miss branches",
    description: "A fresh cache hit returns directly. A miss loads the authoritative source, validates freshness or version, fills the cache, and returns. An unsafe stale value must not be served as a valid hit.",
    nodes: [["read",20,20,"Read request","Cache key + tenant"],["cache",275,20,"Check cache","Fresh and permitted?"],["return",530,20,"Return value","Hit avoids source read"],["source",275,180,"Load source","Miss or unsafe stale value"],["fill",530,180,"Validate and fill","Then return to caller"]],
    edges: [["read","cache","lookup"],["cache","return","hit"],["cache","source","miss"],["source","fill","loaded"]],
  },
  cacheRace: {
    title: "Stale fill race: retain the version floor",
    description: "An old reader starts loading v1. A write commits v2 and invalidation records a v2 floor. When the v1 load finishes, the floor rejects it even if the cached value was evicted. A v2 or newer load may fill the cache.",
    nodes: [["load",20,20,"T1: load v1","Reader still in flight"],["write",275,20,"T2: commit v2","Authoritative source"],["floor",530,20,"T3: invalidate","Retain floor = v2"],["late",20,180,"T4: v1 arrives","Compare to retained floor"],["reject",275,180,"Reject v1","1 < 2: do not refill"],["fresh",530,180,"Accept v2+","Recheck floor on fill"]],
    edges: [["load","write","concurrent write"],["write","floor","invalidation"],["load","late","late response"],["late","reject","below floor"],["floor","fresh","new load"]],
  },
  breaker: {
    title: "Circuit breaker state transitions",
    description: "Closed permits normal calls. A failure threshold opens the circuit and rejects calls. After cooldown, half-open admits a bounded probe. A successful probe closes the circuit; a failed probe reopens it. Every remote call still needs a timeout.",
    nodes: [["closed",20,20,"CLOSED","Normal calls allowed"],["open",530,20,"OPEN","Reject calls"],["probe",275,200,"HALF_OPEN","Bounded recovery probe"]],
    edges: [["closed","open","failure threshold"],["open","probe","cooldown elapsed"],["probe","closed","probe succeeds"],["probe","open","probe fails"]],
  },
  memory: {
    title: "JVM process memory: beyond the heap",
    description: "Process memory includes Java heap, thread stacks, and other native regions such as metaspace, code cache, direct buffers and mappings. A container can run out of memory while the Java heap remains stable.",
    nodes: [["process",275,20,"Java process","Container memory budget"],["heap",20,190,"Java heap","Live objects + allocation"],["stacks",275,190,"Thread stacks","Count × stack budget"],["native",530,190,"Other regions","Metaspace, code, direct, maps"]],
    edges: [["process","heap","managed objects"],["process","stacks","per-thread"],["process","native","outside heap"]],
  },
  sql: {
    title: "Selective index access versus a full scan",
    description: "A full scan examines table rows and then filters. A selective index finds matching entries and fetches needed rows, unless the index covers the query. Both paths must return equivalent results. For low selectivity a scan may be cheaper.",
    height: 580,
    nodes: [["query",275,20,"Same query","Same parameters + snapshot"],["scan",20,190,"Full scan","Read table pages"],["index",530,190,"Index access","Seek matching keys"],["filter",20,360,"Apply predicate","Discard nonmatching rows"],["fetch",530,360,"Fetch needed rows","Or use covering index"],["result",275,480,"Equivalent result","Compare reads and latency"]],
    edges: [["query","scan","plan A"],["query","index","plan B"],["scan","filter","all rows"],["index","fetch","candidate rows"],["filter","result","matches"],["fetch","result","matches"]],
  },
  pointers: {
    title: "Two pointers: sorted pair sum",
    description: "For [1, 2, 4, 8] and target 6: 1 + 8 is too large, so move right leftward. Then 1 + 4 is too small, so move left rightward. Finally 2 + 4 equals 6. Sorted order makes each elimination valid.",
    nodes: [["first",20,20,"L=1, R=8","Sum 9 > target 6"],["second",275,20,"L=1, R=4","Sum 5 < target 6"],["third",530,20,"L=2, R=4","Sum 6: found pair"]],
    edges: [["first","second","move R left"],["second","third","move L right"]],
  },
  window: {
    title: "Sliding window: longest unique substring",
    description: "Scan abba. After a and b the valid window is ab, length 2. The next b duplicates a character: remove a, then the old b. The window is b; adding a gives ba. The maximum remains 2.",
    nodes: [["ab",20,20,"Window: ab","Best length = 2"],["abb",275,20,"Next character: b","Duplicate: window invalid"],["b",530,20,"Shrink to: b","Remove a, then old b"],["ba",530,190,"Append a: ba","Best length still 2"]],
    edges: [["ab","abb","expand"],["abb","b","restore invariant"],["b","ba","expand"]],
  },
  stack: {
    title: "Monotonic stack: next warmer day",
    description: "Temperatures [73, 71, 74]: store unresolved indices. At 74, pop day 1 (wait 1 day), then day 0 (wait 2 days). Push day 2. Each index is pushed and popped at most once.",
    nodes: [["a",20,20,"Day 0: 73","Stack [0]"],["b",275,20,"Day 1: 71","Stack [0, 1]"],["c",530,20,"Day 2: 74","Pop 1 and 0; push 2"],["out",530,190,"Answer [2, 1, 0]","0 means no warmer day"]],
    edges: [["a","b","push cooler"],["b","c","pop cooler days"],["c","out","record waits"]],
  },
  bfs: {
    title: "Breadth-first search: distance layers",
    description: "In an unweighted graph A connects to B and C, and both connect to D. Start at A with distance 0. Enqueue B and C at distance 1. Mark D on first enqueue at distance 2 so it is not queued twice.",
    nodes: [["a",275,20,"A: distance 0","Queue [A]"],["b",20,190,"B: distance 1","First neighbor"],["c",530,190,"C: distance 1","Second neighbor"],["d",275,360,"D: distance 2","Enqueue only once"]],
    edges: [["a","b","first layer"],["a","c","first layer"],["b","d","discover"],["c","d","already visited"]],
  },
  apiEvolution: {
    title: "Compatible API evolution: prove before removal",
    description: "An additive change lets old clients continue with the prior behavior while capable clients use the optional field. Contract tests and adoption telemetry precede deprecation. Removal happens only after the published window and measured migration, with a rollback path retained through the rollout.",
    nodes: [["add",20,20,"Add optional field","Preserve old meaning"],["mixed",275,20,"Mixed clients","Old ignores; new uses"],["evidence",530,20,"Prove adoption","Contract tests + telemetry"],["deprecate",160,180,"Deprecate safely","Published window"],["remove",415,180,"Remove behavior","Only after proof"]],
    edges: [["add","mixed","deploy"],["mixed","evidence","measure"],["evidence","deprecate","ready"],["deprecate","remove","window + threshold"]],
  },
  configuration: {
    title: "Configuration rollout: validate before traffic",
    description: "Deployment inputs bind into one typed configuration contract. Validation rejects missing or unsafe combinations before readiness. A canary then compares user-visible signals with the current version; the team promotes only when the gate passes and otherwise restores the known-good version. Secret values never appear in the diagram, logs, or fingerprint.",
    nodes: [["input",20,20,"Deployment inputs","Endpoint + secret reference"],["bind",275,20,"Typed binding","One immutable contract"],["validate",530,20,"Validate","Reject unsafe values"],["canary",160,180,"Canary traffic","Readiness + user metrics"],["decision",415,180,"Promote or roll back","Restore known-good version"]],
    edges: [["input","bind","supply"],["bind","validate","check"],["validate","canary","ready"],["canary","decision","gate"]],
  },
  jobLease: {
    title: "A lease recovers work; fencing rejects stale ownership",
    description: "Worker A claims a due job with token 7 and then pauses. Its lease expires, so worker B claims token 8. The durable result store accepts only the current token, rejecting a late write by A. The lease permits recovery; fencing prevents split ownership.",
    nodes: [["due",20,20,"Due job","Durable occurrence"],["a",275,20,"Worker A: token 7","Pauses after claim"],["b",530,20,"Worker B: token 8","Claims after expiry"],["reject",275,190,"Reject token 7","Store accepts current token"]],
    edges: [["due","a","claim"],["a","b","lease expires"],["b","reject","fence stale write"]],
  },
  jobLifecycle: {
    title: "Background work is a durable lifecycle",
    description: "A scheduler records a due occurrence. One worker claims it under a bounded lease, executes with a stable side-effect identity, and persists a terminal result. An ambiguous external outcome becomes reconciliation work rather than an unbounded retry or a silent loss.",
    nodes: [["due",20,20,"Due occurrence","Durable job identity"],["claim",275,20,"Claim + fence","One current owner"],["run",530,20,"Bounded execution","Stable provider key"],["result",160,190,"Persist outcome","Complete, deferred, UNKNOWN"],["reconcile",415,190,"Reconcile safely","Query authority"]],
    edges: [["due","claim","poll"],["claim","run","admit"],["run","result","durable result"],["result","reconcile","ambiguous only"]],
  },
  poolOwnership: {
    title: "Connection ownership ends after the database work",
    description: "A request validates before borrowing a connection, then performs its short database transaction. The checkout owner commits or rolls back before releasing exactly once. Remote work and response rendering happen outside the checkout; a cancelled caller does not itself prove the owner has stopped.",
    nodes: [["request",20,20,"Request deadline","Validate before checkout"],["lease",275,20,"Connection checkout","One owner; bounded wait"],["transaction",530,20,"Database transaction","Commit or roll back"],["release",275,190,"Release once","Only after final DB use"],["remote",530,190,"Remote work / response","Outside checkout"]],
    edges: [["request","lease","remaining budget"],["lease","transaction","database-only work"],["transaction","release","safe completion"],["release","remote","after release"]],
  },
  rateLimit: {
    title: "Rate limits admit bounded work; they do not rewrite outcomes",
    description: "An authenticated request produces a trusted quota key. One atomic authority admits or rejects it according to a bounded policy. An admitted owner may finish or become UNKNOWN after a lost response; it keeps the same operation identity for reconciliation. A shared authority outage follows an explicit fail-closed or bounded fallback policy.",
    nodes: [["identity",20,20,"Authenticated identity","Tenant + normalized operation"],["authority",275,20,"Atomic quota authority","Consume or reject"],["owner",530,20,"Admitted owner","Bounded protected work"],["rejected",20,190,"Quota exhausted","Reject before work starts"],["unknown",275,190,"UNKNOWN outcome","Reconcile same operation"],["outage",530,190,"Authority outage","Fail closed or bounded fallback"]],
    edges: [["identity","authority","trusted key"],["authority","owner","admit once"],["authority","rejected","no quota"],["owner","unknown","lost response"],["authority","outage","unavailable"]],
  },
  threadOwnership: {
    title: "One invariant, one current owner, one terminal outcome",
    description: "A request enters with a deadline and uses an atomic transition or narrow lock to protect the shared invariant. Work runs through bounded admission. Cancellation asks the task owner to reach a safe point; that owner records the durable outcome and releases resources exactly once. A timeout alone does not prove the task or external effect stopped.",
    nodes: [["request",20,20,"Request + deadline","Operation identity"],["transition",275,20,"Atomic transition","CAS or narrow lock"],["work",530,20,"Bounded work","Finite executor/resource"],["cancel",20,190,"Cancellation request","Cooperative signal"],["outcome",275,190,"Owner safe point","Commit, rollback, or UNKNOWN"],["release",530,190,"Release once","Then capacity returns"]],
    edges: [["request","transition","claim invariant"],["transition","work","admit"],["cancel","outcome","ask to stop"],["work","outcome","normal or failed"],["outcome","release","terminal handling"]],
  },
  fileUpload: {
    title: "An upload stays private until evidence matches its bytes",
    description: "An authenticated request streams into a private generated object key under byte limits. A type-specific scanner checks that exact object version. Only a durable CLEAN result permits owner-authorized issuance coordinated with deletion; missing scanner evidence remains quarantined. Existing capabilities retain their bounded lifetime or storage denial policy.",
    nodes: [["request",20,20,"Authenticated request","Owner + byte budget"],["private",275,20,"Private object version","Generated key; quarantine"],["scan",530,20,"Bounded scan","Exact version + stable identity"],["clean",160,190,"Durable CLEAN result","Policy and version match"],["deliver",415,190,"Authorized delivery","Short-lived capability"],["unknown",530,360,"UNKNOWN / reject","Reconcile or retain quarantine"]],
    edges: [["request","private","stream within limit"],["private","scan","submit exact version"],["scan","clean","clean evidence"],["clean","deliver","current owner check"],["scan","unknown","missing, unsafe, or mismatch"]],
  },
  fileDeletion: {
    title: "Deletion stops new issuance before object removal is confirmed",
    description: "A delete request first persists revoked new issuance and a pending deletion owner through the same authority as delivery issuance. Existing capabilities require expiry or storage-level denial. Object removal or retention expiry then produces confirmed evidence. A timeout remains pending and is reconciled; the service never calls it erased merely because the request was accepted.",
    nodes: [["delete",20,20,"Delete request","Authenticated owner"],["revoke",275,20,"Revoke new issuance","Durable DELETE_PENDING"],["remove",530,20,"Object delete or expiry","Stable deletion attempt"],["confirmed",160,190,"DELETED","Removal confirmed"],["pending",415,190,"DELETE_PENDING","Retry + reconcile"],["deny",530,360,"New issuance denied","Old grants expire or denied"]],
    edges: [["delete","revoke","authorize + record"],["revoke","remove","asynchronous work"],["remove","confirmed","confirmed"],["remove","pending","timeout or failure"],["revoke","deny","immediate policy effect"]],
  },
};

const assignments = {
  "design-patterns-in-18-minutes": {
    "1. Choosing a pattern": "patternChoice",
    "2. Creational patterns": "patternFactory",
    "3. Structural patterns": "patternAdapter",
    "4. Behavioral patterns": "patternStrategy",
    "5. Composition and testing": "patternInjection",
    "6. Interview design review": "patternChoice",
  },
  "java-design-patterns-with-diagrams": {
    "1. Start with the changing behavior": "patternStrategy",
    "2. Factory Method and Builder: safer object creation": "patternFactory",
    "3. Adapter and Facade: boundaries that protect the domain": "patternAdapter",
    "4. Decorator and Proxy: controlled composition": "patternDecorator",
    "5. Strategy and State: varying algorithms versus lifecycle": "patternState",
    "6. Observer, Command, and Chain: coordination with limits": "patternObserver",
    "7. Dependency Injection and the pattern trade-off": "patternInjection",
  },
  "java-observability-opentelemetry": {
    "1. Signals and user impact": "observeSignals",
    "2. Instrumentation boundaries": "observeSpans",
    "3. Context propagation": "observeContext",
    "4. Metrics and cardinality": "observeCardinality",
    "5. Sampling, cost, and privacy": "observeSampling",
    "6. Operate the feedback loop": "observeRecovery",
  },
  "api-gateway-production-patterns": { "2. Identity at the edge and authorization in services": "gatewayTrust" },
  "load-balancing-algorithms": {
    "1. Choose the unit before the algorithm": "lbPipeline",
    "2. Round robin and weighted round robin": "lbPipeline",
    "3. Least connections and weighted least connections": "lbScores",
    "4. Least response time and power of two choices": "lbPipeline",
    "5. IP hash and consistent hashing": "lbRing",
    "6. Health, draining, and a tested routing model": "lbPipeline",
  },
  "real-time-communication-patterns": {
    "1. Start with freshness and direction": "realtimePoll",
    "2. Long polling with a replay cursor": "realtimePoll",
    "3. SSE for a live read model": "realtimeSse",
    "4. WebSockets for interactive commands": "realtimeSocket",
    "5. Webhooks at the backend boundary": "realtimeWebhook",
    "6. Replay, fan-out, and bounded recovery": "realtimeSse",
  },
  "distributed-transactions-data-consistency": { "2. Saga orchestration and compensation": "saga" },
  "microservices-design-patterns": { "5. Saga and transactional outbox": "saga" },
  "caching-patterns-java": { "1. Cache-aside": "cache", "3. Invalidation and versioning": "cacheRace" },
  "resilience-engineering": { "3. Circuit breakers": "breaker" },
  "java-memory-management-evolution": { "1. The memory map": "memory", "5. Off-heap and container limits": "memory" },
  "sql-performance-interviews": { "2. Read an execution plan": "sql", "3. Index design": "sql" },
  "system-design-concepts": { "4. Caching and CDNs": "cache" },
  "system-design-handbook": { "10. Database indexes": "sql", "11. Caching": "cache" },
  "leetcode-patterns": { "Two Pointers": "pointers", "Sliding Window": "window", "Monotonic Stack": "stack", "Breadth-First Search (BFS)": "bfs" },
  "java-api-evolution-contracts": { "2. Additive payloads and tolerant readers": "apiEvolution", "5. Versioning, deprecation, and rollout": "apiEvolution" },
  "spring-boot-configuration": { "1. Treat configuration as a runtime contract": "configuration", "3. Validate and fail closed at startup": "configuration", "6. Test, deploy, and observe the effective configuration": "configuration" },
  "java-background-jobs": { "1. Model the job and its completion contract": "jobLifecycle", "2. Claim work with leases and fencing": "jobLease", "3. Make side effects idempotent and reconcile ambiguity": "jobLifecycle", "5. Drain safely during deployment and cancellation": "jobLifecycle", "6. Observe lateness, backlog, and recovery": "jobLifecycle" },
  "java-connection-pools": { "1. Treat checkout as owned, bounded work": "poolOwnership", "2. Budget acquisition and query deadlines together": "poolOwnership", "3. Keep transactions short and local": "poolOwnership", "4. Diagnose pressure before changing pool size": "poolOwnership", "5. Handle cancellation, retries, and stale ownership safely": "poolOwnership", "6. Protect capacity with admission and operational policy": "poolOwnership" },
  "java-rate-limiting": { "1. Start with the resource and trusted identity": "rateLimit", "2. Choose a policy whose boundary you can explain": "rateLimit", "3. Make admission atomic and consumption intentional": "rateLimit", "4. Keep retries and outcomes separate from quota": "rateLimit", "5. Define distributed ownership, expiry, and outage behavior": "rateLimit", "6. Observe fairness and tune without hiding overload": "rateLimit" },
  "java-service-networking": { "1. Treat DNS as cached routing data": "networkPath", "2. Share one connection budget across address candidates": "networkBudget", "3. Keep TLS identity verification intact": "networkPath", "4. Separate HTTP transport loss from operation outcome": "networkBudget", "5. Trust forwarded metadata only from known proxies": "proxyTrust", "6. Propagate deadlines and diagnose by phase": "networkBudget" },
  "java-multithreading-production": { "1. Define shared-state ownership and happens-before": "threadOwnership", "2. Make check-then-act transitions atomic": "threadOwnership", "3. Use locks, conditions, and interruption with ownership": "threadOwnership", "4. Bound executors and own their lifecycle": "threadOwnership", "5. Compose async work without orphaning cancellation": "threadOwnership", "6. Test schedules and diagnose evidence, not luck": "threadOwnership", "7. Answer production interview questions with a failure trace": "threadOwnership" },
  "java-file-uploads-production": { "1. Admit a bounded stream before reading bytes": "fileUpload", "2. Separate names and declared types from content evidence": "fileUpload", "3. Make quarantine a durable, non-public state": "fileUpload", "4. Keep duplicate requests and retries owner-bound": "fileUpload", "5. Authorize delivery at the current resource boundary": "fileUpload", "6. Delete as a retryable lifecycle, then prove operations": "fileDeletion" },
  "java-feature-flags-production": { "1. Give every flag a bounded delivery contract": "featureFlag", "2. Target only with trusted, minimal context": "featureFlag", "3. Make percentage assignment deterministic and bounded": "featureFlag", "4. Define stale snapshots and provider failure before rollout": "featureFlag", "5. Roll out with one evaluation and observable rollback": "featureFlag", "6. Retire flags and preserve operational evidence": "featureFlag" },
  "java-money-production": { "1. Model money in minor units with explicit currency": "moneyFlow", "2. Parse decimal input without locale or silent rounding": "moneyFlow", "3. Make rounding and residual allocation a versioned policy": "moneyFlow", "4. Quote foreign exchange from a bounded snapshot": "moneyFlow", "5. Persist intent before dispatch and preserve ambiguity": "moneyFlow", "6. Reconcile, retain evidence, and close deliberately": "moneyFlow" },
};

export function chapterDiagramKey(blogId, chapterTitle) {
  if (["kubernetes-java-production", "postgres-zero-downtime-migrations", "opentelemetry-collector-production", "java-container-supply-chain-security", "production-llm-evals-guardrails"].includes(blogId)) {
    return PRODUCTION_WORKSHOPS[chapterTitle.replace(/^\d+\.\s*/, '')]?.key || null;
  }
  return assignments[blogId]?.[chapterTitle] || null;
}

export const BLOG_OVERVIEW_DIAGRAMS = {
  ...SUPPLEMENTAL_OVERVIEWS,
  "java-observability-opentelemetry": "observeSignals",
  "api-gateway-production-patterns": "gatewayTrust",
  "load-balancing-algorithms": "lbPipeline",
  "real-time-communication-patterns": "realtimeSse",
  "caching-patterns-java": "cache",
  "java-memory-management-evolution": "memory",
  "sql-performance-interviews": "sql",
  "distributed-transactions-data-consistency": "saga",
  "resilience-engineering": "breaker",
  "java-background-jobs": "jobLifecycle",
  "java-connection-pools": "poolOwnership",
  "java-rate-limiting": "rateLimit",
  "java-service-networking": "networkPath",
  "kubernetes-java-production": "kubernetesLifecycle",
  "postgres-zero-downtime-migrations": "postgresCutover",
  "opentelemetry-collector-production": "otelPipeline",
  "java-container-supply-chain-security": "supplyChain",
  "production-llm-evals-guardrails": "llmGuardrail",
  "java-multithreading-production": "threadOwnership",
  "java-file-uploads-production": "fileUpload",
  "java-feature-flags-production": "featureFlag",
  "java-money-production": "moneyFlow",
};

export const BLOG_OVERVIEW_KINDS = {
  "java-8-to-26-evolution": "javaTimeline",
  "design-patterns-in-18-minutes": "pattern",
  "java-design-patterns-with-diagrams": "pattern",
  "learn-low-level-design-from-zero": "lld",
  "leetcode-patterns": "dsa",
  "system-design-concepts": "default",
  "system-design-handbook": "default",
  "production-java-reliability": "java",
  "api-reliability-playbook": "api",
  "technical-interview-communication": "communication",
  "java-concurrency-interviews": "java",
  "distributed-systems-interviews": "distributed",
  "behavioral-star-interviews": "behavioral",
  "system-design-fundamentals-roadmap": "default",
  "java-observability-opentelemetry": "observe",
  "spring-transactions-data-access": "event",
  "java-performance-clinic": "observe",
  "event-driven-java-reliability": "event",
  "production-java-testing": "java",
  "microservices-design-patterns": "distributed",
  "microservices-migration-patterns": "default",
  "spring-boot-security": "api",
  "spring-boot-configuration": "default",
};
