// Authored, subject-specific diagrams shared by the public and workspace readers.
export const SUPPLEMENTAL_DIAGRAMS = {
  patternChoice: {
    title: "Choose a pattern from the change",
    description: "Begin with the expensive change, identify the boundary that must stay stable, then choose the smallest abstraction. For checkout pricing, policies vary while checkout keeps calling the same interface.",
    nodes: [["n0",20,40,"Changing behavior","Pricing or construction"],["n1",275,40,"Stable contract","What callers rely on"],["n2",530,40,"Small abstraction","Strategy, factory, adapter"]],
    edges: [["n0","n1","isolate"],["n1","n2","implement"]],
  },
  patternStrategy: {
    title: "Strategy: checkout delegates pricing",
    description: "Checkout depends on PricingPolicy, not a particular discount class. At construction time, supply StandardPricing or DiscountPricing. Both implement price(subtotal). A $100 subtotal produces $100 or $90 with a ten-percent discount; checkout uses the returned amount.",
    nodes: [["checkout",20,40,"Checkout","Calls price(subtotal)"],["contract",275,40,"PricingPolicy","Stable pricing interface"],["standard",20,220,"StandardPricing","$100 → $100"],["discount",530,220,"DiscountPricing","$100 − $10 → $90"]],
    edges: [["checkout","contract","calls"],["standard","contract","implements"],["discount","contract","implements"]],
  },
  patternFactory: {
    title: "Factory Method: subclasses choose the product",
    description: "The creator defines the workflow and calls an overridable creation method. EmailCreator overrides that method to construct EmailSender. The workflow uses the Sender interface, which keeps it independent of the concrete sender.",
    nodes: [["creator",20,40,"Creator workflow","Calls createSender()"],["subclass",275,40,"EmailCreator","Overrides createSender()"],["product",530,40,"EmailSender","Concrete product"],["interface",530,220,"Sender interface","Workflow sends through it"]],
    edges: [["subclass","creator","extends"],["subclass","product","creates"],["product","interface","implements"],["creator","interface","uses product"]],
  },
  patternAbstractFactory: {
    title: "Abstract Factory: keep product families compatible",
    description: "A client receives one factory family. AwsFactory creates AWS storage and queue adapters; a different family creates its own matching adapters. The client uses abstract storage and queue contracts.",
    nodes: [["client",20,40,"Client","Needs storage + queue"],["factory",275,40,"CloudFactory","Injected family"],["storage",20,220,"Storage adapter","Family-specific storage"],["queue",530,220,"Queue adapter","Same family"]],
    edges: [["client","factory","requests family"],["factory","storage","creates"],["factory","queue","creates"]],
  },
  patternBuilder: {
    title: "Builder: validate before publishing an object",
    description: "A builder collects options and required values, validates them in build(), and returns a complete immutable request. Invalid input produces an error rather than a partially initialized request.",
    nodes: [["n0",20,40,"Builder inputs","Required name + options"],["n1",275,40,"build() validation","Reject missing fields"],["n2",530,40,"Immutable request","Ready for callers"]],
    edges: [["n0","n1","collect"],["n1","n2","valid only"]],
  },
  patternAdapter: {
    title: "Adapter: translate at the boundary",
    description: "Checkout calls the domain-owned PaymentPort. A gateway adapter translates the domain request into the vendor API and maps its result back. Keep vendor formats and error codes inside this boundary.",
    nodes: [["n0",20,40,"Checkout","Domain payment request"],["n1",275,40,"Gateway adapter","Implements PaymentPort"],["n2",530,40,"Vendor SDK","Vendor-specific charge"]],
    edges: [["n0","n1","domain call"],["n1","n2","translated call"]],
  },
  patternFacade: {
    title: "Facade: expose one cohesive workflow",
    description: "The publishing facade offers one publish operation and coordinates encoder and storage services. The services retain their own responsibilities; the facade does not absorb all domain logic.",
    nodes: [["client",20,40,"Client","publish(video)"],["facade",275,40,"Publishing facade","Coordinates workflow"],["encode",20,220,"Encoder","Produces video formats"],["store",530,220,"Storage","Persists encoded output"]],
    edges: [["client","facade","calls"],["facade","encode","encode"],["facade","store","store result"]],
  },
  patternProxy: {
    title: "Proxy: control access before delegation",
    description: "The client sees the same service contract. An authorization proxy checks access and delegates to the real service only when permitted. A denied call never reaches the real implementation.",
    nodes: [["n0",20,40,"Client","Calls service contract"],["n1",275,40,"Authorization proxy","Allow or reject"],["n2",530,40,"Real service","Runs authorized work"]],
    edges: [["n0","n1","request"],["n1","n2","if allowed"]],
  },
  patternDecorator: {
    title: "Decorator: wrap the same contract",
    description: "A tracing decorator records the call and delegates to the wrapped sender. Both expose the Sender contract. Adding a wrapper changes behavior without requiring the caller to know a new interface.",
    nodes: [["n0",20,40,"Client","Sender.send(message)"],["n1",275,40,"Tracing decorator","Record span + delegate"],["n2",530,40,"Concrete sender","Deliver the message"]],
    edges: [["n0","n1","same interface"],["n1","n2","same interface"]],
  },
  patternComposite: {
    title: "Composite: use leaves and groups uniformly",
    description: "A caller uses the Component operation. A group implements that operation by invoking its children, which may be leaves or more groups. Define empty-group behavior and protect traversal from cycles.",
    nodes: [["caller",20,40,"Caller","Component.operation()"],["group",275,40,"Group component","Delegates to children"],["leaf",20,220,"Leaf component","Performs local operation"],["nested",530,220,"Nested group","More components"]],
    edges: [["caller","group","calls"],["group","leaf","child operation"],["group","nested","child operation"]],
  },
  patternObserver: {
    title: "Observer: fan out with explicit lifecycle",
    description: "A subject publishes a state change to registered listeners. Each listener owns its handling. Registration, unsubscribe, ordering, and failure isolation must be explicit; in-process notification is not durable messaging.",
    nodes: [["subject",275,40,"Order subject","Emits status change"],["ui",20,220,"UI listener","Refreshes view"],["metrics",530,220,"Metrics listener","Records transition"]],
    edges: [["subject","ui","notify"],["subject","metrics","notify"]],
  },
  patternState: {
    title: "State: permit only valid transitions",
    description: "An order moves from Pending to Paid on confirmed capture, then to Shipped on dispatch. Events are validated against the current state; an invalid event is rejected rather than silently jumping states.",
    nodes: [["n0",20,40,"Pending","Await confirmed payment"],["n1",275,40,"Paid","Payment accepted"],["n2",530,40,"Shipped","Dispatch recorded"]],
    edges: [["n0","n1","capture confirmed"],["n1","n2","dispatch"]],
  },
  patternCommand: {
    title: "Command: give an action an identity",
    description: "An invoker submits a command containing its arguments and operation identity. A handler executes the receiver operation. If commands can be retried, identity and stored results must protect effects.",
    nodes: [["n0",20,40,"Invoker","Submit command C8"],["n1",275,40,"Command handler","Validate + deduplicate"],["n2",530,40,"Receiver","Apply intended effect"]],
    edges: [["n0","n1","enqueue or call"],["n1","n2","execute"]],
  },
  patternTemplate: {
    title: "Template Method: fix the order, vary a step",
    description: "The base class owns the import algorithm: read, transform, then save. A subclass overrides the transformation hook while the workflow order remains in the base class. Prefer composition when steps vary independently.",
    nodes: [["n0",20,40,"Read input","Base-class workflow"],["n1",275,40,"Transform hook","Subclass implementation"],["n2",530,40,"Save output","Base-class workflow"]],
    edges: [["n0","n1","fixed sequence"],["n1","n2","fixed sequence"]],
  },
  patternChain: {
    title: "Chain: continue only while eligible",
    description: "Authentication verifies identity, authorization checks permission, and validation checks the request. Each handler can reject immediately; only accepted requests continue to the next handler.",
    nodes: [["n0",20,40,"Authenticate","Reject unknown identity"],["n1",275,40,"Authorize","Reject missing permission"],["n2",530,40,"Validate","Reject invalid request"]],
    edges: [["n0","n1","accepted"],["n1","n2","accepted"]],
  },
  patternMediator: {
    title: "Mediator: coordinate without peer dependencies",
    description: "A dialog mediator receives a selection event and coordinates form and preview widgets. Widgets depend on the mediator contract rather than directly orchestrating each other.",
    nodes: [["list",20,40,"Selection widget","Sends selected item"],["mediator",275,40,"Dialog mediator","Coordinates interaction"],["form",20,220,"Form widget","Loads selected values"],["preview",530,220,"Preview widget","Renders selected item"]],
    edges: [["list","mediator","selection changed"],["mediator","form","update"],["mediator","preview","update"]],
  },
  patternRepository: {
    title: "Repository: keep persistence behind a domain contract",
    description: "An order service uses an OrderRepository contract to load an aggregate. The repository implementation owns database mapping. Domain decisions remain in the service or aggregate, not the storage adapter.",
    nodes: [["n0",20,40,"Order service","Domain decision"],["n1",275,40,"OrderRepository","Load / save aggregate"],["n2",530,40,"Database adapter","Queries and mapping"]],
    edges: [["n0","n1","domain contract"],["n1","n2","implementation"]],
  },
  patternUnitOfWork: {
    title: "Unit of Work: commit a related change set",
    description: "Track related changes, validate them inside the intended local transaction boundary, then commit together. On failure roll back that local unit; this does not roll back remote services.",
    nodes: [["n0",20,40,"Track changes","Order + local ledger"],["n1",275,40,"Transaction boundary","Validate / flush"],["n2",530,40,"Commit or rollback","One local outcome"]],
    edges: [["n0","n1","collect"],["n1","n2","atomic outcome"]],
  },
  patternInjection: {
    title: "Dependency Injection: construct outside the workflow",
    description: "The composition root creates collaborators and supplies them to the service. Tests can supply a fake clock or repository without changing the service's business code.",
    nodes: [["root",275,40,"Composition root","Builds object graph"],["clock",20,220,"Clock dependency","Real or fake"],["service",275,390,"Order service","Uses supplied contracts"],["repo",530,220,"Repository dependency","Database or test double"]],
    edges: [["root","clock","creates"],["root","repo","creates"],["clock","service","injected"],["repo","service","injected"]],
  },
  javaUpgrade: {
    title: "Java evolution: capabilities require verification",
    description: "Group a platform upgrade into language/API changes and runtime behavior, then verify the application's dependencies and real workload. A newer JDK is not proof that latency or memory improves.",
    nodes: [["n0",20,40,"Language and APIs","Choose supported features"],["n1",275,40,"Compatibility gate","Dependencies + tests"],["n2",530,40,"Runtime evidence","Latency, memory, startup"]],
    edges: [["n0","n1","adopt deliberately"],["n1","n2","measure"]],
  },
  lldOwnership: {
    title: "Low-level design: assign responsibility around an invariant",
    description: "Start with a business rule, choose the object that owns it, and give that object an interface that rejects invalid operations. A reservation aggregate can protect capacity instead of spreading checks among callers.",
    nodes: [["n0",20,40,"Invariant","Reserved ≤ capacity"],["n1",275,40,"Reservation owner","Controls state changes"],["n2",530,40,"Public operation","Reserve or reject"]],
    edges: [["n0","n1","belongs to"],["n1","n2","exposes"]],
  },
  securityBoundary: {
    title: "Identity is not permission",
    description: "Validate a token against the configured trust rules, load the resource, then check action and ownership. A valid token for tenant A must not authorize access to tenant B's order.",
    nodes: [["n0",20,40,"Verify identity","Issuer, audience, expiry"],["n1",275,40,"Load resource","Determine actual tenant"],["n2",530,40,"Authorize operation","Scope + ownership"]],
    edges: [["n0","n1","verified principal"],["n1","n2","allow or deny"]],
  },
  migrationCutover: {
    title: "Strangler migration: keep the route reversible",
    description: "A facade routes the selected capability to the legacy or new implementation. Begin with legacy ownership, verify new results, then canary traffic. Keep one authoritative writer and a rollback plan.",
    nodes: [["edge",275,40,"Routing facade","Capability + rollout flag"],["old",20,220,"Legacy service","Initial authority"],["next",530,220,"New service","Verified canary cohort"]],
    edges: [["edge","old","default / rollback"],["edge","next","canary after checks"]],
  },
  reliabilityBoundary: {
    title: "Production Java: bound work at each boundary",
    description: "Admit only bounded work, execute a local transaction within its ownership boundary, and call remote dependencies under deadlines. Do not keep scarce resources while waiting unnecessarily.",
    nodes: [["n0",20,40,"Admission","Bound concurrency"],["n1",275,40,"Local work","Own transaction / data"],["n2",530,40,"Remote boundary","Deadline + safe retries"]],
    edges: [["n0","n1","permitted work"],["n1","n2","bounded call"]],
  },
  deadlineBudget: {
    title: "Retries consume the original budget",
    description: "A 300 ms caller budget loses 80 ms to the first attempt and 40 ms to backoff. The next attempt receives at most the remaining 180 ms, less any response reserve. Retries never create a fresh caller deadline.",
    nodes: [["n0",20,40,"Caller budget","300 ms total"],["n1",275,40,"Attempt + backoff","80 ms + 40 ms spent"],["n2",530,40,"Remaining budget","180 ms minus reserve"]],
    edges: [["n0","n1","consume"],["n1","n2","propagate"]],
  },
  interviewEvidence: {
    title: "Explain a technical decision with evidence",
    description: "State a requirement, walk through a concrete example or calculation, then defend the choice and its limits. This gives the interviewer an explicit assumption to challenge.",
    nodes: [["n0",20,40,"Requirement","Freshness ≤ 10 seconds"],["n1",275,40,"Worked evidence","50k / 10 = 5k polls/s"],["n2",530,40,"Decision + trade-off","Compare streaming costs"]],
    edges: [["n0","n1","quantify"],["n1","n2","justify"]],
  },
  lostUpdate: {
    title: "Lost update: two writes based on the same read",
    description: "Both workers read zero. A writes one, then B writes one based on its old read. The final value is one, not two. An atomic increment or correctly scoped lock protects the whole read-modify-write operation.",
    nodes: [["zero",275,40,"Counter = 0","Shared initial value"],["a",20,220,"Worker A","Reads 0; writes 1"],["b",530,220,"Worker B","Reads 0; writes 1"],["final",275,400,"Counter = 1","One increment lost"]],
    edges: [["zero","a","read"],["zero","b","read"],["a","final","first write"],["b","final","later write"]],
  },
  distributedReplay: {
    title: "A duplicate delivery must not repeat a local effect",
    description: "A broker redelivers when an acknowledgment is lost. A consumer stores the event identity with the local effect in one transaction. Replay sees the stored identity and avoids repeating that effect.",
    nodes: [["n0",20,40,"Broker","Event E4, possibly repeated"],["n1",275,40,"Consumer transaction","Effect + event marker"],["n2",530,40,"Acknowledgment","After durable commit"]],
    edges: [["n0","n1","deliver"],["n1","n2","commit then ack"]],
  },
  starEvidence: {
    title: "STAR: make your contribution attributable",
    description: "Describe the situation and task briefly, explain the action you personally took and why, then present evidence for the result and what you learned. Do not invent measurements or take credit for others' work.",
    nodes: [["n0",20,40,"Situation + task","Constraint and responsibility"],["n1",275,40,"Action + judgment","Your decision and evidence"],["n2",530,40,"Result + learning","Measured outcome + limits"]],
    edges: [["n0","n1","context for"],["n1","n2","evaluate"]],
  },
  systemCapacity: {
    title: "System design: find the next capacity limit",
    description: "With equal-cost requests, an app tier able to handle 200 requests/s cannot exceed a database path limited to 120 requests/s if every request needs it. Reducing work per request may help; adding more app nodes alone does not.",
    nodes: [["n0",20,40,"Incoming requests","Offered load"],["n1",275,40,"Application tier","Capacity: 200 requests/s"],["n2",530,40,"Database path","Capacity: 120 requests/s"]],
    edges: [["n0","n1","admit"],["n1","n2","bottleneck"]],
  },
  transactionOutbox: {
    title: "Transactional outbox: close the commit-to-publish gap",
    description: "The application commits the order and outbox row in the same local transaction. A relay reads committed rows and publishes them. A crash can cause repeat publication, so consumers must tolerate duplicates.",
    nodes: [["n0",20,40,"Local transaction","Order + outbox row"],["n1",275,40,"Outbox relay","Read committed events"],["n2",530,40,"Broker / consumer","Duplicate-safe delivery"]],
    edges: [["n0","n1","commit together"],["n1","n2","publish, may repeat"]],
  },
  performanceProof: {
    title: "Performance work: test one causal hypothesis",
    description: "Capture a representative baseline, identify a hotspot with runtime evidence, then change one thing and compare under the same workload. Reject the change if the intended metric does not improve or errors regress.",
    nodes: [["n0",20,40,"Baseline workload","Latency + throughput"],["n1",275,40,"JFR / traces / dumps","Locate suspected cost"],["n2",530,40,"Controlled comparison","Keep or reject change"]],
    edges: [["n0","n1","observe"],["n1","n2","test hypothesis"]],
  },
  testBoundary: {
    title: "Failure testing: verify the effect count",
    description: "Inject a lost response after a command commits. Retry with the same command identity and assert that the result is recoverable while the durable effect count stays one. A status-code-only test cannot establish that property.",
    nodes: [["n0",20,40,"Command K1 commits","Effect count = 1"],["n1",275,40,"Response lost","Caller outcome unknown"],["n2",530,40,"Retry / reconcile K1","Same result; count = 1"]],
    edges: [["n0","n1","inject fault"],["n1","n2","preserve identity"]],
  },
  paymentUnknown: {
    title: "Payment timeout: the effect may already exist",
    description: "A provider commits a charge before its response is lost. The client's timeout reports missing evidence, not a reversed charge. Reconcile or retry under the provider contract using the original operation identity.",
    nodes: [["n0",20,40,"Provider commits K7","Charge count = 1"],["n1",275,40,"Response lost","Client times out"],["n2",530,40,"Reconcile K7","Confirm original effect"]],
    edges: [["n0","n1","effect already exists"],["n1","n2","do not invent new intent"]],
  },
  connectionHold: {
    title: "Pool wait, connection hold, and query time differ",
    description: "A request waits to acquire a connection, holds it while executing database and possibly other work, then returns it. A full pool with short queries can indicate excessive hold time rather than a slow database.",
    nodes: [["n0",20,40,"Acquire wait","No connection owned yet"],["n1",275,40,"Connection held","SQL + any other work"],["n2",530,40,"Release","Next waiter can proceed"]],
    edges: [["n0","n1","acquire"],["n1","n2","return"]],
  },
  walRecovery: {
    title: "Commit durability: log first, recover pages later",
    description: "Under a durable local commit contract, the commit record reaches durable storage before acknowledgment. Data pages may still be old. Recovery replays committed log changes; replication failover has a separate durability contract.",
    nodes: [["n0",20,40,"Flush commit log","Durable local record"],["n1",275,40,"Acknowledge commit","Data page may be old"],["n2",530,40,"Crash recovery","Redo committed change"]],
    edges: [["n0","n1","durability boundary"],["n1","n2","replay if needed"]],
  },
};

export const SUPPLEMENTAL_OVERVIEWS = {
  "request-timed-out-did-payment-happen": "paymentUnknown",
  "connection-pool-full-is-database-slow": "connectionHold",
  "database-committed-what-survives-crash": "walRecovery",
  "java-8-to-26-evolution": "javaUpgrade",
  "design-patterns-in-18-minutes": "patternChoice",
  "java-design-patterns-with-diagrams": "patternStrategy",
  "learn-low-level-design-from-zero": "lldOwnership",
  "microservices-design-patterns": "saga",
  "leetcode-patterns": "bfs",
  "spring-boot-security": "securityBoundary",
  "microservices-migration-patterns": "migrationCutover",
  "system-design-concepts": "systemCapacity",
  "system-design-handbook": "systemCapacity",
  "production-java-reliability": "reliabilityBoundary",
  "api-reliability-playbook": "deadlineBudget",
  "technical-interview-communication": "interviewEvidence",
  "java-concurrency-interviews": "lostUpdate",
  "distributed-systems-interviews": "distributedReplay",
  "behavioral-star-interviews": "starEvidence",
  "system-design-fundamentals-roadmap": "systemCapacity",
  "spring-transactions-data-access": "transactionOutbox",
  "java-performance-clinic": "performanceProof",
  "event-driven-java-reliability": "transactionOutbox",
  "production-java-testing": "testBoundary",
  "java-api-evolution-contracts": "apiEvolution",
  "spring-boot-configuration": "configuration"
};

export const PATTERN_DIAGRAMS = {
  "Factory Method": "patternFactory",
  "Abstract Factory": "patternAbstractFactory",
  "Builder": "patternBuilder",
  "Adapter": "patternAdapter",
  "Facade": "patternFacade",
  "Proxy": "patternProxy",
  "Decorator": "patternDecorator",
  "Composite": "patternComposite",
  "Strategy": "patternStrategy",
  "Observer": "patternObserver",
  "State": "patternState",
  "Command": "patternCommand",
  "Template Method": "patternTemplate",
  "Chain of Responsibility": "patternChain",
  "Mediator": "patternMediator",
  "Repository": "patternRepository",
  "Unit of Work": "patternUnitOfWork",
  "Dependency Injection": "patternInjection"
};
