export const WEBHOOKS_BLOG = {
  id: 'java-webhooks-production', title: 'Java Webhooks in Production: Verify, Deduplicate, Recover', category: 'Java integration reliability', javaRelease: 17,
  summary: 'A Java 17 course on accepting third-party callbacks without trusting transport success, delivery order, or a retry as proof of a new business event.',
  lessons: ['Authenticate the exact delivered bytes before parsing or acting.', 'Treat delivery IDs and business versions as different contracts.', 'Persist one processing owner and retain ambiguous outcomes for reconciliation.'],
  sections: [{ heading: 'Course goal', body: 'Build a webhook boundary that rejects unauthenticated or replayed deliveries, processes one durable event identity once, and preserves uncertainty instead of inventing a second business action.' }, { heading: 'Java 17 production lens', body: 'The examples are standalone Java 17 decision models. They do not implement an HTTP server, durable database, secret store, provider retry policy, or clock synchronization; those production boundaries remain explicit.' }],
  example: 'raw bytes + verified signature → durable delivery identity → ordered business transition → known or UNKNOWN outcome',
  interviewQuestions: ['Why must signature verification use raw bytes?', 'When is an out-of-order webhook safe to ignore?', 'What must survive a crash after an external side effect?'],
  practice: 'Design a payment-provider webhook inbox: state the verification window, delivery retention, version rule, transaction boundary, retry owner, and reconciliation path.',
  capstone: { title: 'Capstone: Safely consume payment status callbacks', scenario: 'A provider retries the same signed event, sends an older status after a newer one, and its webhook acknowledgement is lost while your database transaction is uncertain.', steps: ['Verify the raw body with the provider key, validate timestamp/replay policy, and reject before parsing when authenticity cannot be established.', 'Atomically claim the provider delivery ID with the business transition or an inbox record; retain a version floor so older events cannot regress payment state.', 'Acknowledge only after the durable decision. On timeout or crash, recover the same delivery ID and reconcile any UNKNOWN external effect rather than creating a replacement operation.'], outcome: 'Produce a webhook consumer that has an explicit trust boundary, durable duplicate handling, bounded retry behavior, and a recoverable uncertainty state.' },
};

export const WEBHOOKS_CHAPTERS = [
  {
    "title": "1. Verify authenticity before parsing",
    "lesson": "A webhook is untrusted until verification succeeds. Read the bounded raw body once and compute a MAC with the configured secret over the exact signed message before comparing the supplied tag. This runnable teaching protocol signs canonical nonnegative decimal epoch seconds, a dot, then the raw body using HMAC-SHA256; it accepts a decoded 32-byte tag and at most 1 MiB of nonempty body. It is not a drop-in provider adapter: use the provider SDK/header grammar, size limits and rotation policy in production. Authenticate the timestamp before applying chapter 2 freshness checks, then parse and validate the schema and tenant. Reject malformed headers; do not normalize an arbitrary timestamp header into a different signed value. The caller must retain exclusive ownership of these arrays during verification and parse the same bytes afterward.",
    "whenToUse": "Use raw-body verification at provider callback boundaries; use this model to understand what the MAC authenticates.",
    "avoid": "Avoid passing in a caller-provided expected signature, verifying re-serialized JSON, logging secrets, accepting empty tags, or treating authenticity as tenant authorization.",
    "diagram": "timestamp + raw bytes + configured secret → compute HMAC → compare fixed-length tag → freshness → parse\nchanged body or timestamp → reject before business work",
    "example": "import java.nio.charset.StandardCharsets;\nimport java.security.GeneralSecurityException;\nimport java.security.MessageDigest;\nimport javax.crypto.Mac;\nimport javax.crypto.spec.SecretKeySpec;\n\nfinal class WebhookSignatureExample {\n  // Teaching protocol: HMAC-SHA256(decimal epoch seconds + \".\" + raw body).\n  static boolean accepts(byte[] body, long sentAt, byte[] secret, byte[] supplied)\n      throws GeneralSecurityException {\n    if (body == null || body.length == 0 || body.length > 1_048_576\n        || sentAt < 0 || secret == null || secret.length == 0\n        || supplied == null || supplied.length != 32) return false;\n    Mac mac = Mac.getInstance(\"HmacSHA256\");\n    mac.init(new SecretKeySpec(secret, \"HmacSHA256\"));\n    mac.update((Long.toString(sentAt) + \".\").getBytes(StandardCharsets.US_ASCII));\n    byte[] expected = mac.doFinal(body);\n    return MessageDigest.isEqual(expected, supplied);\n  }\n}",
    "exercise": "Trace a signed {\"id\":\"evt_1\"} at timestamp 1700000000: keeping the tag but changing evt_1 to evt_2 fails; changing the timestamp also fails. A valid replay retains its MAC but must still pass freshness and durable deduplication. Specify header parsing, rotation, maximum body size and secret storage for your provider.",
    "quiz": "Why must both raw body and timestamp be authenticated before parsing or checking freshness?",
    "answer": "Re-serialization changes signed bytes. An unsigned timestamp can be replaced to make an old message appear fresh. Compute the MAC over the provider-defined message, compare a correctly sized tag, then enforce freshness and deduplicate. None of these steps alone authorizes the business action."
  },
  { title: '2. Bound replay without trusting local time alone', lesson: 'A valid old delivery can be replayed. Validate a provider timestamp against a documented acceptance window using a trusted clock, but do not treat time alone as deduplication: delayed legitimate events and clock skew exist. A durable delivery ID with a retention period at least as long as provider retries is the duplicate boundary. Reject malformed or future timestamps according to the provider contract.', whenToUse: 'Use a timestamp window plus durable delivery identity when a provider can retry or an attacker can replay captured traffic.', avoid: 'Avoid deleting deduplication evidence sooner than the provider retry horizon or treating a clock check as proof that an event is unique.', diagram: 'verified timestamp + delivery ID → replay policy → inbox claim\noutside window → reject; duplicate ID → return prior decision', example: 'final class WebhookReplayWindowExample {\n  static boolean inWindow(long sentAt, long now, long maxAge) {\n    if (sentAt < 0 || now < 0 || maxAge < 0 || sentAt > now) throw new IllegalArgumentException();\n    return now - sentAt <= maxAge;\n  }\n}', exercise: 'Document the provider retry horizon, acceptable clock skew, future-timestamp behavior, and durable retention period.', quiz: 'Why keep a delivery ID after acknowledging it?', answer: 'Providers can retry after a lost acknowledgement. Without retained identity evidence, the retry can repeat business work even though its signature and timestamp are valid.' },
  { title: '3. Make inbox claiming and completion one owner transition', lesson: 'Two replicas can receive the same delivery concurrently. Claim its immutable provider delivery ID in a database transaction using a unique constraint or conditional insert; one claimant owns processing, while duplicates return the durable terminal result or a bounded in-progress response. Do not hold a database transaction open across an uncontrolled remote call. A local map is only a cache and cannot survive a crash.', whenToUse: 'Use a durable inbox or dedup record whenever duplicate delivery can create a durable or external effect.', avoid: 'Avoid check-then-insert races, per-process maps as the source of truth, or treating HTTP 200 as proof that every later effect completed.', diagram: 'same delivery reaches replicas → atomic inbox claim → one owner\nduplicate → durable terminal result / bounded in-progress', example: 'import java.util.concurrent.atomic.AtomicBoolean;\nfinal class WebhookClaimExample {\n  private final AtomicBoolean claimed = new AtomicBoolean();\n  boolean claim() { return claimed.compareAndSet(false, true); }\n}', exercise: 'Define the unique key, terminal states, caller response during processing, and cleanup/retention policy for an inbox row.', quiz: 'Why is a unique constraint stronger than a read followed by an insert?', answer: 'The constraint makes ownership election happen at the same durable boundary as recording the claim. Two reads can both see no row before either insert occurs.' },
  { title: '4. Separate delivery order from business version', lesson: 'Providers may retry, batch, or deliver events out of order. A delivery ID answers whether this envelope was processed; a monotonic business version answers whether applying it would regress state. Store a version floor with the aggregate and reject or safely ignore older events. Equal versions need an explicit same-payload or conflict policy; never silently overwrite a newer state because the older event arrived last.', whenToUse: 'Use a version floor when provider events represent ordered state for one business object.', avoid: 'Avoid assuming queue order, using receipt time as business order, or accepting an older terminal state after a newer one.', diagram: 'delivery ID dedup → aggregate version check → apply newer state\nolder version → ignore/reconcile; equal version → verify contract', example: 'final class WebhookVersionExample {\n  static boolean canApply(long current, long incoming) {\n    if (current < 0 || incoming < 0) throw new IllegalArgumentException();\n    return incoming > current;\n  }\n}', exercise: 'Specify the aggregate key, version source, same-version payload rule, and how a missing event is repaired.', quiz: 'Why are delivery ID and business version both necessary?', answer: 'One business update can be delivered in several envelopes, while different events can refer to the same aggregate. Delivery identity prevents duplicate envelope work; a version rule prevents state regression.' },
  {
    "title": "5. Keep retryable transport failure separate from UNKNOWN effects",
    "lesson": "Local persistence, external-effect knowledge and inbound HTTP acknowledgement are separate facts. RETRY_DELIVERY is permitted here only with proof that no external dispatch occurred; it still means re-entering the durable inbox claim, not bypassing ownership. After dispatch, a local rollback cannot undo a remote write. A missing remote response is UNKNOWN and requires reconciliation with the original operation identity. IN_FLIGHT retains its owner; on loss of observation it becomes UNKNOWN, never NOT_DISPATCHED. CONFIRMED means an authoritative terminal result (success or rejection), not merely a sent request. Persist that result before treating processing as COMPLETE. Losing the inbound acknowledgement cannot erase a known durable result: a duplicate returns that result without another effect. Committing an inbox intent alone is not a terminal result.",
    "whenToUse": "Use explicit effect, result-persistence and acknowledgement facts for callbacks that trigger payment, provisioning or another external write.",
    "avoid": "Avoid mapping local rollback or caller cancellation to safe redispatch, creating a new operation identity, releasing an in-flight owner early, or claiming durable completion from an intent-only commit.",
    "diagram": "not dispatched → durable claim → in flight → confirmed → persist result → complete\nremote response lost → UNKNOWN → reconcile original identity\ninbound acknowledgement lost after completion → duplicate returns durable result",
    "example": "final class WebhookOutcomeExample {\n  enum Effect { NOT_DISPATCHED, IN_FLIGHT, CONFIRMED, UNKNOWN }\n  enum Ack { RECEIVED, LOST }\n  enum Outcome { RETRY_DELIVERY, WAIT_FOR_OWNER, PERSIST_RESULT, COMPLETE, RECONCILE }\n\n  static Outcome decide(Effect effect, boolean terminalResultDurable, Ack ack) {\n    if (effect == null || ack == null) throw new IllegalArgumentException();\n    // Committing an inbox intent is NOT the same as durably recording a result.\n    if (terminalResultDurable && effect != Effect.CONFIRMED)\n      throw new IllegalArgumentException(\"durable terminal result requires known effect\");\n    // Ack loss never changes effect knowledge or grants a second processing owner.\n    return switch (effect) {\n      case NOT_DISPATCHED -> Outcome.RETRY_DELIVERY;\n      case IN_FLIGHT -> Outcome.WAIT_FOR_OWNER;\n      case UNKNOWN -> Outcome.RECONCILE;\n      case CONFIRMED -> terminalResultDurable ? Outcome.COMPLETE : Outcome.PERSIST_RESULT;\n    };\n  }\n}",
    "exercise": "Trace three cases: a remote write times out and local persistence rolls back → RECONCILE; an authoritative receipt exists but its local save fails → PERSIST_RESULT; the result is durable but the inbound acknowledgement is lost → COMPLETE. If a crash loses the unsaved receipt, recover UNKNOWN using the previously persisted operation identity. State the provider retention guarantee and reconciliation deadline.",
    "quiz": "Why are a lost remote response and a lost inbound acknowledgement different?",
    "answer": "A lost remote response can hide whether the effect happened, requiring reconciliation. A lost inbound acknowledgement after a durable terminal result only triggers duplicate delivery; the inbox returns the existing result. Neither cancellation nor rollback proves that dispatched work failed. The pure decision model does not implement persistence: operation identity must be durable before dispatch, and completion/recovery writes need an atomic current-owner/version predicate."
  },
  { title: '6. Observe and recover the inbox lifecycle', lesson: 'Measure verification rejects, duplicate deliveries, inbox age, in-progress count, version regressions, retry attempts, UNKNOWN age, and provider acknowledgement latency with bounded labels. Alert on growing inbox age or UNKNOWN outcomes, not merely a low error rate. Recovery workers must claim stale records with a lease/version predicate, avoid concurrent completion, and preserve original delivery and operation identities. Test duplicate, reordered, malformed, cancelled, and crash boundaries deterministically.', whenToUse: 'Use lifecycle metrics and recovery ownership when webhook work can outlive one request or process.', avoid: 'Avoid high-cardinality raw delivery IDs in metrics, unbounded retries, or a sweeper that completes records without an ownership predicate.', diagram: 'metrics + durable inbox → detect stale/UNKNOWN → versioned recovery claim → reconcile\nrecovery never invents a new delivery or operation identity', example: 'final class WebhookRecoveryExample {\n  static boolean mayRecover(long expectedVersion, long currentVersion, boolean terminal) {\n    if (expectedVersion < 0 || currentVersion < 0) throw new IllegalArgumentException();\n    return !terminal && expectedVersion == currentVersion;\n  }\n}', exercise: 'Choose stale thresholds, one recovery owner predicate, a retry cap, and a human escalation rule for UNKNOWN outcomes.', quiz: 'What does a recovery worker need besides an old timestamp?', answer: 'It needs a durable ownership/version predicate so two workers cannot both resume the same delivery, plus the original delivery and external-operation identities to preserve duplicate and reconciliation semantics.' },
];

// Worked traces shared by the public and workspace readers.
const WEBHOOK_WALKTHROUGHS = [
  'Sign timestamp 1700000000 and the raw {"id":"evt_1"} bytes. Keeping the tag while changing either the body or timestamp fails. A byte-identical replay still authenticates: freshness and durable event identity are separate checks. The Mac is created per call, not shared across threads; this method owns no closeable resource. The HTTP adapter must bound streaming reads before allocating the body and must not parse a mutable replacement after verification.',
  'At now=100 and maxAge=10, sentAt=90 is accepted and 89 is rejected. A future value 101 is rejected by this strict teaching policy; a real provider can specify bounded skew. A verified retry can carry a fresh signature timestamp but the same stable event ID, so retain deduplication evidence for the provider retry horizon. Arrival time or event creation seconds are not a monotonic business version.',
  'Two threads sharing one WebhookClaimExample see exactly one successful claim. Two separate instances do not share ownership: this illustrates compare-and-set only, not durable replica coordination. In production a tenant/provider-scoped unique event key elects one owner in the database; duplicates observe its existing result. A cancelled caller does not clear a dispatched operation. Completion requires the current owner/version, and a lease expiry alone cannot cancel an old remote request.',
  'An aggregate at version 4 accepts 5, then ignores 4 and treats another 5 under its explicit duplicate/conflict policy. Read-version-then-write is not atomic: use a conditional update in the same transaction as the inbox decision. Only use this example with a provider-supplied monotonic aggregate version; otherwise fetch authoritative current state or reconcile. Different envelopes can describe the same business transition.',
  'A persisted operation K7 is dispatched, its response is lost, and saving the result rolls back: UNKNOWN plus no durable terminal result returns RECONCILE, never RETRY_DELIVERY. If a receipt arrives, retain ownership and persist it without repeating the write. Once that result is durable, a lost inbound acknowledgement leaves COMPLETE; a repeated event returns the stored result. On crash, recover the original K7 and require authoritative same-key evidence; absent/pending evidence remains UNKNOWN. Retry only within a documented same-key/same-intent retention guarantee.',
  'Recovery read version 7, but a newer owner has version 8: mayRecover(7,8,false) rejects. Terminal version 7 also rejects. mayRecover(7,7,false) is only eligibility, not an acquired lease: claim and complete with atomic version/current-owner predicates in the database. Two recovery workers must not both dispatch; old workers cannot overwrite a newer terminal result. Bound retries and escalate unresolved outcomes without deleting their identity evidence.',
];
WEBHOOKS_CHAPTERS.forEach((chapter, index) => { chapter.walkthrough = WEBHOOK_WALKTHROUGHS[index]; });
