import { useState } from "react";
import { INCIDENT_SIMULATION, getIncidentStage } from "../../lib/incidentSimulator.mjs";

export default function IncidentSimulator({ accent = "#8bd3ff", onAction }) {
  const [stageIndex, setStageIndex] = useState(0); const [revealed, setRevealed] = useState(false); const stage = getIncidentStage(stageIndex);
  return <section style={{ border: `1px solid ${accent}55`, borderRadius: 9, display: "grid", gap: 11, padding: 12 }}>
    <div><div style={{ color: accent, fontSize: 10.5, fontWeight: 900 }}>LIVE INCIDENT SIMULATOR · {stage.time}</div><h3 style={{ margin: "5px 0" }}>{INCIDENT_SIMULATION.title}</h3><p style={{ color: "#cbd5e1", fontSize: 12, margin: 0 }}>{INCIDENT_SIMULATION.summary}</p></div>
    <div style={{ display: "grid", gap: 8, gridTemplateColumns: "repeat(auto-fit, minmax(210px, 1fr))" }}>{[["Dashboard", stage.dashboard], ["Trace", stage.trace], ["Logs", stage.log], ["Deployment diff", stage.deploy], ["Runbook", stage.runbook]].map(([label, value]) => <article key={label} style={{ background: "rgba(0,0,0,.16)", border: "1px solid rgba(255,255,255,.08)", borderRadius: 7, padding: 9 }}><strong style={{ color: accent, fontSize: 10.5 }}>{label}</strong><p style={{ color: "#dbeafe", fontFamily: label === "Logs" ? "monospace" : "inherit", fontSize: 11.5, lineHeight: 1.5, margin: "5px 0 0" }}>{value}</p></article>)}</div>
    <div style={{ display: "flex", flexWrap: "wrap", gap: 7 }}><button className="glass-button" disabled={stageIndex === 0} onClick={() => { setStageIndex((value) => value - 1); setRevealed(false); }}>Previous evidence</button><button className="glass-button" disabled={stageIndex === INCIDENT_SIMULATION.stages.length - 1} onClick={() => { setStageIndex((value) => value + 1); setRevealed(false); }}>Reveal next evidence</button><button className="glass-button" onClick={() => setRevealed((value) => !value)}>Decision checkpoints</button><button className="glass-button" onClick={() => onAction?.(`Run this incident simulation interactively. ${INCIDENT_SIMULATION.summary} Present one evidence stage at a time, ask for my decision, challenge assumptions, then assess mitigation, communication, root-cause analysis, and follow-up actions.`)}>Practice live</button></div>
    {revealed && <section style={{ borderTop: "1px solid rgba(255,255,255,.1)", display: "grid", gap: 8, paddingTop: 10 }}>{INCIDENT_SIMULATION.decisions.map((item) => <div key={item.question}><strong>{item.question}</strong><p style={{ color: "#cbd5e1", fontSize: 11.5, lineHeight: 1.5, margin: "4px 0 0" }}>{item.strong}</p></div>)}</section>}
  </section>;
}
