import { useRouter } from "next/router";
import Head from "next/head";
import Link from "next/link";
import styles from "../../styles/Reader.module.css";
export default function ReaderLayout({ title, description, children }) {
  const router = useRouter();
  const url = `${(process.env.NEXT_PUBLIC_SITE_URL || "https://interviewiq.app").replace(/\/$/, "")}${router.asPath.split(/[?#]/)[0]}`;
  return <div className={styles.shell} data-reader-scroll><Head><title>{`${title} · InterviewIQ`}</title><meta name="description" content={description} /><link rel="canonical" href={url} /><meta property="og:title" content={title} /><meta property="og:description" content={description} /><meta property="og:url" content={url} /></Head><a href="#reader-main" className={styles.skip}>Skip to reading</a><header className={styles.header}><Link prefetch={false} href="/" className={styles.brand}>InterviewIQ <span>FIELD NOTES</span></Link><nav aria-label="Reading navigation"><Link prefetch={false} href="/series">Reading paths</Link><Link prefetch={false} href="/symptoms">Symptoms Atlas</Link><Link prefetch={false} href="/detective">Challenges</Link><Link prefetch={false} href="/build">Build a tiny system</Link><Link prefetch={false} href="/notebook">My notebook</Link><Link prefetch={false} href="/explore">Explore</Link><Link prefetch={false} href="/practice">Practice workspace →</Link></nav></header><main id="reader-main" tabIndex={-1} className={styles.main}>{children}</main><footer className={styles.footer}><Link prefetch={false} href="/editorial">Editorial standards</Link><Link prefetch={false} href="/corrections">Public corrections</Link><Link prefetch={false} href="/digest">The digest</Link><Link prefetch={false} href="/weekly">Weekly challenge</Link><Link prefetch={false} href="/requests">Request board</Link><Link prefetch={false} href="/practice">Resume practice</Link></footer></div>;
}
