import Head from "next/head";
import Link from "next/link";
import { getStackGuide, PUBLIC_STACK_GUIDES } from "../../../lib/seoGuides.mjs";

export default function StackGuide({ guide }) { const url = `https://interviewiq.app/guides/${guide.stack}/${guide.slug}`; return <><Head><title>{guide.title} | InterviewIQ</title><meta name="description" content={guide.description} /><meta name="keywords" content={guide.keyword} /><link rel="canonical" href={url} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ "@context": "https://schema.org", "@type": "Article", headline: guide.title, description: guide.description, dateModified: guide.reviewedAt, author: { "@type": "Organization", name: guide.author } }) }} /></Head><main style={{ background: "#08111f", color: "#e5edf8", minHeight: "100vh", padding: "32px 18px" }}><article style={{ margin: "0 auto", maxWidth: 920 }}><nav style={{ color: "#8bd3ff", fontSize: 12, marginBottom: 20 }}><Link href="/">InterviewIQ</Link> / <Link href="/guides">Interview guides</Link> / {guide.label}</nav><header style={{ borderBottom: "1px solid #22324a", paddingBottom: 20 }}><div style={{ color: "#72d0a6", fontSize: 12, fontWeight: 900, textTransform: "uppercase" }}>{guide.label} · Interview guide</div><h1 style={{ fontSize: "clamp(28px, 5vw, 48px)", lineHeight: 1.08, margin: "10px 0" }}>{guide.title}</h1><p style={{ color: "#a9bad1", fontSize: 17, lineHeight: 1.55 }}>{guide.description}</p></header><section style={sectionStyle}><div style={eyebrow}>SAY THIS FIRST</div><h2>Direct answer</h2><p style={{ fontSize: 18, color: "#f1f7ff" }}>{guide.body}</p></section><section style={sectionStyle}><div style={eyebrow}>INTERVIEW STRUCTURE</div><h2>Build your answer step by step</h2><ol style={{ display: "grid", gap: 9, paddingLeft: 22 }}>{guide.steps.map((step) => <li key={step} style={{ background: "#101d30", border: "1px solid #253b57", borderRadius: 8, padding: 13 }}>{step}</li>)}</ol></section><section style={{ ...sectionStyle, background: "#101d30", border: "1px solid #253b57", borderRadius: 9, padding: 16 }}><h2 style={{ marginTop: 0 }}>Practice this topic</h2><p>Turn this guide into a timed mock and get feedback on correctness, depth, examples, trade-offs, and communication.</p><Link href="/?workspace=java-digest" style={{ color: "#8bd3ff" }}>Open practice workspace →</Link></section></article></main></>; }
const sectionStyle = { color: "#c7d5e8", fontSize: 16, lineHeight: 1.65, marginTop: 26 };
const eyebrow = { color: "#72d0a6", fontSize: 11, fontWeight: 900, letterSpacing: ".08em" };
export function getStaticPaths() { return { paths: PUBLIC_STACK_GUIDES.map((guide) => ({ params: { stack: guide.stack, slug: guide.slug } })), fallback: false }; }
export function getStaticProps({ params }) { const guide = getStackGuide(params.stack, params.slug); return guide ? { props: { guide } } : { notFound: true }; }
