import { useState } from 'react';
import { capacityEstimate } from '../../lib/dailyPractice.mjs';
const empty = { name: 'Untitled design', components: [], connections: [], requirements: '', decision: '', tradeOff: '', assumptions: { users: 10000, requestsPerDay: 20, peakFactor: 5, bytesPerWrite: 1024, writePercent: 10, retentionDays: 30 }, scenario: 'Dependency timeout', defense: '' };
export default function DesignWorkbench({ initialSelectedId, designs, onChange, saveStatus, canvas, onRestoreCanvas, onReview }) {
  const [selectedId, setSelectedId] = useState(initialSelectedId || null);
  const selected = designs.find(d => d.id === selectedId) || designs.at(-1);
  const draft = selected?.draft || empty;
  const update = (next) => {
    const design = selected || { id: crypto.randomUUID(), versions: [] };
    const updated = { ...design, draft: next, updatedAt: new Date().toISOString() };
    setSelectedId(design.id);
    onChange([...designs.filter(d => d.id !== design.id), updated]);
  };
  const estimate = capacityEstimate(draft.assumptions);
  return <section className="practice-panel"><h2>Your saved designs</h2><p role="status">Autosave: {saveStatus === 'saved' ? 'Saved on this device' : saveStatus === 'error' ? 'Failed — retry device save before leaving' : 'Loading'}</p><label>Saved design<select value={selected?.id || ''} onChange={e => setSelectedId(e.target.value)}><option value="">Select design</option>{designs.map(d => <option key={d.id} value={d.id}>{d.draft.name}</option>)}</select></label><button onClick={() => { const id = crypto.randomUUID(); onChange([...designs, { id, draft: { ...empty, name: `Design ${designs.length + 1}` }, versions: [] }]); setSelectedId(id); }}>New design</button><label>Design name<input value={draft.name} onChange={e => update({ ...draft, name: e.target.value })} /></label>
    {['requirements', 'decision', 'tradeOff'].map(key => <label key={key}>{({ requirements: 'Requirements and constraints', decision: 'Architecture decision — which requirement does it satisfy?', tradeOff: 'Trade-offs and rejected alternatives' })[key]}<textarea value={draft[key]} onChange={e => update({ ...draft, [key]: e.target.value })} /></label>)}
    <h3>Editable architecture</h3><button onClick={() => update({ ...draft, components: [...draft.components, { id: crypto.randomUUID(), name: 'Service', responsibility: '' }] })}>Add component</button>
    {draft.components.map(c => <div key={c.id}><label>Component name<input value={c.name} onChange={e => update({ ...draft, components: draft.components.map(v => v.id === c.id ? { ...v, name: e.target.value } : v) })} /></label><label>Responsibility and requirement<input value={c.responsibility} onChange={e => update({ ...draft, components: draft.components.map(v => v.id === c.id ? { ...v, responsibility: e.target.value } : v) })} /></label><button onClick={() => update({ ...draft, components: draft.components.filter(v => v.id !== c.id), connections: draft.connections.filter(v => v.from !== c.id && v.to !== c.id) })}>Remove {c.name}</button></div>)}
    <button disabled={draft.components.length < 2} onClick={() => update({ ...draft, connections: [...draft.connections, { id: crypto.randomUUID(), from: draft.components[0].id, to: draft.components[1].id, contract: 'HTTPS' }] })}>Add connection</button>
    {draft.connections.map(c => <div key={c.id}>{['from', 'to'].map(key => <label key={key}>{key === 'from' ? 'Source component' : 'Destination component'}<select value={c[key]} onChange={e => update({ ...draft, connections: draft.connections.map(v => v.id === c.id ? { ...v, [key]: e.target.value } : v) })}>{draft.components.map(v => <option key={v.id} value={v.id}>{v.name}</option>)}</select></label>)}<label>Connection contract<input value={c.contract} onChange={e => update({ ...draft, connections: draft.connections.map(v => v.id === c.id ? { ...v, contract: e.target.value } : v) })} /></label><button onClick={() => update({ ...draft, connections: draft.connections.filter(v => v.id !== c.id) })}>Remove connection</button></div>)}
    <ul aria-label="Architecture connections">{draft.connections.map(c => <li key={c.id}>{draft.components.find(v => v.id === c.from)?.name} → {draft.components.find(v => v.id === c.to)?.name}: {c.contract}</li>)}</ul>
    <details><summary>Capacity calculator with assumptions</summary>{Object.entries(draft.assumptions).map(([key, value]) => <label key={key}>{({ users: 'Daily active users', requestsPerDay: 'Requests per user per day', peakFactor: 'Peak multiplier', bytesPerWrite: 'Bytes per write', writePercent: 'Write percentage', retentionDays: 'Retention days' })[key]}<input type="number" min="0" max={key === 'writePercent' ? 100 : undefined} value={value} onChange={e => update({ ...draft, assumptions: { ...draft.assumptions, [key]: e.target.value } })} /></label>)}<p role="status">{estimate ? `Average QPS = users × requests / 86,400 = ${estimate.averageQps.toFixed(2)}. Peak QPS = average × multiplier = ${estimate.peakQps.toFixed(2)}. Raw storage = daily requests × write fraction × bytes × retention = ${estimate.storageBytes.toLocaleString()} bytes (excludes replicas and indexes).` : 'Enter non-negative assumptions and a write percentage from 0 to 100.'}</p></details>
    <label>Failure scenario<select value={draft.scenario} onChange={e => update({ ...draft, scenario: e.target.value })}>{['Dependency timeout', 'Duplicate events', 'Traffic spike'].map(v => <option key={v}>{v}</option>)}</select></label><label>Defend your design: affected component, detection, recovery and trade-off<textarea value={draft.defense} onChange={e => update({ ...draft, defense: e.target.value })} /></label>
    <button onClick={() => { const design = selected || { id: crypto.randomUUID(), versions: [] }; const next = { ...design, draft, versions: [...design.versions, { id: crypto.randomUUID(), at: new Date().toISOString(), draft, canvas }] }; onChange([...designs.filter(v => v.id !== design.id), next]); setSelectedId(design.id); }}>Save named version</button>
    <button disabled={!draft.components.length} onClick={() => onReview(`Critique this user-authored design. Reference component names and connection contracts. Link each issue to a requirement, question the capacity assumptions, and ask the candidate to defend one trade-off under ${draft.scenario}. Do not claim mastery. Design: ${JSON.stringify(draft)}`)}>Review my design</button>
    <details><summary>Version history · {selected?.versions.length || 0}</summary>{selected?.versions.map(v => <p key={v.id}>{v.draft.name} · {v.at}<button onClick={() => { update(v.draft); onRestoreCanvas(v.canvas); }}>Restore version</button></p>)}</details>
  </section>;
}
