import { useEffect, useState } from 'react';
import { EXECUTABLE_LESSONS, runLesson } from '../../lib/executableLessons.mjs';
const key = 'interviewiq.executableDsa.v1';
export default function ExecutableDsa() {
  const [state, setState] = useState({ id: 'max', input: '[4,1,7,3]', target: '7', progress: {}, notes: {} });
  const [ready, setReady] = useState(false);
  const [saveStatus, setSaveStatus] = useState('Loading');
  const [step, setStep] = useState(0);
  useEffect(() => { try { const saved = JSON.parse(localStorage.getItem(key)); if (saved && EXECUTABLE_LESSONS.some(l => l.id === saved.id)) setState(saved); } catch { /* Keep usable defaults for malformed local data. */ } setReady(true); }, []);
  useEffect(() => { if (!ready) return; try { localStorage.setItem(key, JSON.stringify(state)); setSaveStatus('Saved on this device'); } catch { setSaveStatus('Save failed. Export your work before leaving.'); } }, [state, ready]);
  const lesson = EXECUTABLE_LESSONS.find(l => l.id === state.id);
  let result, error;
  try { result = runLesson(state.id, JSON.parse(state.input), Number(state.target)); } catch (e) { error = e.message; }
  const frame = result?.frames[Math.min(step, result.frames.length - 1)];
  return <details className="practice-panel"><summary>Executable DSA practice · input, code and trace together</summary><p>JavaScript (ES2015+). Complete reference solutions below; the main lab also contains starter templates. Checked examples do not imply every curriculum example has been verified.</p><label>Executable lesson<select value={state.id} onChange={e => { setState({ ...state, id: e.target.value }); setStep(0); }}>{EXECUTABLE_LESSONS.map(l => <option key={l.id} value={l.id}>{l.title}</option>)}</select></label><p>{lesson.statement}</p><p>{lesson.constraints}</p><p><strong>Brute force:</strong> {lesson.bruteForce}</p><p><strong>Improved:</strong> {lesson.improved}</p><label>Input JSON<input value={state.input} onChange={e => { setState({ ...state, input: e.target.value }); setStep(0); }} /></label>{state.id === 'binary-search' && <label>Target<input type="number" value={state.target} onChange={e => { setState({ ...state, target: e.target.value }); setStep(0); }} /></label>}{error ? <p role="alert">{error}</p> : <><p>Output: {JSON.stringify(result.output)}</p><pre aria-label="Synchronized code">{lesson.code.map((line, i) => <div key={i} style={{ background: frame.line === i + 1 ? '#1e40af' : 'transparent', color: frame.line === i + 1 ? 'white' : 'inherit' }}>{i + 1}. {line}</div>)}</pre><p role="status">Step {Math.min(step + 1, result.frames.length)} / {result.frames.length} · Variables: {JSON.stringify(frame)}</p><button disabled={step <= 0} onClick={() => setStep(step - 1)}>Previous step</button><button disabled={step >= result.frames.length - 1} onClick={() => setStep(step + 1)}>Next step</button></>}<p>{lesson.complexity}</p><label>Explain your invariant<textarea value={state.notes?.[state.id] || ''} onChange={e => setState({ ...state, notes: { ...state.notes, [state.id]: e.target.value } })} /></label><details><summary>Compare your invariant</summary><p>{lesson.invariant}</p></details><ul>{lesson.tests.map((t, i) => <li key={i}>{i === 0 ? 'Normal' : i === 1 ? 'Boundary' : 'Adversarial'}: {JSON.stringify(t.input)} → {JSON.stringify(t.output)} · Executed: {JSON.stringify(runLesson(lesson.id, t.input, t.target).output) === JSON.stringify(t.output) ? 'passes' : 'FAIL — report this example'}</li>)}</ul>{['Understood', 'Implemented', 'Solved independently'].map(label => <label key={label}><span><input type="checkbox" checked={Boolean(state.progress?.[state.id]?.[label])} onChange={e => setState({ ...state, progress: { ...state.progress, [state.id]: { ...state.progress?.[state.id], [label]: e.target.checked } } })} /> {label} (self-reported)</span></label>)}<p role="status">{saveStatus}</p><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isSafeInteger" target="_blank" rel="noreferrer">JavaScript safe integer reference</a></details>;
}
