/* eslint-disable @next/next/no-html-link-for-pages -- RSS is a native XML document. */
import Link from "next/link";
import { useEffect, useState } from "react";
import ReaderLayout from "../components/reader/ReaderLayout";
import { DIGEST_ISSUE, readingItem } from "../lib/readerEditorial.mjs";
import styles from "../styles/Reader.module.css";
export default function Digest() {
  const [available, setAvailable] = useState(false); const [email, setEmail] = useState(""); const [consent, setConsent] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("Checking email signup availability…");
  useEffect(() => { let active = true; fetch("/api/digest-subscription").then(r => r.json()).then(data => { if (active) { setAvailable(data.available === true); setMessage(data.available ? "Confirm by email before receiving any issues. Unsubscribe from any issue." : "Email subscriptions are not enabled yet. No email addresses are being collected. Follow the RSS feed meanwhile."); } }).catch(() => { if (active) setMessage("Signup is unavailable right now. Please use the RSS feed."); }); return () => { active = false; }; }, []);
  async function subscribe(event) { event.preventDefault(); setBusy(true); try { const response = await fetch("/api/digest-subscription", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, consent }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Signup failed."); setMessage(data.message); setEmail(""); setConsent(false); } catch (error) { setMessage(error.message); } finally { setBusy(false); } }
  return <ReaderLayout title="The engineering digest" description="One explanation, one challenge, and one practical takeaway. Preview before opting in."><p className={styles.eyebrow}>DIGEST PREVIEW · {DIGEST_ISSUE.date}</p><h1>{DIGEST_ISSUE.title}</h1><section className={styles.card}><h2>One explanation</h2><Link href={DIGEST_ISSUE.explanation}>{readingItem(DIGEST_ISSUE.explanation).title}</Link><h2>One challenge</h2><Link href={DIGEST_ISSUE.challenge}>{readingItem(DIGEST_ISSUE.challenge).title}</Link><h2>One practical takeaway</h2><p>{DIGEST_ISSUE.takeaway}</p></section><h2>A weekly rhythm, once delivery is ready.</h2><p>No launch date or publishing streak is implied by this preview.</p><form onSubmit={subscribe}><label>Email address<input type="email" required disabled={!available} value={email} onChange={e => setEmail(e.target.value)} autoComplete="email" /></label><label><input type="checkbox" disabled={!available} checked={consent} onChange={e => setConsent(e.target.checked)} />I want one weekly engineering digest by email. I understand I must confirm my address and can unsubscribe at any time.</label><button disabled={!available || !consent || busy}>{busy ? "Requesting confirmation…" : "Send confirmation email"}</button><p role="status">{message}</p></form><p><a href="/rss.xml">Read the RSS feed</a> · <Link href="/editorial">Our subscription promise</Link></p></ReaderLayout>;
}
