import { useEffect, useId, useMemo, useRef, useState } from 'react';
import { analyzeGraph, challengeRevision, normalizeRevision, revisionChanges } from '../../lib/designRevision.mjs';
import styles from '../../styles/DesignRevision.module.css';

function Diagram({ graph, label }) {
  const arrowId = useId();
  const container = useRef(null);
  const [columns, setColumns] = useState(2);
  useEffect(() => {
    const observer = new ResizeObserver(entries => setColumns(entries[0].contentRect.width < 360 ? 1 : 2));
    if (container.current) observer.observe(container.current);
    return () => observer.disconnect();
  }, []);
  const warnings = analyzeGraph(graph);
  const position = id => { const i = graph.nodes.findIndex(n => n.id === id); return { x: columns === 1 ? 120 : 135 + (i % 2) * 330, y: 60 + Math.floor(i / columns) * 140 }; };
  return <figure ref={container} className={styles.diagram}><figcaption>{label}</figcaption><svg role="img" aria-label={`${label} architecture diagram`} viewBox={`0 0 ${columns === 1 ? 300 : 600} ${Math.max(140, Math.ceil(graph.nodes.length / columns) * 140)}`}>
    <defs><marker id={arrowId} markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 Z" fill="#bd875b" /></marker></defs>
    {graph.edges.map(e => { const a = position(e.from), b = position(e.to), risk = warnings.some(w => w.edge === e.id), dx = b.x - a.x, dy = b.y - a.y, clip = Math.min(100 / Math.abs(dx || .001), 25 / Math.abs(dy || .001)); return <g key={e.id}><title>{`${e.from} → ${e.to}: ${e.protocol}, ${e.mode}, ${e.data}`}</title><line x1={a.x + dx * clip} y1={a.y + dy * clip} x2={b.x - dx * clip} y2={b.y - dy * clip} markerEnd={`url(#${arrowId})`} stroke={risk ? '#db6b4a' : '#668faf'} strokeWidth="3" strokeDasharray={e.mode === 'async' ? '7 5' : undefined} /><text x={columns === 1 ? 135 : (a.x + b.x) / 2} y={(a.y + b.y) / 2 - 13} textAnchor={columns === 1 ? "start" : "middle"} fill="currentColor" fontSize="13">{e.protocol.slice(0, 15)} · {e.mode}</text></g>; })}
    {graph.nodes.map(n => { const p = position(n.id), risk = warnings.some(w => w.node === n.id); return <g key={n.id}><rect x={p.x - 100} y={p.y - 25} width="200" height="50" rx="8" fill={risk ? '#442d27' : '#153650'} stroke={risk ? '#ffab8b' : '#8bd3ff'} /><text x={p.x} y={p.y + 5} textAnchor="middle" fill="#fff" fontSize="15">{n.name.slice(0, 20)}{risk ? ' ⚠' : ''}</text></g>; })}
  </svg><p>Arrows show direction; dashed connections are asynchronous. Warning marks and orange paths identify review findings. Full connection details appear below.</p><ul>{graph.edges.map(e => <li key={e.id}>{graph.nodes.find(n => n.id === e.from)?.name} → {graph.nodes.find(n => n.id === e.to)?.name}: {e.protocol}, {e.mode}, {e.data}; timeout {e.timeout} ms, maximum {e.attempts} attempts.</li>)}</ul></figure>;
}
export default function DesignRevisionWorkshop({ value, onChange }) {
  const state = useMemo(() => normalizeRevision(value), [value]);
  const [message, setMessage] = useState('');
  const findings = analyzeGraph(state.graph);
  const changes = revisionChanges(state.baseline, state.graph);
  const update = next => { onChange?.(next); setMessage('Revision updated. Use Save revision to verify browser storage.'); };
  const node = (id, field, value) => update({ ...state, graph: { ...state.graph, nodes: state.graph.nodes.map(n => n.id === id ? { ...n, [field]: value } : n) } });
  const edge = (id, field, value) => update({ ...state, graph: { ...state.graph, edges: state.graph.edges.map(e => e.id === id ? { ...e, [field]: value } : e) } });
  function save() {
    try { localStorage.setItem('interviewiq.designRevision.backup.v1', JSON.stringify(state)); setMessage('Revision, baseline, decisions and risks saved in this browser.'); }
    catch { setMessage('Browser storage is unavailable. Download the revision before leaving.'); }
  }
  function download() {
    const url = URL.createObjectURL(new Blob([JSON.stringify(state, null, 2)], { type: 'application/json' }));
    const a = document.createElement('a'); a.href = url; a.download = 'design-revision.json'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
  }
  return <section className={styles.workshop} aria-label="Design revision workspace"><h2>Design → Challenge → Revise → Explain</h2><p>The same revision is available in System Canvas and Design Lab. This notification-service exercise is separate from the existing text brief. All feedback below is deterministic; no AI or live infrastructure is required.</p>
    <label>Revision title<input value={state.title} maxLength={200} onChange={e => update({ ...state, title: e.target.value })} /></label>
    <div className={styles.grid}>{['requirements', 'constraints'].map(field => <label key={field}>{field === 'requirements' ? 'Requirements and success criteria' : 'Constraints and budget'}<textarea value={state[field]} maxLength={2000} rows={4} onChange={e => update({ ...state, [field]: e.target.value })} /></label>)}</div>
    {!state.baseline ? <><p>Make your initial design explicit, then freeze it before introducing the failure. The baseline cannot be overwritten by later edits.</p><button disabled={!state.graph.nodes.some(n => n.id === 'node-3')} onClick={() => update(challengeRevision(state))}>Freeze baseline and introduce provider outage</button><p>The exercise uses the original Provider component as its failure target. Keep that component until the challenge is introduced.</p></> : <aside className={styles.challenge}><h3>Changed constraint</h3><p>{state.change}</p><p>Revise the graph, then explain which choices changed, their costs, and the risks that remain.</p></aside>}
    <div className={styles.grid}>{state.baseline && <Diagram graph={state.baseline} label="Before: frozen baseline" />}<Diagram graph={state.graph} label={state.baseline ? 'After: current revision' : 'Initial design'} /></div>
    <details><summary>Edit components and assumptions</summary><h3>Components and assumptions</h3><p>Traffic and capacity are requests or jobs per second; capacity is per replica. Latency is an assumed component p95 in milliseconds. These are independent inputs, not measured predictions.</p>
    <div className={styles.grid}>{state.graph.nodes.map(n => <fieldset key={n.id}><legend>{n.name || 'Unnamed component'}</legend><label>Component name<input value={n.name} maxLength={80} onChange={e => node(n.id, 'name', e.target.value)} /></label>{[['traffic', 'Traffic / second'], ['capacity', 'Capacity / second / replica'], ['latency', 'Latency p95 (ms)'], ['replicas', 'Replica count']].map(([key, title]) => <label key={key}>{title}<input type="number" min={key === 'replicas' ? 1 : 0} max={1000000000} value={n[key]} onChange={e => node(n.id, key, Number(e.target.value))} /></label>)}{[['storage', 'Storage and retention'], ['consistency', 'Consistency and delivery guarantee']].map(([key, title]) => <label key={key}>{title}<input value={n[key]} maxLength={300} onChange={e => node(n.id, key, e.target.value)} /></label>)}<label className={styles.check}><input type="checkbox" checked={n.available} onChange={e => node(n.id, 'available', e.target.checked)} />Available in this scenario</label><button onClick={() => update({ ...state, graph: { nodes: state.graph.nodes.filter(x => x.id !== n.id), edges: state.graph.edges.filter(e => e.from !== n.id && e.to !== n.id) } })}>Remove {n.name || 'component'}</button></fieldset>)}</div>
    <button disabled={state.graph.nodes.length >= 12} onClick={() => update({ ...state, graph: { ...state.graph, nodes: [...state.graph.nodes, { id: `node-${Date.now()}`, name: 'New component', traffic: 0, capacity: 0, latency: 0, replicas: 1, available: true, storage: '', consistency: '' }] } })}>Add component</button></details>
    <details><summary>Edit connections and failure controls</summary><h3>Connections and failure controls</h3><div className={styles.grid}>{state.graph.edges.map(e => <fieldset key={e.id}><legend>Connection {state.graph.edges.indexOf(e) + 1}</legend>{[['from', 'Source'], ['to', 'Destination']].map(([key, title]) => <label key={key}>{title}<select value={e[key]} onChange={event => edge(e.id, key, event.target.value)}>{state.graph.nodes.filter(n => n.id !== e[key === 'from' ? 'to' : 'from']).map(n => <option key={n.id} value={n.id}>{n.name}</option>)}</select></label>)}<label>Protocol<input value={e.protocol} maxLength={80} onChange={event => edge(e.id, 'protocol', event.target.value)} /></label><label>Data flow<input value={e.data} maxLength={200} onChange={event => edge(e.id, 'data', event.target.value)} /></label><label>Interaction<select value={e.mode} onChange={event => edge(e.id, 'mode', event.target.value)}><option value="sync">Synchronous</option><option value="async">Asynchronous</option></select></label>{[['timeout', 'Timeout (ms) — 0 means unspecified'], ['attempts', 'Maximum attempts including first']].map(([key, title]) => <label key={key}>{title}<input type="number" min={key === 'attempts' ? 1 : 0} max={key === 'attempts' ? 10 : 1000000000} value={e[key]} onChange={event => edge(e.id, key, Number(event.target.value))} /></label>)}<button onClick={() => update({ ...state, graph: { ...state.graph, edges: state.graph.edges.filter(x => x.id !== e.id) } })}>Remove connection {state.graph.edges.indexOf(e) + 1}</button></fieldset>)}</div>
    <button disabled={state.graph.nodes.length < 2 || state.graph.edges.length >= 24} onClick={() => update({ ...state, graph: { ...state.graph, edges: [...state.graph.edges, { id: `edge-${Date.now()}`, from: state.graph.nodes[0].id, to: state.graph.nodes[1].id, protocol: 'HTTPS', data: '', mode: 'sync', timeout: 200, attempts: 1 }] } })}>Add connection</button></details>
    <section aria-label="Failure path review"><h3>Failure path review</h3><p>Review prompts, not a correctness score. Replicas do not prove independent failure domains; p95 values cannot simply be added. Queue growth, storage durability, retry jitter, and real capacity require testing.</p>{findings.length ? <ul>{findings.map((f, i) => <li key={i}>{f.message}</li>)}</ul> : <p>No configured rule fired. This does not establish resilience.</p>}</section>
    {state.baseline && <section><h3>What changed</h3>{changes.length ? <ul>{changes.map((change, i) => <li key={i}>{change}</li>)}</ul> : <p>The architecture is unchanged. Explain why keeping it is justified.</p>}</section>}
    { [['notes', 'Explain each change and what stayed'], ['decisions', 'Decisions and trade-offs'], ['risks', 'Unresolved risks and evidence that would change your mind']].map(([key, title]) => <label key={key}>{title}<textarea rows={4} maxLength={4000} value={state[key]} onChange={e => update({ ...state, [key]: e.target.value })} /></label>)}
    <div className={styles.actions}><button onClick={save}>Save revision</button><button onClick={download}>Download revision JSON</button><button onClick={() => { try { const saved = localStorage.getItem('interviewiq.designRevision.backup.v1'); if (!saved) { setMessage('No explicit revision backup has been saved.'); return; } const parsed = JSON.parse(saved); if (!Array.isArray(parsed?.graph?.nodes) || !Array.isArray(parsed?.graph?.edges)) throw new Error('Invalid saved revision'); update(normalizeRevision(parsed)); setMessage('Saved revision restored.'); } catch { setMessage('Saved revision could not be restored.'); } }}>Restore saved revision</button></div><p role="status">{message}</p><p>The explicit backup stays in this browser; this revision also travels with your saved practice session. Download a copy before clearing browser data.</p>
  </section>;
}
